### ISSUE TITLE
Fails to build with WITH_TBLITE=ON with the external tblite-0.2.0

### ISSUE THREAD

**Issue by yurivict** [dftbplus/dftbplus#1041]
configure discovers it, but the build later fails:
```
/usr/local/bin/ld: /usr/local/lib/libtblite.so.0.2.0: undefined reference to `__dftd3_ncoord_MOD_add_coordination_number_derivs'
```

All tests pass after the tblite build.

Version: 22.1
OS: FreeBSD 13.1

**Comment by awvwgk** [comment]
Seems like an issue in `tblite` rather than DFTB+, is this issue reproducible only in DFTB+ but also with a standalone build of `tblite`?

**Comment by yurivict** [comment]
All tests pass in ```tblite``` and ```dftb+```.

**Comment by yurivict** [comment]
not stale

**Comment by yurivict** [comment]
Not stale!
