### ISSUE TITLE
Running MD simulation using Nose Hoover Thermostat

### ISSUE THREAD

**Issue by hananrizal** [dftbplus/dftbplus#1054]
Dear all,

I've performed molecular dynamics simulations using barendsen thermostat before, but the result isn't good. so i've plan to try using nose hoover thermostat.  the question are:
1. how can I run molecular dynamics simulations using nose hoover thermostat ? is it possible the result will be different ?
2. what is the x, v, and g in the md.out file ? how can i use it ?

Waiting for your kind reply.

Best regards,
Hanan Rizal.

**Comment by aradi** [comment]
See reply on the DFTB+ User mailing list.
