### ISSUE TITLE
Space group symmetry

### ISSUE THREAD

**Issue by pcazade** [dftbplus/dftbplus#1057]
Dear Developers,

Are there any plans to implement space group symmetry in DFTB+? The library Spglib (https://spglib.github.io/spglib/) is very helpful in doing so.

Regards,
Pierre

**Comment by aradi** [comment]
Dear Pierre,

there are no immediate plans about recognizing space group symmetries. Not that we would not find it useful (although, in most cases you rather apply DFTB+ to larger systems with low symmetries), but we did not find the time to attach spglib to DFTB+.

**Comment by husakm** [comment]
It is not about space group recognition, it is about using the space group information to force symmetry, simplify input. And if correctly implemented speed up calculation becouse only the asymetric part of the unit cell need modification. Unfortunately most programs are not able to do this ...
