### ISSUE TITLE
DFTB+ 21.2 crashes and idles using 1 core w/o error.

### ISSUE THREAD

**Issue by galjos** [dftbplus/dftbplus#1062]
*DFTBPLUS version is 21.2.*

*Problem:*
The calculation randomly stops and idles using 1 core without any error, warning or other kind of output.
The system is ruffly 800 atoms large and the calculation consists of a geometry optimization.
Has anyone seen a similar issue? Are there some input keywords or a specific compilation setup that would eliminate this issue?

*It is compiled with the following options:*
WITH_API                         ON                                                                                                                                            
WITH_API_V2                   ON                                                                                                                                             
WITH_ARPACK                 ON                                                                                                                                             
WITH_CHIMES                 OFF                                                                                                                                           
WITH_ELSI                       OFF                                                                                                                                            
WITH_GPU                       ON                                                                                                                                             
WITH_MBD                       ON                                                                                                                                            
WITH_MPI                         OFF                                                                                                                                           
WITH_OMP                       ON                                                                                                                                             
WITH_PLUMED                OFF                                                                                                                                           
WITH_POISSON              ON                                                                                                                                            
WITH_PYTHON               ON                                                                                                                                             
WITH_SDFTD3                ON                                                                                                                                             
WITH_SOCKETS             ON                                                                                                                                            
WITH_TBLITE                  ON                                                                                                                                             
WITH_TRANSPORT        OFF                                                                                                                                            
WITH_UNIT_TESTS        OFF   

*Geometry Optimization:*
Driver LBFGS
Hamiltonian DFTB with SCCTolerance = 1.0e-7, MaxSCCIterations = 200, dispersion = DftD3, ThirdOrderFull = Yes and mixer = anderson.

**Comment by aradi** [comment]
Did you try to change the solver (e.g. to QR)? Sometimes divideandconquer and relatively robust just stop.

**Comment by aradi** [comment]
Yes, unfortunately, QR is the slowest eigensolver within LAPACK/ScaLAPACK. But at the same time also the most robust one, and ususally does not stop unexpectedly.

As an alternative, you may try to make an MPI-parallel compilation with ELSI and test, whether the ELPA solver is more robust for your system.
