### ISSUE TITLE
Problem reading poscar coordinates: no more than 384 atomes read

### ISSUE THREAD

**Issue by Madebene** [dftbplus/dftbplus#1063]
I just started to play with DFTB+, last stable version installed with anaconda on a CENTOS 7 dell R640 computer (48core, 392GB RAM)

I try to play with a 20Ang box of 266 water with a small organic molecule inside. I am using xtb hamiltonian.
I found the problem on geometry optimization, but it also happen for single point energy calculation: 

From vasp postcar coordinates file, only the 384 first atoms are used. 
No error message. Others atoms of the input are just ignored And calculation goes on.
It works fine for generic coordinates.

DFTB+ input file and vasp coordinate file are  in attachment.

Best,
Bruno Madebène

[detailed.zip](https://github.com/dftbplus/dftbplus/files/9073922/detailed.zip)

**Comment by akakcolin** [comment]
This is a problem with your POSCAR format not DFTB，you may need to create an list of symbols
that accounts for repeating atoms

**Comment by awvwgk** [comment]
The coordinate file seems fine for the Poscar reader:

```
❯ mctc-convert toto.pos -i poscar - -o gen | head
829 S
 H O C N
    1    1    6.06800000000000E+00    5.41000000000000E-01    3.00500000000000E+00
    2    1    6.69600000000000E+00    1.23000000000000E-01    1.55700000000000E+00
    3    2    6.78000000000000E+00    1.00000000000000E-02    2.54600000000000E+00
    4    1    4.81000000000000E-01    1.46500000000000E+00    1.63860000000000E+01
    5    1    1.53800000000000E+00    2.35000000000000E-01    1.61890000000000E+01
    6    2    1.44900000000000E+00    1.21200000000000E+00    1.63790000000000E+01
    7    1    7.42000000000000E+00    3.33800000000000E+00    5.00000000000000E-03
    8    1    7.81100000000000E+00    2.01000000000000E+00    8.71000000000000E-01
```

The issue is most likely that DFTB+ truncates lines at 1000 characters before handing them to the reader (`mctc-lib` itself can read arbitrary long lines).

**Comment by aradi** [comment]
Yes, it seems indeed to be a problem with the fixed line length in the parser. As a quick fix, you could just increase the line length at

https://github.com/dftbplus/dftbplus/blob/9b6a275163b03e8990cc1be9144a3130c2a5720a/src/dftbp/io/hsdparser.F90#L137

Making everything dynamical would take somewhat longer, as it would invoke a lot of dynamic allocation/reallocation while we process the strings ...

**Comment by awvwgk** [comment]
> Making everything dynamical would take somewhat longer, as it would invoke a lot of dynamic allocation/reallocation while we process the strings ...

Not that much and it is quite straight-forward to implement (see https://stdlib.fortran-lang.org/page/specs/stdlib_io.html#getline).

**Comment by aradi** [comment]
The problem is not getting the line itself, the problem is the many `lhs = rhs(from:to)` kind of character assignments we have afterwards, which would have to be made all dynamic. I would have to test first, whether these deteriorate the parser.

**Comment by Madebene** [comment]
Thanks.
Use of poscar coordinate is not necessary for me. Generics work fine.
I just mentioned it to save someone else from wasting time with this problem.
This does not seem to be an urgent problem to deal with, but a least a warning message could be usefull. 
It's quite disturbing that the calculation starts without any alert when the number of atoms does not correspond to the number of coordinates.
Thanks again for the time and the nice works you are doing on this code.

**Comment by awvwgk** [comment]
>  It's quite disturbing that the calculation starts without any alert when the number of atoms does not correspond to the number of coordinates.

Not sure if we can produce a meaningful warning. We can detect trailing lines, in case of `xyz` we actually check whether the line count matches the declared number of atoms. In [CONTCAR](https://www.vasp.at/wiki/index.php/CONTCAR) files there can be further lines specifying restart information, which could interfere with this kind of check.

**Comment by aradi** [comment]
@Madebene I absolutely agree with you, the program should not silently truncate an exceeding line length (sorry for the current behavior). I've created a PR (#1066), which would for your input generate the error message
```
ERROR!
-> HSD parser error: File 'toto.pos', Line    6.
-> Line exceeds maximal line length of the HSD parser
```
Still suboptimal, as dynamic length would be the desirable option, but fails at least explicit enough. :wink:
