### ISSUE TITLE
Latest numpy version (1.23.1) breaks ASE DFTB+ compatibility. 

### ISSUE THREAD

**Issue by kimrojas** [dftbplus/dftbplus#1064]
**Describe the bug**
numpy (version 1.23) breaks ASE + DFTB+ compatibility

**To Reproduce**
```bash
conda create -n test -c conda-forge python=3.8 mamba
conda activate test
conda install -c conda-forge 'dftbplus=22.1=nompi_*' ase=3.22.1 cython mpi4py pytest cymem numpy dftbplus-tools dftbplus-python

python 01_dftb.py
```

1. Trigger is to just run the python code with ASE + Dftb+ contents
2. conda-forge build (serial v22.1)
3. Output of error

```
  File "/home/krojas/.conda/envs/test/lib/python3.8/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: Found an unquoted embedded newline within a single line of input.  This is currently not supported.
```

INPUT FILE: `01_dftb.py`
```python 
#!/usr/bin/env python 

import os
from ase.calculators.dftb import Dftb
from ase.io import write, read

### Slater-koster files (relative path)
skdir = os.path.abspath('../slater-koster')

os.environ['DFTB_PREFIX'] = skdir
os.environ['ASE_DFTB_COMMAND'] = 'dftb+ > PREFIX.out' 


### Define system
atoms = read('hb.txt', format='vasp')


### Define calculator ###
calc = Dftb(label='run_files/hb',
            Hamiltonian_SCC='Yes',
            Hamiltonian_MaxAngularMomentum_='',
            Hamiltonian_MaxAngularMomentum_B='"p"',
            Hamiltonian_MaxAngularMomentum_H='"s"',
            Hamiltonian_Charge='0.000000',
            Hamiltonian_Filling='Fermi {',
            Hamiltonian_Filling_empty='Temperature [Kelvin] = 0.000000',
            kpts=[8,8,1])

atoms.calc =  calc

en = atoms.get_potential_energy()

print(en)
```
All input and output files required to confirm your report. -->

**Expected behaviour**
It will run a simple energy calculation and print it out.

**Additional context**
I also tested some other system. weirdly enough, h2o system (non-pbc) works. I also tested O2 system (non-pbc) and I get the same error.

Changing the numpy version to 1.22.1 instead of the latest 1.23.1 solves the issue. I am not sure what makes the h2o system work but not in the o2 and hb system. Perhaps limiting the numpy version should be including in the conda setup file or documentation ?

[01_dftb.txt](https://github.com/dftbplus/dftbplus/files/9078856/01_dftb.txt)
[01_h2o.txt](https://github.com/dftbplus/dftbplus/files/9078857/01_h2o.txt)
[01_o2.txt](https://github.com/dftbplus/dftbplus/files/9078858/01_o2.txt)
[hb.txt](https://github.com/dftbplus/dftbplus/files/9078859/hb.txt)

**Comment by popsi** [comment]
I confirm that the bug exists. For my DFTB example that optimizes an MXene Mo2C layer using ASE and the QuasiNewton or BFGS optimizers the error ```ValueError: Found an unquoted embedded newline within a single line of input.  This is currently not supported.``` is printed. This was when Numpy 1.24 was installed (on Arch Linux). However, when I downgraded Numpy to version 1.22 the error vanished and calculations finished without issues.

**Comment by aradi** [comment]
OK, thanks for keeping the issue alive. We will have a look at that.

**Comment by jubich** [comment]
I have investigated the problem now and I think I found the bug. But when I created the PR in the ase repository, I saw that [the problem was fixed two months ago](https://gitlab.com/ase/ase/-/merge_requests/2819). 
In short, the problem is that if the number of eigenvalues (in "results.tag") is not divisible by the number of columns, the last row contains empty columns. The `read_eigenvalues()` method in the ase calculator fills them up with "0.0". However, since the last line ends with a "\n" symbol, the "0.0" symbols are added after that, which numpy (>=1.23) does not like. 

@kimrojas Maybe you can try the latest ase development version and see if the bug still exists. If not, then it should be fixed in the next release version of ase.

**Comment by kimrojas** [comment]
@jubich Thank you checking. Yes it seems to work properly now. 

Just to summarize, the fix is already implemented in the main branch of ASE. 
Conda and pip install uses the old version and thus haven't reflected the fix yet, hence, its recommended to use the gitlab main branch instead. 

I'll be closing the issue!
