### ISSUE TITLE
number of MPI processors

### ISSUE THREAD

**Issue by qzhu2017** [dftbplus/dftbplus#1084]
**Is your feature request related to a problem? Please describe.**
I am trying to write an automated workflow to process DFTB calculation. Sometime, I run into the the following issue.
```
 43 WARNING!
 44 -> Insufficient atoms for this number of MPI processors                              
 45 ERROR!
 46 -> Processor grid (2 x 4) too big (> 3 x 3)    
```

**Describe the solution you'd like**
For the above issue, I can manually set the number of processors to 3, 6, or 9. However, I am wondering if there are better ways to handle this situation. 
1, can we type a simple command to get the partitioned grids information from dftbplus? This way, we can set a reasonable mpi numbers by ourself
2, can you for the partition to be compatible with the assigned number of MPI processors?

**Describe alternatives you've considered**

**Additional context**

**Comment by aradi** [comment]
I think, it should be not too complicated to write a program, which reads in the input and calculates the maximal number of processes along one dimension of the 2D processor grid (in this case 3). Would that be sufficient for your purposes?

The second option is more complicated. If you specify 8 processes, but the maximal grid length along one dimension is 3, what should DFTB+ do? Take 3x2 and leave to processes idle? In theory possible, but probably not a very user friendly strategy.

**Comment by aradi** [comment]
This is something I still want to implement, so let's keep the issue alive.
