### ISSUE TITLE
3OB parameterization gives 6000 Hartree discontinuity for P-Cl distance at 2.04 A 

### ISSUE THREAD

**Issue by leifjacobson** [dftbplus/dftbplus#1087]
**Describe the bug**

3OB parameterization gives 6000 Hartree discontinuity for P-Cl distance at 2.04 A.

I'm not sure if this is a bug for a feature, I'm guessing an artifact of the repulsive potential in a poorly trained region of configuration space.  I found several very large outliers when computing DFTB energies on a dataset of organic molecules.  All of the largest outliers have P-Cl bonds and I've isolated a simple example of the molecule PCl2O2-.  Scanning the P-Cl bond shows an extremely large discontinuity at 2.04 A, linear behavior between 2.04 and 2.19A and parabolic behavior beyond 2.19A.  The minimum is around 2.37A compared to 2.15A at B3LYP/6-31G*.

Is this behavior known and expected?

**To Reproduce**

Input file (why don't you support this type of file as an attachement?)
```
Geometry = GenFormat {
    <<< "geo_end.gen"
}

Hamiltonian = DFTB{
   Charge = -1
   Dispersion = DftD3{
      Damping = BeckeJohnson{
         a1 = 0.746
         a2 = 4.191
   }
      s6 = 1.0
      s8 = 3.209
   }
   HCorrection = Damping{
      Exponent = 4.0
   }
   HalogenXCorr = Yes
   HubbardDerivs = {
      C = -0.1492
      Cl = -0.0697
      F = -0.1623
      H = -0.1857
      N = -0.1535
      O = -0.1575
      P = -0.14
      S = -0.11
   }
   MaxAngularMomentum = {
      C = p
      Cl = d
      F = p
      H = s
      N = p
      O = p
      P = p
      S = d
   }
   SCC = Yes
   ShellResolvedSCC = No
   SlaterKosterFiles = Type2FileNames{
      Prefix = /scr/jacobson/tmpxjd1niry/3ob-3-1/
      Separator = "-"
      Suffix = ".skf"
   }
   ThirdOrderFull = Yes
   }
Options {
   WriteResultsTag = Yes
}
ParserOptions {
   IgnoreUnprocessedNodes = Yes
}
Analysis {
   CalculateForces = Yes
}
```

Input 1:
```
5  C
Cl   P    O
1      1     -0.210117000000000      1.807466000000000      0.000000000000000
2      1      1.518438000000000     -0.849752000000000      0.000000000000000
3      2     -0.448914000000000     -0.340521000000000      0.000000000000000
4      3     -0.995502000000000     -0.717195000000000      1.331992000000000
5      3     -0.995502000000000     -0.717195000000000     -1.331992000000000
```

Input 2:
```
5  C
Cl   P    O
1      1     -0.212707000000000      1.808136000000000      0.000000000000000
2      1      1.525693000000000     -0.851630000000000      0.000000000000000
3      2     -0.451504000000000     -0.339850000000000      0.000000000000000
4      3     -0.998093000000000     -0.716524000000000      1.331992000000000
5      3     -0.998093000000000     -0.716524000000000     -1.331992000000000
```

**Expected behaviour**

I expected a smooth and continuous potential energy function.

**Additional context**

**Comment by awvwgk** [comment]
This is a know issue (see https://github.com/dftbparams/3ob/issues/4), there is also a fix available, but not a new release of the 3ob set.
