### ISSUE TITLE
It is necessary to save charges.bin at every step?

### ISSUE THREAD

**Issue by qzhu2017** [dftbplus/dftbplus#1088]
**Is your feature request related to a problem? Please describe.**
Not sure if it is a feature request. I noticed that the charges.bin file will be saved at the end of each SCF cycle. This is fine. But I just want to avoid the unnessary I/o load during the geometry optimization. Is there any keywords from `dftb_in.hsd` related to this?

I tried `RestartFrequency`, but it does not help for my case.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vanderhe** [comment]
Hi Qiang Zhu, sorry for the late reply. I've added a draft-PR (#1162) that introduces an additional keyword in the options input block to (de)activate writing out charges.{bin|dat}. Does this slight extension meet your requirements?

**Comment by qzhu2017** [comment]
@vanderhe Thanks, this is exactly what I want.
