### ISSUE TITLE
Optimization of the geo_end.xyz file

### ISSUE THREAD

**Issue by GES-lbabetto** [dftbplus/dftbplus#1094]
**Is your feature request related to a problem? Please describe.**
The geo_end.xyz file can become quite large for long MD simulations. 

**Describe the solution you'd like**
Saving ONLY the atom coordinates in the geo_end.xyz file (maybe with less significant digits, is such a high precision necessary for the stability of the simulation?), and storing the charge/velocities information (which, as I have understood, is only really necessary for the restart of a MD simulation) in a separate file.

**Describe alternatives you've considered**
If the current structure of the geo_end.xyz file is required, maybe an alternative would be to produce a separate trajectory file for MD simulations. Currently, I am using the following Python script to "parse" MD data into a (significantly) smaller file (including energy data from the md.out file:

```
energies = []
with open("md.out", "r") as f:
    for line in f:
        if "Total MD Energy" in line:
            energies.append(float(line.split()[3]))

  with open("geo_end.xyz", "r") as inp:
    with open(f"traj.xyz", "w") as out:
        for linenum, line in enumerate(inp):
            if linenum == 0:
                atomcount = int(line)
            if linenum % (atomcount + 2) == 0:
                out.write(f"{line.split()[0]}\n")
            if linenum % (atomcount + 2) == 1:
                out.write(f"Step: {line.split()[0]} Energy: {energies.pop(0)} Eh\n")
            if linenum % (atomcount + 2) > 1:
                out.write(
                    f"{line.split()[0]} {round(float(line.split()[1]),3)} {round(float(line.split()[2]),3)} {round(float(line.split()[3]),3)}\n"
                )
```

**Comment by aradi** [comment]
Dear Luca, you can set the restart frequency, which would probably limit the nr. of images written in the xyz-file much more efficiently. Would that be an option for you? Or do you really need all geometries of the long MD?

**Comment by GES-lbabetto** [comment]
Dear Bálint, I'm already saving the geometry every 100 steps with the mdrestartfrequency keyword, and with these settings I'm getting a file of about 1.5GB for a 4ns MD run of a cubic box with 100 water molecules inside. With the script that I posted above, the resulting .xyz file weighs about 250MB, so this "compression" cuts the files of about 80% without losing any of the information I need (which is just the structural geometry at each frame). Furthermore, if I zip the compressed .xyz I get a file of about 100MB, further improving the compression ratio from the original file.

Honestly, the biggest issue for me is not about having a large trajectory file on the workstation, it's mostly the fact that I have to download it on my low-storage PC with a slow connection, so going from a 1.5GB file to a 100MB zip makes a significant difference to my workflow 😅
