### ISSUE TITLE
Line ending in gen files

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#1100]
**Describe the bug**
Commit [36d61b61](https://github.com/dftbplus/dftbplus/pull/1066) breaks for gen files without a line termination on last line for some compilers.

Regression tests sockets/diamond and sockets/diamond_ext fail for specific compiler, with error 

ERROR!
-> Unexpected end of data
Path: dftbplusinput/Geometry/GenFormat
Line: 1-3 (File: dftb_in.hsd)

and an integer value.

**Expected behaviour**

Handle this file, or give a clean error about lack of line ending.

**Comment by aradi** [comment]
Should have been solved by f97f5f7
