### ISSUE TITLE
Installation error with Magmablas

### ISSUE THREAD

**Issue by Lopamudrac** [dftbplus/dftbplus#1137]
Hi,
I am getting the following error while trying to install magmablas.
My config are: 
CentOS, 
GPU:Tesla v100
CC        = gcc
CXX       = g++
NVCC      = nvcc
FORT      = gfortran
 ```
["__nv_associate_access_property_impl" has "C" linkage](error: more than one instance of overloaded function1 error detected in the compilation of "magmablas/zaxpycp.cu".
make: *** [Makefile:640: magmablas/zaxpycp.o] Error 1
```

**Comment by aradi** [comment]
As this is a MAGMA installation problem, please report it to the MAGMA team. We only use MAGMA as an external library.
