### ISSUE TITLE
Add more decimal places for band structure data

### ISSUE THREAD

**Issue by F-Arnold** [dftbplus/dftbplus#1146]
When calculating the band structure the energy values in the band.out file are given with 3 decimal places, so meV resolution, when using the DFTB+ 22.1 (and older versions) precompiled executables for x86_64 (64 bit) architecture. In the large solid state systems that I'm currently working on it would be nice to have a better energy resolution as the dispersion strongly decreases. This would allow to keep smooth bands without unphysical jumps originating from the limited number of decimal places. 

Is there an option to increase the default number of decimal places in the precompiled version? Alternatively, it would be great to have a keyword which allows to toggle the number of printed decimal places.

**Comment by bhourahine** [comment]
The data in results.tag (enable with Options{WriteResultsTag = Yes} ) prints the band structure values to 16 significant figures (in atomic energy units). Unfortunately the dp_bands tool doesn't read that file.

**Comment by vanderhe** [comment]
We could change this behavior as part of the python-tools restructuring from #1015.
