### ISSUE TITLE
DFTB excitation energy is OK for syn-cis-coumaric acid but fails for anti-trans if the convergence threshold is 1E-9

### ISSUE THREAD

**Issue by xiongyan21** [dftbplus/dftbplus#1150]
For DFTB3 optimized syn-cis-coumaric acid, or the anti-trans one,  DFTB3 excitation energy calculations are all OK at the convegence threshold of 1E-4 in optimization, but when that is  lowered  to 1.0E-9,  it is OK for the former, but fails for the latter.
 1  \00\00\00\00       -22.6567687981    0.000        NaN     NaN     NaN       NaN

This occurs in GAMESS.

Does it appear in DFTB+?

Very Best Regards!

**Comment by aradi** [comment]
GAMMESS is using its own DFTB implementation, so we can't comment on this. You're welcome to try it with DFTB+, if you wish.
