### ISSUE TITLE
3078 atom system geometry optimization gives forrtl: severe (154): array index out of bounds

### ISSUE THREAD

**Issue by cfarm6** [dftbplus/dftbplus#1152]
**Describe the bug**
When performing geometry optimization on a system of 3,078 atoms with both the GFN2-xTB and DFTB(matsci-0-3), after a few iSCC iterations an array index out of bounds error is generated. Below is the error messages:

**To Reproduce**
To run the program:
ulimit -s unlimited
export OMP_STACKSIZE=16000000
mpirun -np 32 dftb+

Input File:
Geometry = xyzFormat{
  <<<sys_combined.xyz
}

Driver   = GeometryOptimization{
    Optimizer = LBFGS{}
    OutputPrefix = "opt_sys"
}

Hamiltonian = DFTB {
  Scc = Yes
  SlaterKosterFiles = Type2FileNames {
    Prefix="matsci-0-3/"
    Separator = "-"
    Suffix = ".skf"
  }
  MaxAngularMomentum {
    H = "s"
    Si = "d"
    C = "p"
    O = "p"
  }
}

Parallel = {
  UseOmpThreads = Yes
}

Output:
***  Geometry step: 0

 iSCC Total electronic   Diff electronic      SCC error
     1    0.00000000E+00    0.00000000E+00    0.17413795E+01
     2   -0.47129307E+04   -0.47129307E+04    0.12906954E+01
     3   -0.48069012E+04   -0.93970541E+02    0.15255618E+01
     4   -0.48324216E+04   -0.25520366E+02    0.74575136E+00 
     5   -0.48307174E+04    0.17041295E+01    0.89815459E+00
     6   -0.48287414E+04    0.19760516E+01    0.63152856E+00
forrtl: severe (154): array index out of bounds
Image                                            PC                        Routine                         Line        Source
dftb+                            000000000043E3CB      for__signal_handl       Unknown  Unknown
libpthread-2.17.s       00002B073691C630      Unknown                     Unknown  Unknown
libmkl_avx512.so.      00002B0A34A171F8      mkl_blas_avx512_x    Unknown  Unknown
libmkl_gnu_thread    00002B072B2F52DE      mkl_blas_dcopy          Unknown  Unknown
libmkl_intel_lp64       00002B072A6DDA7F      dcopy_                         Unknown  Unknown
libmkl_scalapack_     00002B073A1C408A       pdsbrdb_                     Unknown  Unknown
libmkl_scalapack_     00002B0739FF3333        pdsyrdb_                     Unknown  Unknown
libmkl_scalapack_     00002B073A14BBAD      pdsyevr_                       Unknown  Unknown
libscalapackfx.so      00002B072A2B4164       scalapackfx_modul     Unknown  Unknown
libscalapackfx.so      00002B072A2B36E8       scalapackfx_modul     Unknown  Unknown
libdftbplus.so            00002B0727D46792       dftbp_dftbplus_ei       Unknown  Unknown
libdftbplus.so            00002B0727DADBE4      dftbp_dftbplus_ma     Unknown  Unknown
libdftbplus.so            00002B0727DA56BC      dftbp_dftbplus_ma     Unknown  Unknown
libdftbplus.so           00002B0727DA4FA6        dftbp_dftbplus_ma     Unknown  Unknown
libdftbplus.so           00002B0727D9E3B9        dftbp_dftbplus_ma     Unknown  Unknown
libdftbplus.so           00002B0727D92166        dftbp_dftbplus_ma     Unknown  Unknown
dftb+                          0000000000422F59         Unknown                      Unknown  Unknown
dftb+                          000000000041A822         Unknown                     Unknown  Unknown
libc-2.17.so               00002B0736B4B555         __libc_start_main        Unknown  Unknown
dftb+                         000000000041A729          Unknown                      Unknown  Unknown

Version of DFTB: Compiled from source.

**Expected behaviour**
Expected to complete the iSCC iteration

**Additional context**
Running on resources provided by Rescale.com and compiler flags can be provided if required.

**Comment by aradi** [comment]
Thanks for the report!  Could you provide me the system you run so that I can try to reproduce? You can send me that also directly (myGitHubUserName @ uni-bremen.de) if you do not want to upload it here.

**Comment by cfarm6** [comment]
Thank you. Changing the solver resolved the issue.
