### ISSUE TITLE
Tests fail when including TBLITE with intel compilers

### ISSUE THREAD

**Issue by Gareth-elliott** [dftbplus/dftbplus#1155]
**Describe the bug**

Hi dftbplus developers,

In addition to #1154 I came across this (compiler) bug also. Some of the unit tests fail when I try to build dftbplus with the tblite package included.

**To Reproduce**

This is on a Ubuntu AWS instance.
The oneAPI compilers (ifort, icx) are the following:
`ifort (IFORT) 2021.7.1 20221019`
`Intel(R) oneAPI DPC++/C++ Compiler 2022.2.1 (2022.2.1.20221020)`

The dftbplus source code was downloaded from the dftbplus website, version 21.2.

I initialise the build with:
`cmake .. -DWITH_TBLITE=True -DWITH_UNIT_TEST=True -DTEST_OMP_THREADS=4`

This configures fine (finds compilers, MKL) and builds fine.

Running the tests, however, causes some to fail (see below). The legacy tests fail with the RelWithDebInfo, as documented in #1154. It seems my issue is slightly different to #1127, as the build is successful, but the tests fail.

Let me know if you need anything else to help.

Thanks,

Gareth

**Additional context**

*Test Output*
```
94% tests passed, 16 tests failed out of 286

Total Test time (real) =  25.75 sec

The following tests FAILED:
	 38 - dftb+_xtb/gfn1_h2 (Failed)
	 39 - dftb+_xtb/gfn1_mindless01 (Failed)
	 40 - dftb+_xtb/gfn1_succinic (Failed)
	 41 - dftb+_xtb/ipea1_h2 (Failed)
	 42 - dftb+_xtb/ipea1_mindless02 (Failed)
	 43 - dftb+_xtb/gfn2_h2 (Failed)
	 44 - dftb+_xtb/gfn2_h2_restart (Failed)
	 45 - dftb+_xtb/gfn2_h2_Ascii (Failed)
	 46 - dftb+_xtb/gfn2_mindless05 (Failed)
	 47 - dftb+_xtb/gfn2_benzene (Failed)
	 48 - dftb+_spin/gfn2_H2 (Failed)
	 49 - dftb+_spin/gfn1_Fe4 (Failed)
	 50 - dftb+_spin/ipea1_Fe4_noncolinear (Failed)
	105 - dftb+_legacy/Si2_polyRep (Failed)
	145 - dftb+_scc/H2O-extfield-gfn1 (Failed)
	150 - dftb+_legacy/SiC_polyRep (Failed)
Errors while running CTest
```

Looking at some of the stderr.log files shows in all the cases I checked:
```
forrtl: severe (190): for allocate(source=), source needs to be allocated
Image              PC                Routine            Line        Source
dftb+              00000000005152B0  Unknown               Unknown  Unknown
dftb+              0000000000410D15  Unknown               Unknown  Unknown
dftb+              000000000040841D  Unknown               Unknown  Unknown
libc-2.31.so       00007FCD5D08E083  __libc_start_main     Unknown  Unknown
dftb+              000000000040833E  Unknown               Unknown  Unknown
Command exited with non-zero status 190
0.00user 0.01system 0:00.01elapsed 100%CPU (0avgtext+0avgdata 28388maxresident)k
0inputs+24outputs (48major+3320minor)pagefaults 0swaps
```

**Comment by Gareth-elliott** [comment]
cc @alisterpage

**Comment by aradi** [comment]
Thanks for reporting! I can reproduce it on my laptop. We did not catch this so far, as our regression tests run with `ifort (IFORT) 2021.5.0 20211109`, which produces perfectly running code.

My first guess would be a compiler bug, but I'd would have to check it. In the mean time, try to downgrade your Intel compiler, that should solve the issue.

**Comment by Gareth-elliott** [comment]
Thanks @aradi 👍

**Comment by aradi** [comment]
@Gareth-elliott  You're welcome. :smile:  However, I am not sure, whether we should merge this workaround, as it seems a to be a compiler bug. Especially, it does not seem to fix the `polyRep` testcases. :disappointed: , at least they still fail on my laptop (sometimes). If I can not reliably fix that within the next day or so, we will probably not merge this workaround, but drop the 2021.7 compiler from the list of supported compilers and will hope that Intel fixes that compiler bug. (I have reports from other packages about serious problems with that compiler...)

**Comment by aradi** [comment]
OK, there is a fair chance, that I've found the culprit for the remaining `polyRep` test cases, see #1156. So, we will probably merge the fix, which will close this issue automatically

Thanks for reporting it!
