### ISSUE TITLE
Conda build with tblite support in release 22.2

### ISSUE THREAD

**Issue by arosen93** [dftbplus/dftbplus#1163]
When installing DFTB+ 22.2 with conda via `conda install -c conda-forge dftbplus`, I get the following when I try to run an xTB calculation. What is the recommended way for building DFTB+ via Conda with tblite support?

I should note, everything works fine if I revert to `conda install -c conda-forge dftbplus==22.1`.

```
|===============================================================================
|
|  DFTB+ release 22.2
|
|  Copyright (C) 2006 - 2022  DFTB+ developers group
|
|===============================================================================
|
|  When publishing results obtained with DFTB+, please cite the following
|  reference:
|
|  * DFTB+, a software package for efficient approximate density functional
|    theory based atomistic simulations, J. Chem. Phys. 152, 124101 (2020).
|    [doi: 10.1063/1.5143190]
|
|  You should also cite additional publications crediting the parametrization
|  data you use. Please consult the documentation of the SK-files for the
|  references.
|
|===============================================================================

Reading input file 'dftb_in.hsd'
Parser version: 12

--------------------------------------------------------------------------------
ERROR!
-> DFTB+ compiled without support for tblite library
```

**Comment by aradi** [comment]
Unfortunately, the tblite stack on conda is currently broken (https://github.com/conda-forge/tblite-feedstock/pull/8), so that it is not possible to provide a DFTB+ build with xtb functionality (https://github.com/conda-forge/dftbplus-feedstock/pull/30). As soon as the tblite stack is fixed, I'll provide a new build with xTB functionality.

**Comment by aradi** [comment]
The tblite stack on conda had been fixed, and I've created a new DFTB+ build which includes the xTB functionality now. If you update your dftbplus package on Conda, you should obtain the new build.

**Comment by arosen93** [comment]
Fantastic. Thank you!!
