### ISSUE TITLE
DFTB+ error in recipes_DFTB+

### ISSUE THREAD

**Issue by danieleveclani** [dftbplus/dftbplus#1190]
Dear developers,

I’m a DFTB+ user and I tried to replicate the UV absorption calculation for a macromolecule from your recipes (recipes_DFTB+/linresp/macromolecule). However the calculation ends with an error here reported:
“ERROR!
-> Maximum number of iterations reached. Increase the number of excited states to solve for (NrOfExcitations).”

How can I solve this problem?

I'm using a DFTB+ software in 21.2 version.

Waiting for your reply.

Best regards,
Daniele Veclani.

**Comment by aradi** [comment]
Thanks for reporting. Could you try to run the example with the official Conda-binary? I've just downloaded the input from the recipes page and run it without experiencing any problems. My guess would be, that there is something wrong with the build you use.
