### ISSUE TITLE
Geometry Optimization SIGSEGV segmentation fault

### ISSUE THREAD

**Issue by m-a-saleh** [dftbplus/dftbplus#1201]
System Description:
---------------------------
Processor: Intel Core i7 13700k (8 cores x 2 threads)
Memory: 50 GB
OS: Ubuntu 22 LTS on Virtual Machine

Input file:
-----------
```
Geometry = VaspFormat {
<<< "POSCAR"
}

Driver = GeometryOptimization {
  Optimizer =  LBFGS { Memory = 20 }
  MovedAtoms = 1:-1
  MaxSteps = -1
  OutputPrefix = "geom.out"
  AppendGeometries = yes
  Convergence {GradAMax = 1E-4}
}

Hamiltonian = DFTB {
  Scc = Yes
    SlaterKosterFiles = Type2FileNames {
    Prefix = "../../skfs/"
    Separator = "-"
    Suffix = ".skf"
  }
  MaxAngularMomentum {  
    Si = "d"
    O  = "p"
    H  = "s"
  }
  KPointsAndWeights = SupercellFolding {
    1 0 0
    0 4 0
    0 0 1
    0.5 0.5 0.5
  }
}

Options {}

Analysis {
  CalculateForces = Yes
}

ParserOptions {
  ParserVersion = 12
}
```
The POSCAR geometry file contains a super cell with about 250 atom and uses. It is basically a Si slab with its surface passivated by SiO2 and H. It used the "siband" parameters.

Problem:
------------
I have downloaded the DFTB+ 22.2 precompiled executables for x86_64 (64 bit) architecture with Linux operating system.
I set the OMP_NUM_THREADS environment variable to 8.

When I run my calculation, I get the following error
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x58d051f in ???
#1  0x5cb121 in __dftbp_dftbplus_mainio_MOD_writedetailedout7
	at /mnt/scratch/aradi/gnu/dftb+/src/dftbp/dftbplus/mainio.f90:2804
#2  0x5b222c in __dftbp_dftbplus_main_MOD_rundftbplus
	at /mnt/scratch/aradi/gnu/dftb+/src/dftbp/dftbplus/main.f90:337
#3  0x4e6880 in dftbplus
	at /mnt/scratch/aradi/gnu/dftb+/app/dftb+/dftbplus.f90:33
#4  0x4b669c in main
	at /mnt/scratch/aradi/gnu/dftb+/app/dftb+/dftbplus.f90:10
Segmentation fault (core dumped)
```

I compiling from source (tried both OMP and MPI versions) using intel compilers and intel mpi V.2023. The program passed the tests using "ctest" and was able to complete the basic recipies. But when I use my system I again got the SIGSEGV error: 

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                            Routine                   Line        Source             
libc.so.6          00007F8969442520  Unknown                Unknown  Unknown
dftb+              00000000006093A2  Unknown                 Unknown  Unknown
dftb+              0000000000587B4E  Unknown                 Unknown  Unknown
dftb+              000000000040F7C3  Unknown                 Unknown  Unknown
dftb+              00000000004083DD  Unknown                 Unknown  Unknown
libc.so.6          00007F8969429D90  Unknown                 Unknown  Unknown
libc.so.6          00007F8969429E40  __libc_start_main      Unknown  Unknown
dftb+              00000000004082F5  Unknown                 Unknown  Unknown
```
I tried to increase the stack size via:
`ulimit -s unlimited`
but got the same error.

I tried simulating the un-optimized geometry and the run completed successfully.

**Comment by aradi** [comment]
Thanks for reporting. Could you upload your geometry, so that we can try to reproduce the issue?

**Comment by vanderhe** [comment]
Another possibly helpful remark: If I understand your description correctly you are attempting to perform a geometry optimization using the [siband](https://dftb.org/parameters/download/siband/siband-1-1-cc) parameters. As stated in their respective documentation those parameters only contain a dummy repulsive that is unsuitable for structural relaxation. While this should not cause a segfault per se, it will lead to unphysical geometries during relaxation and eventually an overlap that is not positive definite anymore, therefore by extend a Cholesky decomposition that fails.
