### ISSUE TITLE
Spin-Orbit coupling with Spin Polarization

### ISSUE THREAD

**Issue by anshugaur** [dftbplus/dftbplus#1204]
Dear all,
I am trying to do calculations with spin-orbit coupling and spin polarization (using spin constants) for carbon nanostructures. The calculation ends at the parsing stage without printing any error (given below). The calculation runs fine if I do not use spin polarization (only spin-orbit coupling).

I am using 3ob SK parameters (C-C.skf). I am attaching the input file. Is there something wrong with the input file of format for specifying spin polarizations?

Thanks in advance.
Anshu
---------------------------------------------------------------------------------------------------------------------------------
**Output:**
|===============================================================================
|
|  DFTB+ release 22.2
|
|  Copyright (C) 2006 - 2022  DFTB+ developers group
|
|===============================================================================
|
|  When publishing results obtained with DFTB+, please cite the following
|  reference:
|
|  * DFTB+, a software package for efficient approximate density functional
|    theory based atomistic simulations, J. Chem. Phys. 152, 124101 (2020).
|    [doi: 10.1063/1.5143190]
|
|  You should also cite additional publications crediting the parametrization
|  data you use. Please consult the documentation of the SK-files for the
|  references.
|
|===============================================================================

Reading input file 'dftb_in.hsd'
Parser version: 12

--------------------------------------------------------------------------------
Reading SK-files:
/home/anshu/Softwares/DFTBP18.2/slako/3ob/3ob-3-1/C-C.skf
Abort(1) on node 18 (rank 18 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 18
Abort(1) on node 9 (rank 9 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 1) - process 9

--------------------------------------------------------------------------------------------------------------------------------------------------------------

**Input file: dftb_in.hsd**

Geometry = GenFormat {
  <<< 'CNT85.gen'
}

Driver = {
}

Hamiltonian = DFTB {
  SCC = Yes
  ReadInitialCharges = No
  MaxAngularMomentum = {
    C = "p"
  }
  Filling = Fermi {
    Temperature [Kelvin] = 100.0
}
  SlaterKosterFiles = Type2FileNames {
    Prefix = "/home/anshu/Softwares/DFTBP18.2/slako/3ob/3ob-3-1/"
    Separator = "-"
    Suffix = ".skf"
  }

SCCTolerance = 1e-7
  KPointsAndWeights = SupercellFolding{
8   0   0
0   8   0
0   0   8  
0.5 0.5 0.5 
}

Dispersion = DftD3{
Damping = ZeroDamping {
  sr6 = 0.7461
  alpha6 = 14.0
}
  s6 = 1.0
  s8 = 3.209
}

SpinPolarisation = NonColinear {
SpinConstants = {
C = {
# Wss Wsp Wps Wpp
-0.031 -0.025 -0.025 -0.023
}
}
}

ShellResolvedSpin = Yes 

# Spin-Orbit Coupling

SpinOrbit = {
C [eV] = {0.0 0.012}  # 12 meV from Saito paper
}

ThirdOrderFull = Yes
HubbardDerivs {
C = -0.1492
}

}

Analysis {
ProjectStates {
Region {
Atoms = 1:172
ShellResolved = Yes
OrbitalResolved = No
Label = "pdos_CNT85"
}
}
CalculateForces = Yes
}

Parallel {
UseOmpThreads = Yes
Groups = 4
  Blacs {
    BlockSize = 32
}
}

**Comment by aradi** [comment]
Could you run first the same example serially (you can stop it immediately after the parsing)? Sometimes, the MPI-framework swallows the error message.

**Comment by anshugaur** [comment]
While running the example serially the following error is shown. The parser quits (no dftb_pin.hsd file). SpinConstants have been defined in the input file (previous message). I am not sure if they are correctly defined or not.
------------------------------------------------------------------------------------------------------------------
Reading SK-files:
/home/anshu/Softwares/DFTBP18.2/slako/3ob/3ob-3-1/C-C.skf
Done.
ERROR!
-> Missing child: SpinConstants
Path: dftbplusinput/Hamiltonian/DFTB
-----------------------------------------------------------------------------------------------------------------

Thanks and regards,
Anshu

**Comment by anshugaur** [comment]
I think, from the manual I am not able to understand the parent-child relation between SpinPlolarization and SpinConstants blocks of Hamiltonian.
Any clarification on this would be very welcome.
Regards,
Anshu

**Comment by aradi** [comment]
As the output says, the  ̇`SpinConstants` block must be within the `DFTB` block:
```
Hamiltonian = DFTB {
  ...
  SpinConstants {
    ...
   }
```
