### ISSUE TITLE
Examples for DFTB+U calculations

### ISSUE THREAD

**Issue by henhans** [dftbplus/dftbplus#1205]
Dear Developers,

I am new to DFTB+ and have reviewed the examples in DFTB+ recipes. It helps a lot in learning the capability of the method. 

Since I am in the field of correlated materials, I am also interested in the DFTB+U approach. However, I couldn't find an example for running DFTB+U calculations. There is an example in the folder dftbplus/test/app/dftb+/dftb+u, but it doesn't contain the prototypical correlated materials, e.g., NiO, MnO, etc.

Therefore, I would like to request an example for running DFTB+U calculations for strongly correlated materials like correlated transition metal oxides. It may benefit future users who want to work on correlated materials. Thank you!

**Comment by aradi** [comment]
Thanks, we are trying to extend the recipes as much as we can, but are of course limited by our other duties. Actually, while the tests might not use the materials you are interested in, the way how you have to specify the +U in DFTB+ is materials independent, so you should use the same keywords as in those examples.
