### ISSUE TITLE
DFTB+ as a MDI engine?

### ISSUE THREAD

**Issue by nesquik91** [dftbplus/dftbplus#1227]
**Is your feature request related to a problem? Please describe.**
Not a problem but just wonder since MDI library (https://molssi-mdi.github.io/MDI_Library/html/index.html) said DFTB+ can be used as an MDI "engine".

**Describe the solution you'd like**
Want to use DFB+ as an engine while suing LAMMPS as a driver. Is there any python MDI QM/MM wrapper code?

**Describe alternatives you've considered**
Or do you have any plan to do that?

**Additional context**
Thank you for the help.

**Comment by bhourahine** [comment]
@nesquik91 MDI can use their iPI flag, not sure what functionality changes this would lead to, but you will need a socket enabled build of DFTB+. We plan to look at adding the MDI bindings after the next release.
