### ISSUE TITLE
Failed to execute latest dftb+ installed using mamba 

### ISSUE THREAD

**Issue by tinidoooooooog** [dftbplus/dftbplus#1248]
Hi all,

I failed to run dftb+ installed from mamba whether in ubuntu 18.04 LTS in my Windows laptop or in ubuntu 22.04 LTS in my Windows PC. In both cases, ubuntu was installed using WSL 2.

**Here are the steps to reproduce the error:**

1. _Install miniconda 23.3.1_
2. _add conda-forge to conda_
 `conda config --add channels conda-forge`
4. _Create environment, install mamba, and install latest dftb+_
`conda create -n dftb && conda activate dftb && conda install -y mamba && mamba install 'dftbplus=*=mpi_*'`

5. _Run dftb+, and the following error messages are given_
`dftb+: symbol lookup error: /home/user/.conda/envs/dftb/bin/../lib/./libelsi.so: undefined symbol: __solverparametersmodule_MOD_solverparameters_init`

This error occurred in mpi version after 20.2.1. I really want to know how to fix this, thanks!

**Comment by aradi** [comment]
Can you please check, whether the `conda-forge` channel is the first one in the list of conda channels? Your `~/.condarc` file should look like
```
channels:
  - conda-forge
  - defaults
```
Otherwise, you might get the wrong dependencies.

**Comment by tinidoooooooog** [comment]
> Can you please check, whether the `conda-forge` channel is the first one in the list of conda channels? Your `~/.condarc` file should look like
> 
> ```
> channels:
>   - conda-forge
>   - defaults
> ```
> 
> Otherwise, you might get the wrong dependencies.

My .condarc looks like
`channels:
  - conda-forge
  - defaults
`

Here are the packages to be installed by mamba
`  Package                  Version  Build                   Channel                   Size
────────────────────────────────────────────────────────────────────────────────────────────
  Install:
────────────────────────────────────────────────────────────────────────────────────────────

  + chimes-calculator        1.0.2  h0c14de7_0              conda-forge/linux-64     190kB
  + dftbplus                  22.2  mpi_openmpi_h573552d_1  conda-forge/linux-64      18MB
  + dftd4                    3.5.0  h03160e7_0              conda-forge/linux-64     596kB
  + elpa               2021.11.001  mpi_openmpi_haf9840c_3  conda-forge/linux-64       6MB
  + elsi                     2.8.2  mpi_openmpi_hbbb7b4b_2  conda-forge/linux-64     952kB
  + fftw                    3.3.10  nompi_hc118613_107      conda-forge/linux-64       2MB
  + gawk                     5.1.0  h7f98852_0              conda-forge/linux-64       1MB
  + gsl                        2.7  he838d99_0              conda-forge/linux-64       3MB
  + libblas                  3.9.0  16_linux64_openblas     conda-forge/linux-64      13kB
  + libcblas                 3.9.0  16_linux64_openblas     conda-forge/linux-64      13kB
  + libgfortran-ng          12.2.0  h69a702a_19             conda-forge/linux-64      23kB
  + libgfortran5            12.2.0  h337968e_19             conda-forge/linux-64       2MB
  + liblapack                3.9.0  16_linux64_openblas     conda-forge/linux-64      13kB
  + libmbd                  0.12.5  mpi_openmpi_h4fb355c_0  conda-forge/linux-64     854kB
  + libnegf                  1.1.2  mpi_openmpi_h67de57e_0  conda-forge/linux-64     691kB
  + libomm                   1.0.0  mpi_openmpi_hbbb7b4b_2  conda-forge/linux-64     164kB
  + libopenblas             0.3.21  pthreads_h78a6416_3     conda-forge/linux-64      11MB
  + matrixswitch             1.0.0  mpi_openmpi_hbbb7b4b_2  conda-forge/linux-64     321kB
  + mctc-lib                 0.3.1  h74f4db8_0              conda-forge/linux-64     461kB
  + mpi                        1.0  openmpi                 conda-forge/linux-64       4kB
  + mpifx                    1.3.1  mpi_openmpi_h82bc248_0  conda-forge/linux-64       1MB
  + ntpoly                   3.0.0  mpi_openmpi_ha0c50f8_0  conda-forge/linux-64     761kB
  + openmpi                  4.1.5  h414af15_101            conda-forge/linux-64       4MB
  + plumed                   2.8.2  mpi_openmpi_hb0545ae_0  conda-forge/linux-64       3MB
  + scalapack                2.2.0  h67de57e_1              conda-forge/linux-64       2MB
  + scalapackfx                1.1  mpi_openmpi_h7636f6f_0  conda-forge/linux-64     425kB
  + simple-dftd3             0.7.0  heafb486_2              conda-forge/linux-64     710kB
  + tblite                   0.3.0  h03160e7_0              conda-forge/linux-64       4MB
  + toml-f                   0.3.1  h74f4db8_0              conda-forge/linux-64     583kB
  + zlib                    1.2.13  h166bdaf_4              conda-forge/linux-64      94kB
`

Can you please check if these are the same as your case? Thanks!

**Comment by aradi** [comment]
I've just tested, I get the same error message as you (and the same components). Apparently, the ELSI package is broken on Conda. I'll try to investigate it more in detail.

**Comment by tinidoooooooog** [comment]
> 

Thank you for the quick reply@aradi! I will try build dftb+ myself using latest Intel meanwhile.

**Comment by aradi** [comment]
OK, it has been fixed now. The latest build of 22.2 on Conda should work without any problems.

**Comment by tinidoooooooog** [comment]
@aradi I will perform the test in the coming days. If it proves successful, I will close this issue. Thank you!
