### ISSUE TITLE
Alternative to installing `mamba` - using the `mamba` solver with `conda`

### ISSUE THREAD

**Issue by JacksonBurns** [dftbplus/dftbplus#1252]
**Is your feature request related to a problem? Please describe.**
README instructs users to install `mamba` in the base environment with `conda`, and from there on out uses `mamba` commands. This is done to resolve issues with solving the environment with default `conda`.

**Describe the solution you'd like**
We ran into similar issues over on RMG-Py, and resolved them in [this issue](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2384). We ultimately ended up having our users install the `conda-libmamba-solver` instead of actually switching to `mamba` (which still speeds up/fixes environment solving), as described in [this Anaconda blogpost](https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community). We found this to be slightly easier for our users and for us, since `conda` 'googles' better than `mamba` and we were all accustomed to writing docs referencing `conda`. 

**Describe alternatives you've considered**
Feel free to disregard and close this suggestion, as the current strategy works perfectly fine. Just wanted to make sure everyone knows about this option!

**Comment by vanderhe** [comment]
Hi @JacksonBurns,

thanks a lot for the kind suggestion, I've already (hopefully correctly) adopted it for our parametrization suite SkProgs (see PR [#64](https://github.com/dftbplus/skprogs/pull/64)) and will put it on the agenda to discuss it for the main repo as well.

Best regards
Tammo
