### ISSUE TITLE
Memory leak when iterating in DFTB+

### ISSUE THREAD

**Issue by Pibemanden** [dftbplus/dftbplus#1266]
**Describe the bug**
I have now tried installing DFTB+ from the current developement version and a number of different compiler, lapack libraries, machines, and DFTB+ complation flags.
So far I have found in all cases that running the GeometryOptimization for several iterations leads to a growing memory consumption.
This does however not cause a crash since it is only some hundreds of kB every cycle, 
but I am intending to use the library function of DFTB+, and it is therefore important that the program doesn't slowly accumulate memory as it will crash a calculation running for more than 1000 DFTB+ steps.

**To Reproduce**
I have tried many different setups so currently I have verified it to be the case for:

MKL 2018.3, 2023.1.0, Lapack.
gfortran 9, 11, and 12.
Turning on an off thread support in DFTB didn't change anything either.
Turning on and off the D3 dispersion library and inputs didn't change anything either.

**Expected behaviour**
The memory consumption remains flat over the run.

**Additional context**
I have also tried running the code through Valgrind, but there are no obvious unreachable memory that were growing even after running with more and more steps in the calculation.

**Comment by Pibemanden** [comment]
After searching through libraries and finally picking up a memory debugger I think I have found the issue, but since I am no expert in the code I have edited to make this work I will have to rely on one of the main developers to tell me if this is correct.

In the subroutine ` fillNeighbourArrays(neigh, iNeighbour, neighDist2, startAtom, endAtom, maxNeighbour, nAtom, isParallel)` in the `src/dftbp/dftb/periodic.F90` file we have the following lines:

https://github.com/dftbplus/dftbplus/blob/f13480e32f5edbf8ca1fd195fd89b336ba8252d5/src/dftbp/dftb/periodic.F90#L900-L913

I believe that either the deallocation of the arrays use the wrong names, or at the very least that we need to deallocate the `neigh%iNeighbour` and `neigh%neighDist2` arrays. If I add some code to deallocate the arrays if they are allocated I seem to have removed the memory leak, and can not run the code for more than 1000 iterations with near constant memory use.

**Comment by KStrutynski** [comment]
Hello,
I think that I saw similar behaviour with Socket Driver, when I used DFTB+ in ASE. The system with 960 atoms used up 230 Gb of assigned ram with only 265 geometry steps.

**Comment by bhourahine** [comment]
@Pibemanden I've also confirmed the memory leak. As you say, it looks like the wrong pointers being tested and attached memory deallocated.

**Comment by Pibemanden** [comment]
@bhourahine @KStrutynski Thank you both for confirming the issue.

And thank you @bhourahine for making the pull request to fix the issue.
