### ISSUE TITLE
The test dftb+_dispersion/specieslist_dftd4 doesn't finish in 90 miutes

### ISSUE THREAD

**Issue by yurivict** [dftbplus/dftbplus#1278]
**Describe the bug**
See subject.

**To Reproduce**
Regular tests run. 

63 tests succeeded before this one, then this tests hanged.

Version: 23.1
FreeBSD 13.2

**Comment by vanderhe** [comment]
Dear @yurivict,

thanks for reporting the issue. I'm not familiar with FreeBSD, could you provide some additional information, i.e. build configuration, compiler (+ version), etc. for us to reproduce the behavior?

Best regards
Tammo
