### ISSUE TITLE
Issue in calling dftb+ "in get_fermi_level     return max(self.get_fermi_levels())

### ISSUE THREAD

**Issue by RameshwarKumawat** [dftbplus/dftbplus#1298]
Hi, 
I am trying to plot the band structure of Si bulk. I have written a Python script to call dftb+ to calculate the band structure but it is failing to compute. I got the following error: 

File "/home/ram/.local/lib/python3.8/site-packages/ase/calculators/dftb.py", line 477, in get_fermi_levels     return self.results['fermi_levels'].copy() KeyError: 'fermi_levels'

Thank you!
Ram

**Comment by vanderhe** [comment]
Hi @RameshwarKumawat,

my first guess would be that you performed a two-step calculation composed of 1) the self-consistent density calculation with a "good" k-point sampling of the BZ and 2) diagonalizing the Hamiltonian at k-lines between high-symmetry points with fixed density/charges. In the second step the calculation usually does not converge and (if requested) DFTB+ defaults to writing an empty results.tag file in these cases, resulting in the ASE calculator not being able to return anything. You should probably use the Fermi level that comes out of step 1) anyway.

I hope this is of use to you, feel free to report back if you could solve the issue.

Best regards
Tammo
