### ISSUE TITLE
Invalid Hamiltonian xTB

### ISSUE THREAD

**Issue by AntonioCd96** [dftbplus/dftbplus#1315]
**Describe the bug**
I'm trying to obtain the Raman and the IR spectra using dftb+, specifically, xTB methods . When I run the program I obtain:
 **ERROR!
-> Invalid Hamiltonian
Path: dftbplusinput/Hamiltonian/xTB
Line: 5-13 (File: dftb_in.hsd)**

**To Reproduce**
This is my code:
`Geometry = vaspFormat {
<<< "POSCAR"
}

Hamiltonian = xTB {
  Method = "GFN1-xTB"
  KPointsAndWeights = SupercellFolding {
    4 0 0
    0 4 0
    0 0 4
    0.5 0.5 0.5
  }
}

Analysis {
  ProjectStates {
    Region {
      Atoms = Ti
      ShellResolved = Yes
      Label = "dos_ti"
    }
    Region {
      Atoms = O
      ShellResolved = Yes
      Label = "dos_o"
     }
  }
}

ParserOptions {
  ParserVersion = 8
}
`

All input and output files required to confirm your report. -->

**Expected behaviour**
I expect that it works as when a use xtb for discrete molecules
**Additional context**
I execute the program in wsl using dftb+ dftb_in.hsd
I also have this problem when I try to run the recipes, which makes me think that it's related to the installation in my machine

**Comment by awvwgk** [comment]
Could you share the version of dftb+ you are using?

**Comment by AntonioCd96** [comment]
Thanks for the answer.
I think it is:   DFTB+ development version (commit: 85675ff)
I'm trying to use the terminal as dftb+ -version but it doesn't work. However if it works, I installed dftb+ as: conda install 'dftbplus=*=nompi_*'
So I would assume it's the latest one

Thanks

**Comment by AntonioCd96** [comment]
Hi, there! Any suggestion? Thaaanks

**Comment by AntonioCd96** [comment]
Hi, there! Any suggestion? Thaaanks

**Comment by aradi** [comment]
I am somewhat puzzled about the problem. I've tried following input (which is yours, just with some geometry information added):
```
Geometry = GenFormat {
    6  F
 Ti  O
    1 1    0.4393045491E-02   -0.4394122690E-02   -0.4185505032E-06
    2 1   -0.2456050838E+00   -0.7543932244E+00    0.5000007729E+00
    3 2    0.1997217007E+00    0.2106836749E+00   -0.1813953963E-02
    4 2   -0.4625010039E+00    0.4843137675E-01    0.4981557672E+00
    5 2   -0.2106822274E+00   -0.1997223911E+00    0.1816384188E-02
    6 2   -0.4843281768E-01   -0.5374990457E+00    0.5018414482E+00
    0.0000000000E+00    0.0000000000E+00    0.0000000000E+00
   -0.1903471721E+01    0.1903471721E+01    0.4864738245E+01
    0.1903471721E+01   -0.1903471721E+01    0.4864738245E+01
    0.1903471721E+01    0.1903471721E+01   -0.4864738245E+01
}

Hamiltonian = xTB {
  Method = "GFN1-xTB"
  KPointsAndWeights = SupercellFolding {
    4 0 0
    0 4 0
    0 0 4
    0.5 0.5 0.5
  }
}

Analysis {
  ProjectStates {
    Region {
      Atoms = Ti
      ShellResolved = Yes
      Label = "dos_ti"
    }
    Region {
      Atoms = O
      ShellResolved = Yes
      Label = "dos_o"
    }
  }
}

ParserOptions {
  ParserVersion = 8
}
```
It runs without any problems using DFTB+ 23.1 (from Conda). Please test, whether this input works for you. If not, then probably you are using a different  (much older) version of DFTB+ as you think. (The version number should be printed in the header at start...)

**Comment by AntonioCd96** [comment]
Thanks for the support! 
This is the header:

|  DFTB+ development version (commit: 85675ff)
|
|  Copyright (C) 2006 - 2020  DFTB+ developers group


I'm gonna try to update it and see if it works.
Thanks
