### ISSUE TITLE
Can't install dftbplus for Apple Silicon macs!!!!

### ISSUE THREAD

**Issue by alejandroarche** [dftbplus/dftbplus#1318]
**Describe the bug**

**To Reproduce**

**Expected behaviour**

**Additional context**

**Comment by bhourahine** [comment]
You'll need to give a bit more information. Are you building from source, or looking for conda packaging? What errors are you getting?

**Comment by aradi** [comment]
Closing as no information was provided. @alejandroarche: Feel free to reopen it if you are able/willing to provide any details.
