### ISSUE TITLE
Range separated input can not handle None {}

### ISSUE THREAD

**Issue by aradi** [dftbplus/dftbplus#1331]
**Describe the bug**
Setting
```
RangeSeparated = None {}
```
in the `Hamiltonian` block triggers

* an error message about non-rs SK-files, when used with conventional SK-files
* an error message about unknown rs-functional "none", when used with rs-SK-files (which should not be done).

**To Reproduce**

Take any example and set `RangeSeparated = None {}`.

**Expected behaviour**

Code should accept it.

**Additional context**

This worked in 22.2 and was broken in 23.1, when the check about the SK-files was introduced. Unfortunately, as 22.2 created `RangeSeparated = None {}` in the input, this prevents users to use `dftb_pin.hsd` of earlier runs as input.

**Comment by vanderhe** [comment]
@aradi As far as I can see, the erroneous behavior has been fixed by #1223, but we might have to think about reproducibility.
