### ISSUE TITLE
Faster alternative to matrix diagonalization for GPU acceleration

### ISSUE THREAD

**Issue by Lactoria-cornuta** [dftbplus/dftbplus#1333]
Dear developers!

Recently I came across the paper (https://doi.org/10.1063/5.0164255) describing the method for density matrix calculation which is faster than conventional matrix diagonalization when using GPU acceleration. I think adding this method to the codebase may greatly benefit the users (the authors of the paper themeselves suggest doing it).

**Comment by bhourahine** [comment]
We are exploring options for this to be added at the moment.

**Comment by Lactoria-cornuta** [comment]
This is great news!
