### ISSUE TITLE
Python: "Cannot call MPI_INIT or MPI_INIT_THREAD more than once"

### ISSUE THREAD

**Issue by njzjz** [dftbplus/dftbplus#1351]
**Describe the bug**

Got `Cannot call MPI_INIT or MPI_INIT_THREAD more than once` error when calling `dftbplus.DftbPlus()` twice. The first one has been closed by `cdftb.close()`.

In my situation, I need to adjust the input file, so I must initialize DFTB+ twice.

**To Reproduce**

```py
import dftbplus
cdftb = dftbplus.DftbPlus()
cdftb.close()
cdftb = dftbplus.DftbPlus()
```

**Expected behaviour**

No error.

**Additional context**

The DFTB+ is installed from conda-forge.

**Comment by njzjz** [comment]
The `nompi` version from conda-forge doesn't have this problem.

**Comment by aradi** [comment]
@njzjz Thanks for reporting. The Python API should only use serial binary as there is currently no way to pass MPI-handlers through the Python bindings.
