### ISSUE TITLE
Output of MD runs

### ISSUE THREAD

**Issue by blowfist** [dftbplus/dftbplus#1378]
For MD runs, the output files like band.out or detailed.out will store only the latest step of the runs and the previous step will be covered. So when the runs finish, only the information of the last step is present. However, I want output files to store information of all steps. Is there an option to switch that?

**Comment by vanderhe** [comment]
Hi @blowfist,

that is right, not all quantities are stored for all steps. The most important ones are accumulated in md.out, including e.g. structural information (together with geo_end.xyz), the temperature, pressure, total energy and so on. May I ask which additional quantities are required for your application?

Best regards
Tammo

**Comment by blowfist** [comment]
Problem solved. I change writing mode in mainio.F90 and it seems to work properly. Thank you for your reply.

**Comment by bhourahine** [comment]
@blowfist would you consider making a pull request for this change?

**Comment by blowfist** [comment]
@bhourahine  I changed only the output of band.out and left detailed.out alone. I didn't read the part of detailed.out in main.F90 and mainio.F90 carefully. So maybe this modification is not suitable for general MD runs. Do you expect to append both of these files in MD runs?

**Comment by bhourahine** [comment]
The main code now has the capability to accumulate the band structure.
