### ISSUE TITLE
Documentation: The recipes guide is using the outdated `GradAMax` keyword

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [dftbplus/dftbplus#1379]
As I noted in https://github.com/dftbplus/dftbplus/issues/969#issuecomment-1918254558, the ["first calculation" section of the DFTB+ recipe guide](https://dftbplus-recipes.readthedocs.io/en/latest/basics/firstcalc.html) is using the `GradAMax` variable name, which should instead be `GradElem` now.

**Comment by vanderhe** [comment]
Hi @Andrew-S-Rosen,

thanks for reporting the inconsistency, I've created a [PR](https://github.com/dftbplus/recipes/pull/60) in the recipes repo that should resolve the issue. While playing around with the convergence keywords it occurred to me that apparently any additional (unprocessed) keyword is quietly accepted by the parser and propagated into the `dftb_pin.hsd` file. I think that's another bug but need to spend some more time to confirm and possibly fix.

Best regards
Tammo

**Comment by Andrew-S-Rosen** [comment]
Thank you! Yes, I can confirm that as well.

**Comment by bhourahine** [comment]
It looks like the behaviour manifests if there are no valid keywords in the  Convergence{} block. Putting a warnUnprocessedNodes() call into readOptTolerance also shows there are no unprocessed keywords in the junk case, suggesting it's either in the parser, or something wrong with the node passed into that code section.

**Comment by bhourahine** [comment]
PR #1384 removes this behaviour.
