### ISSUE TITLE
Reconciling differences in ASE vs. DFTB+ internal relaxations

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [dftbplus/dftbplus#1380]
## Disclaimer

Hello DFTB+ developers! First of all, I recognize that this is not a true bug report (or feature request), so certainly feel free to close this. That said, if you happen to have any suggestions about where I might be missing something, I'm all ears.

## The Issue

I am getting fairly noticeable differences in the converged lattice parameters when carrying out a geometry optimization using DFTB+'s internal routines when compared to those obtained using ASE to carry out the relaxation, and I am at a loss about the source of the discrepancy. 

### Problem Setup

I've chosen to do the following to try and locate the source of the discrepancy

1. A TBLite/ASE relaxation with GFN1-xTB.
2. A DFTB+/ASE relaxation with GFN1-xTB.
3. A DFTB+ only relaxation with GFN1-xTB.

### Sample Results

The results for a sample material (attached below) are as follows. As we can see here, TBLite and DFTB+ are giving the same results when optimized via the same ASE routine, which was a reassuring sanity check. It seems the difference is solely due to the cell relaxation routine between that in DFTB+ and ASE.

| Method | a (Å) | b (Å) | c (Å) |
|--------|--------|--------|--------|
| TBLite/ASE | 18.11521837| 18.11521837| 18.11521837|
| DFTB+/ASE | 18.11520707| 18.11520707| 18.11520707|
| DFTB+ | 18.19500848| 18.19502726| 18.1949668|

### Sample Code

Here's sample code using DFTB+ 23.1 installed via `conda`, TBLite 0.3.0 installed via pip, the `master` branch of ASE, and Python 3.11 on an Ubuntu machine:

```python
from tblite.ase import TBLite
from ase.calculators.dftb import Dftb
from ase.optimize import BFGS
from ase.filters import FrechetCellFilter
from ase.io import read

# -------------- Method 1 --------------
atoms1 = read("POSCAR.txt")
atoms1.calc = TBLite(method="GFN1-xTB")
dyn1 = BFGS(FrechetCellFilter(atoms1))
dyn1.run(fmax=0.01)
print(atoms1.cell.lengths())

# -------------- Method 2 --------------
atoms2 = read("POSCAR.txt")
atoms2.calc = Dftb(Hamiltonian_="xTB", Hamiltonian_Method="GFN1-xTB", kpts=(1,1,1))
dyn2 = BFGS(FrechetCellFilter(atoms2))
dyn2.run(fmax=0.01)
print(atoms2.cell.lengths())

# -------------- Method 3 --------------
atoms3 = read("POSCAR.txt")
atoms3.calc = Dftb(
    Hamiltonian_="xTB",
    Hamiltonian_Method="GFN1-xTB",
    kpts=(1, 1, 1),
    Driver_="GeometryOptimization",
    Driver_AppendGeometries="Yes",
    Driver_LatticeOpt="Yes",
    Driver_Convergence="{ GradElem [eV/AA] = 0.01 }",
    Driver_Optimizer="LBFGS {}",
)
atoms3.get_potential_energy()
atoms3 = read("geo_end.gen")
print(atoms3.cell.lengths())
```
[POSCAR.txt](https://github.com/dftbplus/dftbplus/files/14107659/POSCAR.txt)

### Question

Do you happen to have any thoughts for why there would be such a difference? Are there any parameters in Method 3 (DFTB+'s internal procedure) that I should consider modifying to further evaluate any potential differences?

I did try using LBFGS as the optimizer in all three scenarios and received basically the same results, so I don't think it has to do with the optimizer choice. I also tried using ASE's `ExpCellFilter` instead of the newer `FrechetCellFilter` to confirm that didn't play a role.

**Comment by bhourahine** [comment]
One idea is that 1&2 could be getting a slightly different eV/AA -> Hartree/Bohr conversion factor (internal to ASE or DFTB+) than 3. Also, depending on how rigid the material is, a 0.01 eV/AA tolerance might be quite loose, and the run could halt at different iterations even with the same optimizer algorithm.

Does the difference decrease for a tighter tolerance and also how different are the final energies?

**Comment by Andrew-S-Rosen** [comment]
@bhourahine --- thanks for taking the time to reply! I definitely should have thought of that. I don't usually find 0.01 eV/A to be a problem, but you were right. I tried tightening the force tolerance to 0.001 eV/A in the third run (i.e. pure DFTB+) and then I received the same answer as Run 1 and Run 2 using ASE as the wrapper. It seems like the slight implementation difference simply caused the DFTB+ run to finish the optimization earlier than Run 1 and Run 2, when in reality, it wasn't as close to the local minimum in the PES.

Much appreciated, even though this was clearly beyond your role as a maintainer!
