### ISSUE TITLE
web site down

### ISSUE THREAD

**Issue by ltalirz** [dftbplus/dftbplus#1381]
The web site https://dftbplus.org seems to be down

<img width="269" alt="image" src="https://github.com/dftbplus/dftbplus/assets/1053245/04e35b0a-5725-4936-b815-5642559fb63e">

**Comment by aradi** [comment]
Thanks for the report! I can reach the site from our university network, but not from outside, indeed. I'll try to find out what happened and fix it.

**Comment by aradi** [comment]
It was due to a wrong firewall config. Now, it should work. Thx for reporting, feel free to reopen, if you still experience problems.

**Comment by ltalirz** [comment]
Cheers, thanks for fixing!
