### ISSUE TITLE
parser change

### ISSUE THREAD

**Issue by banbi0615** [dftbplus/dftbplus#1454]
**I use dftb_in.hsd as follows:**
Geometry = GenFormat {

    6  S
 Ti  O
    1 1    0.0000000000E+00  0.0000000000E+00  0.0000000000E+00
    2 1    0.0000000000E+00  0.0000000000E+00  0.0000000000E+00
    3 2    0.0000000000E+00  0.0000000000E+00  0.0000000000E+00
    4 2    0.0000000000E+00  0.0000000000E+00  0.0000000000E+00
    5 2    0.0000000000E+00  0.0000000000E+00  0.0000000000E+00
    6 2    0.0000000000E+00  0.0000000000E+00  0.0000000000E+00
    0.0000000000E+00    0.0000000000E+00    0.0000000000E+00
    1.0000000000E+02    0.0000000000E+00    0.0000000000E+00
    0.0000000000E+00    1.0000000000E+02    0.0000000000E+00
    0.0000000000E+00    0.0000000000E+00    1.0000000000E+02

}

Hamiltonian = DFTB {

  Scc = Yes
  MaxSccIterations = 100
  SccTolerance = 1.00e-05

  SlaterKosterFiles = Type2FileNames {
    Prefix = "/root/electrondensity2-master/bin/dataset/recipes/slakos/mio-ext/"
    Separator = "-"
    Suffix = ".skf"
  }

  MaxAngularMomentum {
    Ti = "d"
    O  = "p"
  }

  KPointsAndWeights = SupercellFolding {
    4   0   0
    0   4   0
    0   0   4
    0.5 0.5 0.5
  }

}

Analysis {
  PrintForces = Yes
}

Options {
  TotalChargeDensity = Yes           # Total density be plotted?
  TotalChargeDifference = Yes        # Total density difference plotted?
  ChargeDensity = Yes                # Charge density for each state?
  NrOfPoints = 50 50 50              # Number of grid points in each direction
  NrOfCachedGrids = -1               # Nr of cached grids (speeds up things)
  Verbose = Yes                      # Wanna see a lot of messages?
}

ParserOptions {
  ParserVersion = 12
}

**and it shows bugs which says:**
WARNING!
-> The following 6 node(s) have been ignored by the parser:
(1)
Path: dftbplusinput/Options/TotalChargeDensity
Line: 49-49 (File: /root/electrondensity2-master/bin/dataset/dftb_in.hsd)
(2)
Path: dftbplusinput/Options/TotalChargeDifference
Line: 50-50 (File: /root/electrondensity2-master/bin/dataset/dftb_in.hsd)
(3)
Path: dftbplusinput/Options/ChargeDensity
Line: 51-51 (File: /root/electrondensity2-master/bin/dataset/dftb_in.hsd)
(4)
Path: dftbplusinput/Options/NrOfPoints
Line: 52-52 (File: /root/electrondensity2-master/bin/dataset/dftb_in.hsd)
(5)
Path: dftbplusinput/Options/NrOfCachedGrids
Line: 53-53 (File: /root/electrondensity2-master/bin/dataset/dftb_in.hsd)
(6)
Path: dftbplusinput/Options/Verbose
Line: 54-54 (File: /root/electrondensity2-master/bin/dataset/dftb_in.hsd)
I copied these 6 command from official website:https://dftbplus-recipes.readthedocs.io/en/latest/basics/waveplot.html, but it seems like the keyword is not supported in the new version of DFTB+ due to different versions of parser. May I ask how to realize the grid division of electron density and cube file output in the latest 24.1 version of dftbplus

**Comment by aradi** [comment]
You can not put the input for waveplot in the DFTB+ input file. As written in the recipes, you need to put it into a separate file `waveplot_in.hsd`.
