### ISSUE TITLE
WITH_SOCKETS = 0 is not compiling

### ISSUE THREAD

**Issue by zerothi** [dftbplus/dftbplus#148]
Multiple errors in the `parser.F90` will not compile due to missing pre-processor statements. (the `control` type has `socketInput` as a preprocessed member.

**Comment by bhourahine** [comment]
Is this for the current master code, or the 18.1 release ( see commit 49a564c )?

**Comment by zerothi** [comment]
It was for 18.1. Sorry for not writing the version.
