### ISSUE TITLE
Please replace WITH_xx:=xx with WITH_xx?=xx

### ISSUE THREAD

**Issue by yurivict** [dftbplus/dftbplus#170]
This will allow users to change thee values in environment variables or make arguments.

Here https://github.com/dftbplus/dftbplus/blob/master/make.config#L16 and at other similar places.

**Comment by aradi** [comment]
But that works also this way: `make DEBUG=2` would override the `DEBUG` variable. I am not sure, whether that honors environment variables, but to be honest, for the sake of reproducibility, I would be even more happy, if it won't. This assumes of course GNU make, but that's a prerequisite for building DFTB+ anyway.

**Comment by yurivict** [comment]
When you assign the variable with ```:=```, this is non-overridable. I had to patch these so that they can be overridden. This is a small thing anyway, I can just keep patching them.

**Comment by aradi** [comment]
You can patch it if you like, but the statement above about overriding is not correct. According to [GNU make documentation](https://www.gnu.org/software/make/manual/html_node/Overriding.html):

> When you override a variable with a command line argument, you can define either a recursively-expanded variable or a simply-expanded variable. The examples shown above make a recursively-expanded variable; to make a simply-expanded variable, write ‘:=’ or ‘::=’ instead of ‘=’. But, unless you want to include a variable reference or function call in the value that you specify, it makes no difference which kind of variable you create. 

So, by passing the appropriate variable at the command line, like
```make WITH_MPI=1```
would override, whatever value `WITH_MPI` is assigned in `make.config`.

This may not apply for overriding by an environment variable, but I for sure would like to keep the build system as much as possible independent of some forgotten environment variables the user is not even aware of...

**Comment by yurivict** [comment]
You are right, thanks!
