### ISSUE TITLE
dp_dos can't hande projected states output for cluster

### ISSUE THREAD

**Issue by aradi** [dftbplus/dftbplus#179]
Either k-point and spin has to be added to file header of dp_dos modified to handle those missing fields.

**Comment by aageo25** [comment]
Yes. I cannot use dp_dos/dp_bands in my cluster models because of that. It would be great if dp_dos/dp_bands could handle that.

Thank you very much!

**Comment by dryndyk** [comment]
Simply change
write(fd(iReg), "(A,1X,I0)") 'SPIN', iS
to
write(fd(iReg), "(2(A,1X,I0,1X),A,1X,F12.8)") 'KPT', 1, 'SPIN', iS, 'KWEIGHT', 1.0
in 
subroutine writeProjEigvecHeader(fd, iS, iK, kWeight)
?
