### ISSUE TITLE
(dftb plus-18.2) continuously growing memory usages with MPI ? 

### ISSUE THREAD

**Issue by suntaho** [dftbplus/dftbplus#183]
Dear 
Using dftb-plus-18.2 in Ubuntu 18.04 (intel compiler+mkl, 2019),
the program requests more and more memory as processing iterative Driver function.
Can anyone give suggestion to deal this issue?

============== .hsd setup ==============
Geometry = GenFormat {
     #<<<"geo_end.gen"
     <<<"geometry.gen"
}
Driver = VelocityVerlet {
  TimeStep [Femtosecond] = 1.0
  MovedAtoms = H C S
  Thermostat = Berendsen {
    CouplingStrength = 0.1
    AdaptFillingTemp = Yes
    Temperature [Kelvin] = TemperatureProfile {
        constant     500  300.0
        linear       500  500.0
        exponential  1000  300.0    
        constant     500  300.0
    }
  }
  MDRestartFrequency = 10
}	       			

Hamiltonian = DFTB {
  SCC = Yes
  SCCTolerance = 1e-5
  MaxSCCIterations = 500
  SlaterKosterFiles = Type2FileNames {
    Prefix = "//home/sunta/bin/dftbplus-18.2/slakos/auorg-1-1/"
    Separator = "-"
    Suffix = ".skf"
  }
  MaxAngularMomentum {
    H  = "s"
    C  = "p"
    S  = "p"
    Au = "d"
  }
  KPointsAndWeights = SupercellFolding {
    1  0  0
    0  1  0
    0  0  1
    0.0 0.0 0.0
  }
  InitialCharges = {
    AtomCharge = {
      Atoms = S
      ChargePerAtom = 0.0
    }
  }
  Eigensolver = DivideAndConquer{}
  Mixer = Anderson{
    MixingParameter = 0.05
    Generations = 6
  }
}
Parallel{
  Groups = 1
  UseOmpThreads = No
}
Analysis={
  MullikenAnalysis = Yes
}
ParserOptions {
  ParserVersion = 6
}

**Comment by aradi** [comment]
That's odd. Can you send me your geometry by mail, so that I can test it on my machine?

**Comment by suntaho** [comment]
Dear Professor Bálint Aradi

As your mentions, relevant documents are added in attachments.
Did i miss anything setup for dftb+ operations?

Sorry if this brings any bother to you.

best regards
I-Lin Ho

Bálint Aradi <notifications@github.com> 於 2018年10月24日 週三 下午3:09寫道：

**Comment by aradi** [comment]
Can you send me that to my [proper university Bremen mail](https://www.bccms.uni-bremen.de/cms/people/b-aradi/) address? Attachment won't come through via github. Also make sure, you include the geometry file as well.
