### ISSUE TITLE
Sever problems with MPI version of dftb+ 18.2

### ISSUE THREAD

**Issue by Dselli** [dftbplus/dftbplus#228]
I do have a particular problem which I hope can be solved.

I am using the last MPI version of dftb+ 18.2 (downloaded the 12/03/2019), compiled with the intel2017 package (ifort, impi, mkl). I am also using the dftd3 module.

My simulation consists of a series of single point calculations on slightly different geometries. To speed up it, I would like to read at the N step the charges.bin file produced at the N-1 one.

I did try many set up, but in all the cases I got two different kind of error:

1) the code stops because the charges calculated at the N-1 step are not correct 
-> External file of charges has a total charge:      6408.033605,  instead of        6408.000000

2) the code remains hanged up (so it is still running) but it does not write anymore.
It stops writing in the middle of the SCC cycle!!!

As an additional information, if I run the same identical series of calculations (except for the D3 dispersions which were not implemented in version < 1.3), with an old MPI version (the mpi-r4473 which is the MPI version of dftb+1.2) I never had such problems!

Thank you for the help!

**Comment by aradi** [comment]
Is the problem reproducible. If so, could you upload the two input files, so that we try to reproduce it? (If you don't want them in public, send me directly via mail...)

**Comment by aradi** [comment]
Is the problem still there? Could you eventually try it with the actual version from master?
