### ISSUE TITLE
Testing File Parsers

### ISSUE THREAD

**Issue by JoshuaSBrown** [dftbplus/dftbplus#233]
I apologize if this issue does not follow some format template, I did not see mention of one in the developers guide. I am running into an error when parsing an .hsd input file and was wanting to try to debug it. I was wondering if there was already some unit tests that were made for .hsd files so I could familiarize my self with parser functions?

**Comment by bhourahine** [comment]
Unfortunately there are no unit tests for the parser at the moment. Is there a meaningful error being raised or is it something which is not trapped? If you send me your input I may be able to debug.
