### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by fengbit** [dftbplus/dftbplus#235]
Dear developers,
When I tried compile the dftbplus-18.2, there encountered an error:

[root@localhost dftbplus-18.2]# make
mkdir -p /home/room/cns/DFTB/dftbplus-18.2/_build
[ -r /home/room/cns/DFTB/dftbplus-18.2/RELEASE ] && cp -a /home/room/cns/DFTB/dftbplus-18.2/RELEASE /home/room/cns/DFTB/dftbplus-18.2/_build/RELEASE \
        || /home/room/cns/DFTB/dftbplus-18.2/utils/build/update_release /home/room/cns/DFTB/dftbplus-18.2/_build/RELEASE \
        || echo "(UNKNOWN RELEASE)" > /home/room/cns/DFTB/dftbplus-18.2/_build/RELEASE
mkdir -p /home/room/cns/DFTB/dftbplus-18.2/_build/external/xmlf90
make -C /home/room/cns/DFTB/dftbplus-18.2/_build/external/xmlf90 \
          -f /home/room/cns/DFTB/dftbplus-18.2/external/xmlf90/make.dpbuild \
          ROOT=/home/room/cns/DFTB/dftbplus-18.2 BUILDROOT=/home/room/cns/DFTB/dftbplus-18.2/_build
make[1]: 进入目录“/home/room/cns/DFTB/dftbplus-18.2/_build/external/xmlf90”
touch -r libxmlf90.a /home/room/cns/DFTB/dftbplus-18.2/_build/external/xmlf90/BUILD_TIMESTAMP
make[1]: 离开目录“/home/room/cns/DFTB/dftbplus-18.2/_build/external/xmlf90”
mkdir -p /home/room/cns/DFTB/dftbplus-18.2/_build/prog/dftb+
make -C /home/room/cns/DFTB/dftbplus-18.2/_build/prog/dftb+ -f /home/room/cns/DFTB/dftbplus-18.2/prog/dftb+/make.build \
    ROOT=/home/room/cns/DFTB/dftbplus-18.2 BUILDROOT=/home/room/cns/DFTB/dftbplus-18.2/_build
make[1]: 进入目录“/home/room/cns/DFTB/dftbplus-18.2/_build/prog/dftb+”
/home/room/cns/DFTB/dftbplus-18.2/external/fypp/bin/fypp  -DDEBUG=0 -DRELEASE="'release 18.2'" -DWITH_ARPACK -I/home/room/cns/DFTB/dftbplus-18.2/prog/dftb+/lib_common/ -I/home/room/cns/DFTB/dftbplus-18.2/prog/dftb+/include /home/room/cns/DFTB/dftbplus-18.2/prog/dftb+/lib_common/timerarray.F90 > timerarray.f90
gfortran -O2 -funroll-all-loops -fopenmp -I/home/room/cns/DFTB/dftbplus-18.2/_build/external/xmlf90 -o timerarray.o -c timerarray.f90
timerarray.f90:37.39:

    character(:), allocatable :: header
                                       1
错误： Deferred-length character component 'header' at (1) is not yet supported
timerarray.f90:37.39:

    character(:), allocatable :: header
                                       1
错误： Deferred-length character component 'header' at (1) is not yet supported
timerarray.f90:37.39:

    character(:), allocatable :: header
                                       1
错误： Deferred-length character component 'header' at (1) is not yet supported
timerarray.f90:37.39:

    character(:), allocatable :: header
                                       1
错误： Deferred-length character component 'header' at (1) is not yet supported
timerarray.f90:92.21:

    call this%reset()
                     1
错误： (1)处的‘reset’应该是一个 SUBROUTINE
make[1]: *** [timerarray.o] 错误 1
rm timerarray.f90
make[1]: 离开目录“/home/room/cns/DFTB/dftbplus-18.2/_build/prog/dftb+”
make: *** [dftb+] 错误 2

Please give me a suggest,Thanks.

**Comment by bhourahine** [comment]
Which version of gfortran are you using? This looks to be behaviour of an old version (possibly 4.8). The code has been tested for gfortran 5.4 - 7.1.

**Comment by fengbit** [comment]
Thank you. My gfortran version is 8.3

**Comment by aradi** [comment]
Are you sure, that's the compiler you really use? (Try `gfortran --version`). Because as @bhourahine pointed out, the GNU compiler supports allocatable character components for several years by now. I've just tried to compile the code with gfortran 8.2 and it passes without problems, so unlikely, that they broke it in version 8.3.

**Comment by fengbit** [comment]
Yes, it's 8.3.0, 
[room@localhost ~]$ gfortran --version
GNU Fortran (GCC) 8.3.0

**Comment by aradi** [comment]
I am pretty sure, that you use a different compiler during the build. I just downloaded GFortran 8.3 and compiled DFTB+ (the serial version) without any problems. Please try to make sure, that the right compiler is invoked, when you build the code. You may add the option `-v` to the `FXXOPT` variable in your system specific makefile. This would print the version number (and a lot of other information) at every invokation of the compiler.

**Comment by fengbit** [comment]
Thank you for your help.
Now,  the serial version is OK, but MPI compilation is not working. see #236
