### ISSUE TITLE
Making 'install_api' useful for automated build systems

### ISSUE THREAD

**Issue by ExpHP** [dftbplus/dftbplus#248]
At present, the files produced by `make install_api` are not useful for a code that wants to link to the C api of DFTB+ in an automated build system.  There are several issues:

* The C header file is not installed.
* When DFTB+ is built, so is libxmlf90, but this library is not installed. (and I don't see any option to build against a preinstalled version)
* `libdftb+` has numerous static dependencies that may depend on your system, compilation options and choice of Fortran compiler, such as `libgfortran`.  An external build system attempting to link to `libdftb+` has no way to discover this list of dependencies and emit the appropriate `-l` flags.
* It would be nice to expose `API_VERSION` in some way.

For the first two bullets, it would be nice to have these missing files installed.  For the latter two, generating a pkg-config file would be a huge help.  Basically, the ideal circumstance would be for `make install_api` to automatically generate a pkg-config file like this:

**`$INSTALL_PREFIX/lib/pkgconfig/libdftb+.pc`**

```pkgconfig
prefix=/home/lampam/.local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
api_version=0.2.0

Name: DFTB+
Description: C library for DFTB+, a fast and efficient versatile quantum mechanical simulation software package.
Version: 19.1
Requires.private:
Libs: -L${libdir} -ldftb+ -lxmlf90
Libs.private: -llapack -lblas  -lgfortran -lm -lgomp
Cflags: -I${includedir}
```

so that:
* `pkg-config --cflags --libs --static libdftb+` produces all of the flags necessary to build a program like `test_fileinitc`
* `pkg-config --variable api_version libdftb+` prints the API version.

Does this sound reasonable?

---

As an aside, it is bothersome to see the installer place such a large number of `.mod` files in `include/`.  I am not familiar with these files and how module inclusion works in Fortran, but is it possible that these could somehow be cleanly collected into one subdirectory?

**Comment by aradi** [comment]
Hi,
we were rewriting the build system. see PR #300 . This remedies many of the shortcomings you mention:

* It installs all libraries which are needed into the `lib/` folder, not just the dftb+ library.
* It installs the .h file needed for integration into a C/C++ project.
* It puts all the module files (some compiler needs all of them, unfortunately) into a separate folder.
* It exports a CMake config file, which can be used to automatically achieve the right linking, when using the library in other CMake based projects.

I am still working on the pgk-config export, though.

**Comment by aradi** [comment]
OK, I stared at it the entire afternoon, and I have the feeling that making a proper pkg-config export is almost impossible in CMake unless for trivial cases. In our case, where we depend on several external projects, I could not find a proper way to write the multiple levels of dependencies as a flat list into a pkg-config file. (Not to mention the problem of dealing with generator expressions at this point...)

I'll "postpone" the problem of pkg-config export and close the PR now. If you have any experience with CMake and pkg-config, you would be more than welcome to give us a hand. Also, if you have any comments regarding the PR, let us know.

**Comment by ExpHP** [comment]
Understandable. I'll look into it and see what I can figure out. (I'm definitely no expert in cmake, though!)

The other changes sound extremely promising!  I'll give the PR a try at some point soon.

**Comment by aradi** [comment]
Now, pkg-config has been implemented in 673f645 in the PR #300 . Rather a manual hack than being elegant, though it seems to work.

The only question is, how to deal with the compiler dependent libraries. Depending, whether the linking with the target application is done with Fortran or C compiler, one needs different libraries (e.g. -lgfortran -lm or nothing). Also, it is highly compiler dependent (GNU, Intel, NAG, ...) which libraries one needs. I, therefore, left out those compiler dependent libraries. Is that acceptable from the point of a pkg-config user?

**Comment by ExpHP** [comment]
> Also, it is highly compiler dependent (GNU, Intel, NAG, ...) which libraries one needs. I, therefore, left out those compiler dependent libraries. 

The fact that they're compiler-dependent is, in my opinion, *precisely the reason why* they need to be there. There is no way for downstream code to discover what fortran compiler was used at the time of compilation.

> Depending, whether the linking with the target application is done with Fortran or C compiler, one needs different libraries (e.g. -lgfortran -lm or nothing).

My thoughts are the following:

1. Does supplying `-lgfortran -lm` to `gfortran` cause trouble?  I would expect them to be fairly harmless.
2. I am tempted to believe that `pkg-config` may not be widely used by Fortran codes to gather information about dependencies (but I do not know for certain!).  As indicated by the fact that it only has a `Cflags:` (and no e.g. `Fflags:`), `pkg-config` is highly C-centric, and most downstream projects using it probably want the C interface.
3. Searching my own `pkgconfig` files, I see many instances of `-lstdc++`, so that `c++` code can be linked from `C`.

    ```
    [ lampam @ 10:02:16 ] /usr/lib/pkgconfig
    $ rg stdc++
    x265.pc:10:Libs.private: -lstdc++ -lm -lgcc_s -lgcc -lgcc_s -lgcc -lrt -ldl
    vulkan.pc:10:Libs.private:  -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
    haisrt.pc:10:Libs.private:  -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
    libraw_r.pc:10:Libs: -L${libdir} -lraw_r -lstdc++ -fopenmp
    libgme.pc:16:Libs.private: -lstdc++
    libraw.pc:10:Libs: -L${libdir} -lraw -lstdc++ -fopenmp
    uchardet.pc:9:Libs.private: -lstdc++
    srt.pc:10:Libs.private:  -lpthread -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc
    libheif.pc:14:Libs.private: -lpthread  -lstdc++
    libzmq.pc:10:Libs.private: -lstdc++  -lpthread -lrt
    libde265.pc:12:Libs.private: -lpthread -lm  -lstdc++
    libmodplug.pc:11:Libs.private: -lstdc++ -lm
    ```

That said, to play devils advocate, I also tried searching for `lgfortran`, and only found one result:

```
$ rg gfortran --no-heading
openblas.pc:5:extralib=-lm -lpthread -lgfortran -lm -lpthread -lgfortran
```
(note: the file in question has `Libs.private: ${extralib}`)

OpenBLAS is a library with no Fortran interface, only a C interface (it just happens to contain some Fortran code), so this result does not help my case!

It is hard to tell whether this lack of results is truly due to a common practice against including these flags in libraries with a Fortran interface, or if it is simply that I do not have any static libraries on my system that meet all of the necessary conditions we are interested in (which are that (a) it exposes both Fortran and C interfaces, (b) a static library is installed, (c) it was compiled with `gfortran`, and (d) it has a `pkgconfig` file.  It wouldn't surprise me if there weren't any!).

**Comment by aradi** [comment]
> The fact that they're compiler-dependent is, in my opinion, _precisely the reason why_ they need to be there. There is no way for downstream code to discover what fortran compiler was used at the time of DFTB+'s compilation.

I get your point. I think, I have managed to find a way to extract the needed libraries automatically from CMake. If the code compiled, I could then compile a test example by issuing
```
gcc `pkg-config --cflags dftbplus` test_fileinitc.c `pkg-config --libs --static dftbplus`
```
for various cases with various external libraries (even with MPI parallelisation). See commit 1b8fd70 in PR #300 . By default, the Fortran libraries and flags are written, but you can change it to C by passing the `-DPKGCONFIG_LANGUAGE=C` option to CMake.
