### ISSUE TITLE
Question about external point charges

### ISSUE THREAD

**Issue by S0S-90** [dftbplus/dftbplus#298]
Hi, 
this is not a bug report but only a question about how DFTB+ works.

What I'd like to know is what contributions the energy and gradients contain for a calculation with external point charges.

What I thought until now (after comparison with Gaussian calculations) is:

* The energy contains:
   * of course everything that has to do with the atoms
   * the interactions between atoms and external charges
   * the interactions between the external charges **???**

* The gradients contain:
   * also of course all interactions between the atoms
   * the interactions between atoms and external charges (on atoms as ``forces`` and on external charges as ``forces_ext_charges``)
   * **no** interactions between the external charges

As I watched some very strange behavior I'm not sure anymore if that is correct. Especially I'm not sure if the interactions between the external charges are included in the energy because some of the strange behaviour disappears when I exclude them from the calculations.

Thanks a lot for your answer!

**Comment by aradi** [comment]
The interaction between the external charges themselves is not included. Neither in the energy, nor in the forces.

**Comment by S0S-90** [comment]
Ok, thanks a lot!
