### ISSUE TITLE
Mistake in transport tutorial

### ISSUE THREAD

**Issue by ipcamit** [dftbplus/dftbplus#303]
IN version 19.1 onwards NGEF transport functionality has been added, and for the same following tutorial has been suggested:

https://www.dftbplus.org/fileadmin/DFTB-Plus/public/tutorials/cecamhp/html/transport.html#non-scc-pristine-armchair-nanoribbon

However thee is a mistake in the tutorial I think. When I run its files i get the following error:

> ERROR!
> -> Eigensolver incompatible with transport calculation (GreensFunction or TransportOnly required)
> Path: dftbplusinput/Hamiltonian/DFTB/Solver/RelativelyRobust

The reason is that its still using Relatively Robust solver as the following block is given in the tutorial:

    Hamiltonian = DFTB {
    SCC = No
    MaxAngularMomentum = {
      C = "p"
      H = "s"
     }

    SlaterKosterFiles = Type2FileNames {
      Prefix = "../../../sk/"  # To be substituted with the path to
                               # SK parameters on your local disk
      Separator = "-"
      Suffix = ".skf"
    }

    Eigensolver = TransportOnly{}
    }
 
tries to assign the `TransportOnly` solver using keyword `EigenSolver`. 
However the manual says that solver is to be selected by keyword `Solver`. Hence `Eigensolver = TransportOnly{}` should be `Solver = TransportOnly{}`. Doing so indeed solved my problem.

**Comment by aradi** [comment]
Dear Amit,

indeed, the input structured changed during the final merge. The
material of the tutorial has been also merged in the DFTB+ recipes document

https://dftbplus-recipes.readthedocs.io/en/stable/

where the input has been adapted. The tutorial is deprecated, so I even
removed it from the web site now.

Thanks for reporting!

  Best regards,

  Bálint
