### ISSUE TITLE
Generalize Coulomb Matrix Setup / Ewald summation

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#320]
Right now the Coulomb matrix setup seems to only support 1/r terms. Screened Coulomb interactions (like erf(r)/r or Klopman–Ohno) could also be handled by the current implementation, without the need of reproduce existing code like done in #314.

**Possible Solution**
1. A Coulomb container similar to the one used for the repulsion energy might work here and would allow to generalize the Coulomb matrix setup.
2. Alternatively one could use the existing routines, remove the 1/r afterwards and add the screened Coulomb interactions back. But this seems somewhat impractical at best.

**Comment by awvwgk** [comment]
The `ThirdOrder` class looks promising for this purpose. Wrapping everything from `dftbp_coulomb` in a similar container would allow enough abstraction to implement several electrostatic models in the same infrastructure.

How about making a potential `coulomb` container an extendable class? Every class inheriting from it gains an MPI parallel Ewald summation and only has to take care about the real space part.

**Comment by bhourahine** [comment]
Seems reasonable. Are other Ewald summations also going to be needed (dipole particularly)? Or is the intention to do everything other than 1/r in real space for the moment?
One issue is to avoid following in the DFTB+ electronic structure data types too closely, as the boundary conditions on the electrostatics can in principle need some differences.
