### ISSUE TITLE
WITH_OMP option in make.config

### ISSUE THREAD

**Issue by inseonglee** [dftbplus/dftbplus#338]
Dear DFTB+ developers,

I have a question about WITH_OMP option in compilation process.
In my understanding, when I use cmake I can decide WITH_OMP option in config.cmake file so that the dftb+ code considers WITH_OMP may become true. (I do not test and use with cmake)
But when I use make with make.config, WITH_OMP becomes false even though I use OpenMP parallelization with '-qopenmp' flag in ifort.

Due to this, it seems to be hard to use WITH_OMP option into the code development.
Can anyone explain about this?
If there is a wrong point for me, please tell me anything.

Best Regards
In Seong Lee

**Comment by bhourahine** [comment]
This behaviour should be fixed in pull request #328  (commit 4238dd80 ).

**Comment by inseonglee** [comment]
@bhourahine I tested WITH_OMP option with new commit (8a7ffcf). This commit includes current master branch as well as commit 4238dd8.

In the code, the following part is added for the test purpose in initprogram.F90 file.
`#:if WITH_OMP
  write(*,*) "omp run"
#:else
  write(*,*) "omp not run"
#:endif`
The flag of the code includes '-qopenmp' with ifort compiler.
But the test result shows "omp not run" sentence.

I think that this is caused from the make.config file. It means that current make.config file do not include WITH_OMP option unlike config.cmake file.
After I add WITH_OMP := 1 in the make.config file, the test result shows "omp run" sentence.
Thus, my conclusion is that WITH_OMP option should be added to make.config file for correct use of WITH_OMP option in the code development.

**Comment by bhourahine** [comment]
Thanks for pointing this out. See #354 for your suggested fix.

**Comment by inseonglee** [comment]
This behavior is now fixed (9551096), so I close this issue.
