### ISSUE TITLE
"C" Locale makes "fypp" preprocessor fail

### ISSUE THREAD

**Issue by stephethier** [dftbplus/dftbplus#346]
Hi there,
This is not a bug but it may be worth adding a sentence or two in the installation documentation. Maybe in the "Requirements" section of the INSTALL.rst file.

I set my locale to "C" (export LC_ALL=C) in order to avoid annoying behaviors in "vi". Unfortunately, this seems to crash the DFTB+ preprocessing step for some files. Here is an example:

[ 25%] Generating lib_dftb/vdwdata.f90
cd /p/nano/ethier/DFTBP_GITHUB/dftbplus/_build/prog/dftb+ && ../../../external/fypp/bin/fypp -DWITH_OMP -DWITH_C_EXECUTABLES -I/p/nano/ethier/DFTBP_GITHUB/dftbplus/prog/dftb+/include -DRELEASE="'development version (commit: 91e2b654, base: 19.1)'" /p/nano/ethier/DFTBP_GITHUB/dftbplus/prog/dftb+/lib_dftb/vdwdata.F90 /p/nano/ethier/DFTBP_GITHUB/dftbplus/_build/prog/dftb+/lib_dftb/vdwdata.f90
Traceback (most recent call last):
  File "../../../external/fypp/bin/fypp", line 2978, in <module>
    run_fypp()
  File "../../../external/fypp/bin/fypp", line 2811, in run_fypp
    tool.process_file(infile, outfile)
  File "../../../external/fypp/bin/fypp", line 2486, in process_file
    output = self._preprocessor.process_file(infile)
  File "../../../external/fypp/bin/fypp", line 2365, in process_file
    self._parser.parsefile(fname)
  File "../../../external/fypp/bin/fypp", line 253, in parsefile
    self._includefile(None, inpfp, fobj, os.path.dirname(fobj))
  File "../../../external/fypp/bin/fypp", line 265, in _includefile
    self._parse(fobj.read())
  File "/usr/pppl/python/3.6.4/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 923: ordinal not in range(128)

It turns out that some *.F90 files contain characters that are in the extended ASCII character range (128 to 255 in the ASCII table). I can make it work by changing my LOCALE to en_US.UTF-8 with:
                          export LC_ALL=en_US.UTF-8

Or simply with  "LC_ALL=en_US.UTF-8 make"

Other locales work too...

**Comment by aradi** [comment]
Thanks a lot for reporting. I have fixed fypp to ensure locale independent file processing, see PR #350, commit f413cd1. It should be on master soon.
