### ISSUE TITLE
Manual not update for external charges

### ISSUE THREAD

**Issue by inseonglee** [dftbplus/dftbplus#356]
Hello dftbplus developers,

In current manual for external charge calculations, it said that the blurred charge is not available for periodic systems. But blurred charges for periodic systems are already added in 18.1 release, thus the manual for this part should be modified.

Best regards
In Seong Lee

**Comment by bhourahine** [comment]
See PR #357 for the fix.

**Comment by inseonglee** [comment]
Enough for the fix. Now I will close this issue
