### ISSUE TITLE
There is no matching specific subroutine of GPU GVD in eigenvects.f90

### ISSUE THREAD

**Issue by ibnusyuhadap3** [dftbplus/dftbplus#359]
I was built dftb+ with GPU, here I use MAGMA. But it fails each time compile eigenvects.f90. The MAGMA was built with MKL ilp64, test of MAGMA also going fine. I use same compilers for both GPU and MAGMA. I use Ubuntu 18.04 and CUDA 10.2. Below is the snippet result of dftb+

`ifort -O3 -standard-semantics -heap-arrays 10 -integer-size 64 -I/usr/local/cuda-10.2/include -I/usr/local/magma/mkl/intel/include -L/usr/local/cuda-10.2/lib64 -I/home/mycompt/Public/dftbplus-19.1-mkl-gpu/_build/external/xmlf90 -I/home/mycompt/Public/dftbplus-19.1-mkl-gpu/_build/external/magmahelper -o eigenvects.o -c eigenvects.f90
eigenvects.f90(69): error #6285: There is no matching specific subroutine for this generic subroutine call.   [GPU_GVD]
      call gpu_gvd(ngpus,HSqrReal,SSqrReal,eigen,'L',jobz)      
-----------^
`

I knew, it is experimental. Please help me. Thank you.

**Comment by aradi** [comment]
Could it be an integer size mismatch? When you use the CMake toolchain files as shipped with DFTB+, you would usually get 32 bit integers, which corresponds to the `lp64` not to the `ilp64` model.

**Comment by ibnusyuhadap3** [comment]
I did not test with 32 version, yet. Because, NVIDIA officially not release 32 library anymore.

**Comment by aradi** [comment]
I thought, if you select `Intel10_64lp` instead of `Intel10_64ilp` for BLAS vendor when compiling MAGMA, it may solve the issue.
