### ISSUE TITLE
Implicit Solvation Model?

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#361]
It seems like DFTB+ is missing an implicit solvation model, like a polarizable continuum model (PCM) or a generalized Born (GB) model. Is there interest to have an implicit solvation model in DFTB+?

The [DFTB module of AMS](https://www.scm.com/doc/DFTB/DFTB_Model_Hamiltonian.html#solvation) got recently a GB model. And the `xtb` program is supporting a GB model as well.

**Comment by bhourahine** [comment]
There is a partial [implementation](https://github.com/bhourahine/dftbplus/tree/ddPCM)
using the [ddPCM](https://www.ddpcm.org/) library. The nice feature with that approach is linear cost in solvated atoms (and relatively small prefactor).
The branch is 2 years out of date, but the bigger issue is the re-factoring of the electrostatics structure, which should probably happen before other  changes.

**Comment by awvwgk** [comment]
@bhourahine Should we close this with #461 or are there still plans for a PCM model in DFTB+?
