### ISSUE TITLE
Inconsistency between GenFormat specifications and actual implementation

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#363]
Apparently the DFTB+ GenFormat parser doesn't care about newline tokens at all, therefore this is a valid GenFormat input:
```
16 S H N    1    1    2.19855889440000    1.76390058240000    0.88014548160000    2    1    1.76390058240000    0.88014548160000    2.19855889440000    3    1    0.88014548160000    2.19855889440000    1.76390058240000    4    1    4.84115108400000    1.61941554720000    4.93981400880000    5    1    4.35630903840000    2.49981169680000    3.63248012160000    6    1    3.51957925440000    1.15357413600000    4.08403345680000    7    1    4.08403345680000    3.51957925440000    1.15357413600000    8    1    4.93981400880000    4.84115108400000    1.61941554720000    9    1    3.63248012160000    4.35630903840000    2.49981169680000   10    1    2.49981169680000    3.63248012160000    4.35630903840000   11    1    1.15357413600000    4.08403345680000    3.51957925440000   12    1    1.61941554720000    4.93981400880000    4.84115108400000   13    2    1.37461317840000    1.37461317840000    1.37461317840000   14    2    3.99815460000000    1.99105592400000    4.46364507600000   15    2
4.46364507600000    3.99815460000000    1.99105592400000   16    2    1.99105592400000    4.46364507600000    3.99815460000000    0.00000000000000    0.00000000000000    0.00000000000000    5.01336000000000    0.00000000000000    0.00000000000000    0.00000000000000    5.01336000000000    0.00000000000000    0.00000000000000    0.00000000000000    5.01336000000000
```
The only limit present is a 1k character limit for lines (compiled with Intel, maybe related to #13), exceeding this limit gives a not very helpful error message.
```
ERROR!
-> Unexpected end of data
Path: dftbplusinput/Geometry/genFormat
Line: 1-3 (File: dftb_in.hsd)
```

Yet the manual explicitly mentions lines in appendix C:
> The first line of the file contains the number of atoms,n, followed by the type of geometry.

> The second line contains the chemical symbols of the elements present separated by one or morespaces

Is this behaviour intended?

A possible fix is outlined in https://github.com/dftbplus/dftbplus/pull/362#issuecomment-581026245.

**Comment by aradi** [comment]
I tried to implement it without  making use newline, indeed. I had some reasons to do so, but I would not do it again that way. It causes more trouble then it helps, especially it could leave input errors undetected. I like your solution for the xyz-reader, we should do the same for the gen-reader as well.

**Comment by aradi** [comment]
The 1K line length limit is hardcoded in the parser at the moment and there is no easy way to detect longer lines as we read it with one record-based Fortran read, which automatically chops anything beyond the length of the character variable. I think, this is not crucial, we can fix it later. I want to replace the parser infrastructue at some point anyway (depending on eventual developments on saydx...)

**Comment by awvwgk** [comment]
I wonder if the HSD tokenizer could return a newline token? Since you are reading the file record by record anyway, you are probably generating the newline characters yourself, which would ensure they are always well defined and not a wild mix of `\n` and `\r`. Skipping newlines when not wanted is easy, but they would be available without hacks in the geometry reader.

Regarding the line length limit, I usually use something like the code below to read arbitrary length lines. In case of static line lengths the loop has to be removed. If the non-advancing `read` is not returning the EOR signal, the line is longer than allowed and an appropriate warning can be generated.

```fortran
subroutine getLine(unit, line, iostat)
   integer, intent(in) :: unit
   character(len=:), allocatable, intent(out) :: line
   integer, intent(out), optional :: iostat

   integer, parameter :: buffersize = 512
   character(len=buffersize) :: buffer
   integer :: size, err

   line = ''
   do
      read(unit, '(a)', advance='no', iostat=err, size=size) buffer
      if (err > 0) then
         if (present(iostat)) iostat = err
         return ! an error occurred
      end if
      line = line // buffer(:size)
      if (err < 0) then
         if (is_iostat_eor(err)) err = 0
         if (present(iostat)) iostat = err
         return
      end if
   end do

end subroutine getLine
```

**Comment by aradi** [comment]
Actually, we do generate newlines ourselves: it is `lineFeed` set to `achar(10)` in [charmanip.F90](https://github.com/dftbplus/dftbplus/blob/c733b0d4ad86f7b6f590ced1c720100013f4ff88/prog/dftb%2B/lib_io/charmanip.F90#L50)

As for the arbitrary line length, that could be indeed a god solution. I am not sure, though, whether it is didactically a good idea, to let people to use arbitrary long lines, as they may feel tempted to do so :smile:

**Comment by awvwgk** [comment]
> Actually, we do generate newlines ourselves: it is `lineFeed` set to `achar(10)` in [charmanip.F90](https://github.com/dftbplus/dftbplus/blob/c733b0d4ad86f7b6f590ced1c720100013f4ff88/prog/dftb%2B/lib_io/charmanip.F90#L50)

Than we should replace the usage of the `new_line()` intrinsic with the `newline` constant.

> As for the arbitrary line length, that could be indeed a god solution. I am not sure, though, whether it is didactically a good idea, to let people to use arbitrary long lines, as they may feel tempted to do so

A malicious user could dump GBs of data in one line to overflow the memory, which will likely cause DFTB+ to crash or the system to freeze as it begins swapping. I doubt DFTB+ is a good attack vector, but it might happen by accident from a bad script. At least a warning for too long lines would be helpful.
