### ISSUE TITLE
Add XYZ support to waveplot and modes 

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#364]
Both need to be able to read XYZ format to match DFTB+

**Comment by awvwgk** [comment]
So these parts

https://github.com/dftbplus/dftbplus/blob/0fdc064be36a7a2bd204a22fa7519fb0d90d17cc/prog/waveplot/initwaveplot.F90#L362-L371
https://github.com/dftbplus/dftbplus/blob/0fdc064be36a7a2bd204a22fa7519fb0d90d17cc/prog/modes/initmodes.F90#L325-L334

need to be consistent with

https://github.com/dftbplus/dftbplus/blob/0fdc064be36a7a2bd204a22fa7519fb0d90d17cc/prog/dftb%2B/lib_dftbplus/parser.F90#L281-L291

Should be easy to fix this in #365 and include the VaspFormat as well. You can assign me for this.

**Comment by bhourahine** [comment]
Thanks, just have
