### ISSUE TITLE
HalogenXCorr not working with   KPointsAndWeights

### ISSUE THREAD

**Issue by apolionl** [dftbplus/dftbplus#380]
Dear developers. 
I am using DFTB+ development version (commit: 9551096). 
My task is tu run a MD simulation of a box (PBC) containing several molecules of bromobenzene. At the moment I am testing whether using halogen corrections (HalogenXCorr) could bring any improvement of our calculations. 

Test files provided in the examples are working fine, however when I try to adapt them to my system, I get a error. If I use something like this 
`    HalogenXCorr = Yes ...
KPointsAndWeights[absolute] = { 0.0 0.0 0.0 1.0  }
`
The program complains and gives me the following error 
> WARNING!
-> The following 1 node(s) have been ignored by the parser:
(1)
Path: dftbplusinput/Hamiltonian/DFTB/HalogenXCorr
Line: 63-63 (File: dftb_in.hsd)
ERROR!

When I hash `HalogenXCorr `, the program works fine, but if instead I hash `KPointsAndWeights`, then the program  complains and ask me to use it. 

Seeking help, I wrote to Dr. Jan Rezac . He told me to ask directly here as the problem seems to be the PBC itself and not the implementation of `  HalogenXCorr ` _per se_ .

Thanks in advance

**Comment by awvwgk** [comment]
Looks like the HalogenXCorr node cannot be present if the system is periodic:

**Comment by bhourahine** [comment]
Yes, the correction was fitted for molecular systems, not condensed phases. After some discussion, the periodic case was disabled for the moment, as the description for highly coordinated systems (as occurs for example with molecular crystals) seems worse than for molecular structures with few halogen bonds.

**Comment by aradi** [comment]
@apolionl If you comment out the three lines
```
if (tPeriodic) then
  call error(...)
end if
```
in the coded posted by @awvwgk, you should be able to try the correction for periodic cases.

Please note, that the correction was fitted on non-periodic systems, and some tests indicate that it does not work well for periodic sytems. It is not a technical problem on the implementation side, periodicity was just not considered when the correction was fitted. (The author of the correction confirmed that.)

So, we would still prohibit periodic calculations in the official code You may play around with it for periodic systems yourself, nevertheless. Make sure to analyze the results sceptically. If you have any positive experiences, let us and/or Jan Rezac know, so we may reconsider our decision.
