### ISSUE TITLE
Write[Read]BinaryContact: default value and manual

### ISSUE THREAD

**Issue by dryndyk** [dftbplus/dftbplus#423]
New WriteBinaryContact and ReadBinaryContact properties have default .TRUE. values (in parser.F90). As a result, old inputs with shiftcont_ContactId.dat files stop to work. Besides, these new options are not described in the manual. Also, position of new properties directly in Transport{} block as a property is not good for me. I placed it inside Task{} at the moment and changed the default to .FALSE. In this way, it is better.

**Comment by bhourahine** [comment]
> As a result, old inputs with shiftcont_ContactId.dat files stop to work.
Not if you set the input version, as is suggested practice, since backward compatibility is then preserved.

> Besides, these new options are not described in the manual.
Thank you for pointing out gap in the documentation.

**Comment by dryndyk** [comment]
> > As a result, old inputs with shiftcont_ContactId.dat files stop to work.
> 
> Not if you set the input version, as is suggested practice, since backward compatibility is then preserved.

OK. You are right!

**Comment by dryndyk** [comment]
Now it is written in the manual that Fermi level is optional but below
"In order to set up a proper transport calculation the user should also define the contacts'
Fermi levels (as printed in the files previously produced by using
\is{ContactHamiltonian} tasks)"
