### ISSUE TITLE
AnnealSW (DFTB+19.1 show C atoms disperion)

### ISSUE THREAD

**Issue by ManabuInukai** [dftbplus/dftbplus#429]
Dear Developers,

I hved tried "annealSW" at "DFTB+ Recipes" on  DFTB+18.2 and 19.1.
DFTB+ 18.2 showed goot reslts (graphene structure), but DFTB19.1 showed C atoms dispersion.
(compilling condition: gfortran, OpenBLAS, openMP, mio-ext)

DFTB+ 19.1 with SCC worked, but results for "annealSW", etc remained start structure.
(I added 
-----
ForceEvaluation = Dynamics

  SCC = Yes
  SCCTolerance = 0.8e-3
-----
to dftb_in.hsd for annealSW)

Would you give me any advices ?

Best Regards,
M. Inukai

**Comment by aradi** [comment]
Dear M. Inukai,

Thanks for reporting. Could you provide more details? The best would be one input file `dftb_in.hsd` which gives different results with version 18.1 and 19.1, then we could have a look at it.

**Comment by ManabuInukai** [comment]
Dear Dr. B. Aradi and co-worker

Thank you for your reply.

Sorry, I tried only version 18.2, 19.1 and 19.2.
I will send the file of "annealSW" of 18.2 and 19.1 as an attachment.
(In version 18.2, it ran on PerserVersion 6, so it was rewritten to PerserVersion 6.)

Please forgive me if I make a mistake.

Best Regards, 
M. Inukai 

************************************************ 
Manabu Inukai 
Technical staff Ⅰ 
RIKEN Baton Zone Program 
RIKEN Cluster for Science, 
Technology and Innovation Hub (RCSTI) 
2-1 Hirosawa, Wako-shi, saitama 351-0198, JAPAN 
Tel/Fax: +81-48-467-4058 
E-mail: manabu.inukai@riken.jp 
************************************************

**Comment by aradi** [comment]
@ManabuInukai Github won't show the attachment, if you send it as a mail. Could you, please, upload it directly in Github, or send it by mail directly to me?

**Comment by ManabuInukai** [comment]
[annealSW_19_1.tar.gz](https://github.com/dftbplus/dftbplus/files/4424391/annealSW_19_1.tar.gz)
[annealSW_18_2.tar.gz](https://github.com/dftbplus/dftbplus/files/4424392/annealSW_18_2.tar.gz)

Sorry for being unfamiliar.
Thank you

**Comment by aradi** [comment]
Thanks, I had a quick look at it. It is indeed a bug, but not specific to your example. I have created an issue, see #447. As a workaround for the moment, turn on the `MullikenAnalysis` option in the `Analyses` block, and you should recover the old (correct) results.

**Comment by bhourahine** [comment]
The fix for this issue has been added to the main code ( #448 ).
