### ISSUE TITLE
Travis-CI webhook seems dead

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#430]
It seems that the https://travis-ci.org webhook is only working erratically now and then, sometimes it is not even triggered by the commit and sometimes it is triggered and fails to report back, which makes the CI pretty useless.

I'm mirroring this repository for a while now (using the pull bot) and also running the same CI on all my branches and the master, but on my fork there are no issues with the Travis-CI integration. For my fork I've setup the integration via the Travis-CI app instead of a webhook, so it might be worth to migrate DFTB+ from https://travis-ci.org to https://travis-ci.com and replace the webhook by the GH app.

@dftbplus/administrators The migration can be done directly on https://travis-ci.com but requires admin permissions to the dftbplus organisation. Please remember to remove the stale webhook afterwards.

**Comment by aradi** [comment]
I have migrated the repository now. Webhook has been disabled, thanks for the note, I'd have forgotten it otherwise :wink:
