### ISSUE TITLE
dptools test fails on Haswell hosts

### ISSUE THREAD

**Issue by migueldiascosta** [dftbplus/dftbplus#44]
https://github.com/dftbplus/dftbplus/blob/8a1d1af27ff7a96390e1e10e9ba186b1d217eb06/test/tools/dptools/test_grids.py#L42

this is failing on Haswell hosts (see https://github.com/easybuilders/easybuild-easyconfigs/pull/5263)

the difference between architectures is likely coming from numpy or mkl, but wouldn't `self.assertLess(diff, FLOAT_TOLERANCE)` be sufficient, as in the inverse transformation?

**Comment by aradi** [comment]
You are right, that is numerically not robust. Thank you for reporting! I've made fix (#45), it will be on the master soon.

**Comment by aradi** [comment]
Has been fixed in 06e0a95
