### ISSUE TITLE
Frequency / Phonon calculations

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#482]
DFTB+ seems to be able to calculate second derivatives by finite differences, but it can't perform any useful calculation with the obtained hessian matrix on its own.

It would be nice if the hessian matrix could be at least diagonalized and the frequencies reported. Also the calculation of some easily accessible thermodynamic function would greatly enhance the usability of this driver.

**Comment by bhourahine** [comment]
There is an external tool in the codebase (modes), but are you suggesting that should be integrated into the main code? This raises several points for discussion (reloading the Hessian would be needed for simple isotopic substitution for example, for MPI parallelism the electronic structure decomposition would not be optimal for the hessian, also are you proposing hessian calculation for different structures within say an MD calculation - this would require some re-engineering of the main code workflow).

Also, other than zero-point or harmonic free energy, what properties did you have in mind?

**Comment by awvwgk** [comment]
I found `modes` after searching the DFTB+ code base, it is sparsely documented in the manual and the recipes, therefore I missed it in the first place. Having those functionalities _also_ in the main code would make life a lot easier, without scarifying detailed control in the `modes` program. I'm just looking for one (optional) diagonalization and some more analysis, but as it stands right now, I will probably implement it myself elsewhere.

Combining geometry optimizations and second derivatives is something I would find very convenient, but this is out-of-scope of this issue.

Regarding properties, I want to calculate free energies with a special partition function: https://dx.doi.org/10.1002/chem.201200497

**Comment by pecchia** [comment]
There is also a forthcoming tool "phonons" to compute dispersions

**Comment by awvwgk** [comment]
This issue is fixed for me by https://github.com/grimme-lab/xtb/pull/208.

Since we are not planning anything on this in the near future, I will just close it.
