### ISSUE TITLE
Done. Of course it means the DFTB+ test README also needs a PR.

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#496]
Convert and update the DFTB+ test framework README to an rst file.

_Originally posted by @bhourahine in https://github.com/dftbplus/dftbplus/pull/489/review_comment/create_

**Comment by bhourahine** [comment]
Related to #406

**Comment by awvwgk** [comment]
More like a duplicate.

**Comment by awvwgk** [comment]
Closing in favour of #406
