### ISSUE TITLE
empty results.tag if SCC not converged for static calculation

### ISSUE THREAD

**Issue by lixinyuu** [dftbplus/dftbplus#503]
Hi,

This issue is about writing output files of DFTB+ 19.1 static calculation. I am trying to run a DFTB+ NEB calculation based on ASE NEB (https://wiki.fysik.dtu.dk/ase/ase/neb.html). 

As we known, ASE DFTB+ interface depends on reading the force and energy in results.tag (https://github.com/dftbplus/dftbplus/issues/123). However, I met the problem that DFTB+ writes nothing in the results.tag if "SCC is NOT converged, maximal SCC iterations exceeded".

Can you please check if this is a bug of DFTB+? If not, is there any solution for this?

Thanks very much.

**Comment by bhourahine** [comment]
there are two options, either:

1) Increase the number of SCC cycles (possibly also read in initially converged charges either for one of the relaxed geometries or for a similar structure on the NEB path). This is the  MaxSccIterations keyword (and ReadInitialCharges).

2) Either increase the value of the SCC convergence tolerance (the default SccTolerance is 1E-5, but 1E-4 may be OK) or set the code option to continue even if the calculation has not converged (ConvergentForcesOnly = No). In particular the second option does mean that incorrect non-ground state energies and forces may be returned to ASE (this may be close to the correct values if partial convergence is achieved).

Note that if the structure is not converging, an electronic temperature may also help (the Filling block).

**Comment by lixinyuu** [comment]
@bhourahine Thanks Ben. Your suggestion make the SCC converged, thus unconverged energy and force are not needed any more.

**Comment by rgarcia87** [comment]
Hi, 

I had the same error "SCC is NOT converged, maximal SCC iterations exceeded" when I was trying to compute periodic molecular systems. In this case, the reported SCC error was spuriously high from the beginning (_eg_, 1E+16). This was always the case disregarding the electronic temperature, number of k-points, Slater-Koster files, or any other input parameter used. Non-periodic systems were running fine. 

The problem disappeared when switching from the dftb+ executable provided with Conda, to [the stable version provided by the developers](https://dftbplus.org/download). 

I hope someone in the community may find this useful. Thank you!

**Comment by lixinyuu** [comment]
@rgarcia87 Thanks Rodrigo. BTW, I felt your name was quite familiar when I saw the email, and then I realized I read lots of your papers. Thanks for those great works.

**Comment by aradi** [comment]
@rgarcia87 Dear Rodrigo, would it be possible to provide an self-containing example, where the Conda version fails to converge, while the one provided by us converges? I'd like to have a look at that and investigate it further.
