### ISSUE TITLE
List of supported compiler versions

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#515]
There is not a list of known good compiler combinations included with the source (for example requirement of gfortran >= 7.4).

**Comment by aradi** [comment]
Valid point. Currently, we publish this information on the release-notes page on dftbplus.info. Probably, we should put this into `INSTALL.rst`? I could just make a table there, which contains the combinations buildbot runs...

**Comment by bhourahine** [comment]
Addressed by #551
