### ISSUE TITLE
get_opt_externals 

### ISSUE THREAD

**Issue by cnegre** [dftbplus/dftbplus#52]
./utils/get_opt_externals all  

Only works when replacing 

urlprefix = 'http://www.dftb.org/fileadmin/DFTB/public/slako'

by 

urlprefix = 'https://www.dftb.org/fileadmin/DFTB/public/slako'

In line 90 of ./utils/get_opt_externals script.

**Comment by aradi** [comment]
There was apparently a problem with the webserver at dftb.org, now it works with both http and https.
