### ISSUE TITLE
Geometry output

### ISSUE THREAD

**Issue by Mverena** [dftbplus/dftbplus#529]
Hello,

I observed two problems with the gen output, when performing calculations with > 10 atomic species and using dummy names for those species that contain > 2 digits as name.

1) When using >2 digits as a specifier for the atomic species, like "H11", next to a different specifier like O they get combined to OH11 instead of O H11. Note: I am using these dummy names due to a modification of the SK files from an original Hydrogen file.

2) When having > 100 atoms in the system and > 10 atomic species the atomic indices' and atomic species' numeric specifier get combined to e.g. 11011 instead of 110 11.

These issues require me to always manually modify the gen output in order to use it.

Best
Verena

**Comment by bhourahine** [comment]
Can you test the code in #538 to see if this resolves your issue?

**Comment by Mverena** [comment]
Hi Ben,

thanks a lot for the fix. The code resolves my issue.
The gen output looks fine now.

Best
Verena
