### ISSUE TITLE
error for ~30,000 atoms

### ISSUE THREAD

**Issue by blindcharzard** [dftbplus/dftbplus#534]
When using less than 20,000 atoms, there is no problem. However, increasing to >=30 000 atoms causes the following error.

"MKL_SCALAPACK_ALLOCATE in mr2d_malloc.c is unsucceseful, size = 18446744061294680096 " when using >1 MPI tasks for large systems.

compiled with intel MKL scalapack.

any ideas would be appreciated.

Best,
Justin

**Comment by aradi** [comment]
Wow! The size MKL tries to allocate here is basically 2^64, so it is not surprising that it fails. The only question is, where it comes from... It would be good to try to narrow it down. Could you for example change the eigensolver and see, whether the problem remains?

**Comment by blindcharzard** [comment]
Yes, for QR, RelativelyRobust, and DivideandConquer all give the same results. I suppose it is related to this issue: 'https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/Crash-while-calling-pdmr2d-for-a-large-matrix/td-p/1138292'.

**Comment by aradi** [comment]
OK, so it is probably not on our side. Would you be interested to try one of the ELSI-solvers? They should be as good (or even better!) than the MKL-solvers for large systems. You would have to get the source from the master branch, though. Also, you would have to compile the [ELSi library](https://wordpress.elsi-interchange.org/index.php/download/) first.
