### ISSUE TITLE
Suspect formula in transition dipole moment

### ISSUE THREAD

**Issue by francesco-bosia** [dftbplus/dftbplus#535]
There is a suspect formula [here](https://github.com/dftbplus/dftbplus/blob/a4e65b65da71b61a866a42ec79649972ba85ec86/prog/dftb%2B/lib_timedep/linrespcommon.F90#L814).

I think it should be 

```
    rtmp = eval(ii)**(-1/4) ,
```
as also suggested by by the [literature](https://doi.org/10.1016/j.theochem.2009.04.034) and by the comment
```
! 1._dp / sqrt(sqrt(eval(ii))) .
```
In this subroutine, eval are the eigenvalues of the coupling matrix, i.e. the square of the vertical transition energies. 
I think one could use the coefficients directly, as done in [here](https://github.com/dftbplus/dftbplus/blob/a4e65b65da71b61a866a42ec79649972ba85ec86/prog/dftb%2B/lib_timedep/linrespcommon.F90#L782), instead of transforming the eigenvectors in-place. 
In fact, one gets wild transition dipoles, on the order of 1e4 - 1e6 Debye for a bright state. 

Or am I missing something?

**Comment by aradi** [comment]
@francesco-bosia Thanks a lot! indeed, this is an implementation bug! We will fix it asap!
