### ISSUE TITLE
CMake Fails with Fortran compilers

### ISSUE THREAD

**Issue by inseonglee** [dftbplus/dftbplus#555]
Hello, developers.

I currently tested with bhourahine:reksRefactorUpdate for the REKS code.

For cmake process, following two errors occur.

1. DFTB+ building system does not read relative path for toolchain file. For example, it does not read "cmake -DTOOLCHAIN_FILE=../intel.cmake ..". It can read "cmake -DTOOLCHAIN_FILE=/home/......../dftbplus/intel.cmake ..".

2. With intel.cmake configuration, "Could NOT find OpenMP_Fortran" error occurs.
In current examples for cmake configuration such as intel.cmake, there are no flags for openmp-related variables.
Should I add these variables such as OpenMP_Fortran_FLAGS or OpenMP_Fortran_LIB_NAMES?

Please let me know about the solution..

Best Regards,
In Seong Lee.

**Comment by bhourahine** [comment]
Hello Lee,

the recent changes in cmake in the main repository means that

env FC=ifort CC=icc cmake ..

should work.

Regards

Ben

On 19/07/2020 05:46, inseonglee wrote:
>
> Hello, developers.
>
> I currently tested with bhourahine:reksRefactorUpdate for the REKS code.
>
> For cmake process, following two errors occur.
>
> 1.
>
>     DFTB+ building system does not read relative path for toolchain
>     file. For example, it does not read "cmake
>     -DTOOLCHAIN_FILE=../intel.cmake ..". It can read "cmake
>     -DTOOLCHAIN_FILE=/home/......../dftbplus/intel.cmake ..".
>
> 2.
>
>     With intel.cmake configuration, "Could NOT find OpenMP_Fortran"
>     error occurs.
>     In current examples for cmake configuration such as intel.cmake,
>     there are no flags for openmp-related variables.
>     Should I add these variables such as OpenMP_Fortran_FLAGS or
>     OpenMP_Fortran_LIB_NAMES?
>
> Please let me know about the solution..
>
> Best Regards,
> In Seong Lee.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdftbplus%2Fdftbplus%2Fissues%2F555&data=02%7C01%7Cbenjamin.hourahine%40strath.ac.uk%7Cb13342aab43a43b9129208d82b9ea666%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637307307680723483&sdata=aXvSwpLWFmCFzgezdRVT7B3HQlwJiOfalewadXjH3ik%3D&reserved=0>,
> or unsubscribe
> <https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACKD6IZ6G2AWHSVT6BCOCVDR4J3A3ANCNFSM4PA2NI5Q&data=02%7C01%7Cbenjamin.hourahine%40strath.ac.uk%7Cb13342aab43a43b9129208d82b9ea666%7C631e0763153347eba5cd0457bee5944e%7C0%7C0%7C637307307680733477&sdata=w%2FN4dWvXiILEk7O6%2FLlHT%2BnqTlLBBuhDOu3jQJtY7yk%3D&reserved=0>.
>
-- 
        Dr.  B.  Hourahine,  Senior  lecturer
            SUPA, Department  of  Physics,
             University  of  Strathclyde,
              John  Anderson  Building,
          107 Rottenrow, Glasgow G4 0NG, UK.                    
  +44 141 548 2325, benjamin.hourahine@strath.ac.uk

The  Department is  a partner  in SUPA,  the Scottish
            Universities Physics Alliance

The University  of Strathclyde  is a  charitable body,
       registered in Scotland, number SC015263

**Comment by inseonglee** [comment]
@bhourahine Thanks, The command "env FC=ifort CC=icc cmake -DTOOLCHAIN=intel .." works normally. I will close this issue.
