### ISSUE TITLE
Spin constants difference

### ISSUE THREAD

**Issue by inseonglee** [dftbplus/dftbplus#562]
Hello, developers

There is an issue for spin constants.
The values are different from the dftb+ manual and dftb.org site.

For mio set, the value of W_dd for S is -0.080 in the manual and -3.1592 in the http://www.dftb.org/fileadmin/DFTB/public/slako/mio/mio-1-1.spinw.txt.

The difference is too large so which one is correct value?

Best Regards,
In Seong Lee

**Comment by bhourahine** [comment]
Yes, the GGA values in the manual are rounded to 3 decimal places, while the file with the parameters gives these to 4 decimal places. The values included with the parameters are the more accurate so should be preferred (will open a pull request to update the table).

**Comment by inseonglee** [comment]
@bhourahine Did you mean that -3.1592 is accurate value for W_dd of sulfur atom? Except this value, other values (W_ss, W_sp, W_pp) are almost similar for two files (manual and dftb+ website). For W_dd value, this is not the problem of decimal point, the value (-3.1592) is ~40 times larger than the value in the manual (-0.080).

**Comment by bhourahine** [comment]
Sorry, I'd missed the W_dd problem. In this case the values included with the parameter set are probably incorrect, but I will investigate.

**Comment by dwaipayanroni** [comment]
Hi,

I was trying to find the table for the spin constants on the dftb.org website but couldn't find that. Can anyone provide the updated link for that? Also how to understand whether one should use the LDA or GGA spin constant values with a particular set of skf files.
