### ISSUE TITLE
setupgeom with mpi

### ISSUE THREAD

**Issue by dryndyk** [dftbplus/dftbplus#581]
setupgeom is not build with MPI
If one changes setupgeom/CMakeLists.txt, it works 

[CMakeLists.txt](https://github.com/dftbplus/dftbplus/files/4978205/CMakeLists.txt)

**Comment by bhourahine** [comment]
Setting WITH_TRANSPORT will build it, either in config.cmake or
env cmake -DWITH_TRANSPORT=1 ..

**Comment by dryndyk** [comment]
I used WITH_TRANSPORT but it gives error, can not find mpi.mod

**Comment by bhourahine** [comment]
Which compiler is being used? Does something like 
env FC=mpifort cmake -DWITH_MPI=1 -DWITH_TRANSPORT=1 ..
not work?

**Comment by dryndyk** [comment]
I use gfortran from gcc-9.3.0
Everything is OK, but not  setupgeom:

[ 99%] Building Fortran object prog/setupgeom/CMakeFiles/setupgeom.dir/setupgeom.f90.o
/home/dryndyk/dftbplus/build/prog/setupgeom/setupgeom.f90:16:6:

   16 |   use mpi, only : MPI_THREAD_FUNNELED, MPI_COMM_WORLD
      |      1
Fatal Error: Cannot open module file ‘mpi.mod’ for reading at (1): No such file or directory
compilation terminated.

Nothing helps, only the modification that I made in setupgeom/CMakeLists.txt

**Comment by bhourahine** [comment]
What happens if you use FC=mpifort i.e. the wrapper around gfortran instead of the compiler? This should resolve the include path for MPI.
FC=gfortran cmake -DWITH_MPI=1 -DWITH_TRANSPORT=1 ..
fails with the mpi.mod error you describe, but
FC=mpifort cmake -DWITH_MPI=1 -DWITH_TRANSPORT=1 ..
builds successfully.
Alternatively, you could set the include paths for mpi as the Fortran arguments if you use gfortran directly.

**Comment by dryndyk** [comment]
I tried
env FC=mpifort
but in my system, it does not work.

**Comment by bhourahine** [comment]
What compiler options were you using with earlier mpi builds and gfortran?
The compiler flags can be set in sys/gnu.cmake or via Fortran_FLAGS_RELEASE or CMAKE_Fortran_FLAGS variables.

**Comment by dryndyk** [comment]
I use default sys/gnu.cmake and modifications are made with setup file and my.cmake (in zip below)
[setup_files.zip](https://github.com/dftbplus/dftbplus/files/4979898/setup_files.zip)

I will check it at another comp.

**Comment by bhourahine** [comment]
FC=gfortran cmake works, so closing issue.
