### ISSUE TITLE
dftbplus.pc

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#590]
Probably we should switch to generating with [configure_package_config_file](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) instead of configure_file.

**Comment by awvwgk** [comment]
Generating a pkg-config file with `configure_file` is fine in my opinion, this shouldn't be dropped. Also, if I'm not mistaken DFTB+ does already generate cmake package files, see:

https://travis-ci.com/github/conda-forge/dftbplus-feedstock/builds/178431259#L4789-L4791

**Comment by awvwgk** [comment]
This is handled now with the recent CMake changes. Therefore, closing this issue for now.
