### ISSUE TITLE
InputVersion in dftb_in converted to ParserVersion in dftb_pin

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#592]
Setting the input from the code release as InputVersion converts into the (internal) parser number in the processed output. Probably clearer to leave as code version and possibly to convert to release number if possible.

**Comment by awvwgk** [comment]
I don't think this is desirable, on updating from an older `InputVersion` we will create input for the latest `ParserVersion`, we might have multiple `InputVersion` referring to the same `ParserVersion` or might be in between releases were the `ParserVersion` is already bumped but the `InputVersion` not.

Replacing the `InputVersion` by a `ParserVersion` is in my opinion the safest and least ambiguous choice.

**Comment by bhourahine** [comment]
A look-up table back from ParserVersion to InputVersion then needs to be available somewhere, unless the manual always carries both instead of just the release label (== InputVersion, and the original motivation for what became InputVersion).

**Comment by awvwgk** [comment]
I created the mapping from `InputVersion` to `ParserVersion` by looking up the respective parameters in the source at the release tags, as I was not able to find a place where this was documented. Having a list in the manual would be an improvement.
