### ISSUE TITLE
Many-Body Dispersion Implementation

### ISSUE THREAD

**Issue by shaychaudhuri** [dftbplus/dftbplus#622]
Hi,

I've been getting some errors using the many-body dispersion correction in the new 20.1 release of DFTB+. In the previous 19.1 release, I successfully managed to implement MBD using:
`Dispersion = MBD{
      NOmegaGrid = 15
      Beta = 0.95
      KGrid = 1 1 1
   }`
within the `Hamiltonian{}` block of `dftb_in.hsd` (provided '`git checkout mbd`' was done when building DFTB+. I believe MBD was merged into the main branch of the code for the new release, but when I attempt to use `MBD{}`, I get the following error: 
"`ERROR!
-> Invalid dispersion model name.
Path: dftbplusinput/Hamiltonian/DFTB/Dispersion`".

The DFTB+ manual doesn't explain how to correctly implement MBD (with the only available `Dispersion` options being `LennardJones`, `SlaterKirkwood`, `DftD3` and `DftD4`). Has the implementation of MBD changed with the new 20.1 release and if so, what is it (and can the manual be updated to include this?), or is there a new branch I need to checkout in order to include MBD in the DFTB+ build if it is not in the main branch currently? 

Many thanks,

Shay

**Comment by awvwgk** [comment]
MBD will be part of the next DFTB+ release, it is not yet available in the 20.1 release and therefore also not documented in the manual of the 20.1 release.

You can still build the latest version from source and enable it in the CMake configuration step by adding `-DWITH_MBD=ON`.

**Comment by shaychaudhuri** [comment]
Hi,

I just tried enabling MBD in the CMake configuration step but I get the following message:
"`CMake Warning: Manually-specified variables were not used by the project: WITH_MBD`" (though the rest of the build is fine)

Regards, Shay

**Comment by awvwgk** [comment]
Cannot confirm, works fine for me. Which commit are you trying to build?

**Comment by shaychaudhuri** [comment]
Ah yes, I was building from the `aradi` repository, all working now! Thanks for all the help!
