### ISSUE TITLE
Is reduced charges proper to check convergence for SCC part?

### ISSUE THREAD

**Issue by inseonglee** [dftbplus/dftbplus#626]
**Describe the bug**

When we run SCC calculations (especially, REKS), there is a case that the program shows successful convergence, but large energy difference.

**To Reproduce**

1. I attached dftb_in.hsd, eigenvec.bin-guess, log files.

2. github:inseonglee/reksReadMO branch (commit: 68d31da) based on 20.1, see PR: #625

3. output (energy and charge difference) -> too large
#iter    energy    diff    X_a    SccErrorQ
13       -4.7829699439      -0.0000402577     0.999998    0.00011780
14       -4.7829959950      -0.0000260512     0.999998    0.00004686
15       -4.7830130020      -0.0000170070     0.999998    0.00000033
converged!

orbital population (qOutput for C atom) -> too large
#iter  s   p1   p2   p3
13      1.27635663     0.96103924     1.00000000     0.93349605
14      1.27652123     0.96079549     1.00000000     0.93362206
15      1.27663061     0.96055601     1.00000000     0.93375250

atomic population (qOutRed for C atom) -> fortunately too small
13      4.17089192
14      4.17093879
15      4.17093912

**Expected behaviour**

For correct convergence, it shows small energy difference as well as small charge difference. To obtain this, it would be better to use orbital populations (not atomic population) as a convergence criterion. Then, the SccErrorQ would become ~0.00024, not 0.00000033.

In 2421 and 2444 lines in log file, it shows small difference of orbital and atomic populations when it shows correct convergence. (del_q ~= 0.00000092, del_q_l ~= 0.00000158)

**Additional context**

This example shows optimization of ethylene with use of eigenvec.bin-guess file as initial guess in REKS calculations. It shows a wrong convergence (small SccErrorQ, but large energy difference) for Geometry step: 2. In 2896 - 2934 line, the result shows large energe difference of PPS and OSS states as well as orbital populations. (del_E ~= 0.000017 H, del_q_l ~= 0.00024 e)

Despite of large difference of orbital populations for s, p1, p3 orbitals of C atom (qOutput), fortunately it shows small difference of atomic populations for C atom (qOutRed).

[scc_bug.tar.gz](https://github.com/dftbplus/dftbplus/files/5094984/scc_bug.tar.gz)

**Comment by inseonglee** [comment]
I just try to change the convergence criterion from `qDiffRed` to qDiff = qOutput - qInput`. From this test result, it shows normal convergence for every geometry step. So I think the orbital populations rather than atomic populations would be better convergence criterion for charges.

**Comment by bhourahine** [comment]
That depends on the hamitonian, but for REKS I think you are correct.

For conventional SCC DFTB, the input potential is invariant with respect to transfer of electrons within shells with the same Hubbard U value, so charge based mixing does not distinguish between configurations. Aufbauer filling should produce the lowest energy case for that potential (at least for V representable cases with fractional occupations, but as far as I'm aware this hasn't been formally proved). There were some brief attempts to test removing this symetrization in the SCC cycle, but nothing systematic.

For orbital or density matrix dependent functionals this isn't the case, and changes in the density matrix need to monitored. For REKS, if I understand correctly, you effectively have a non-local potential present by separating the solutions into the different categories of microstates. So again measuring convergence from the overall shell populations is not correct.

**Comment by inseonglee** [comment]
@bhourahine Thanks for detailed explanation. You mentioned that the energy of conventional SCC-DFTB do not depend on transfer of electrons within shells with the same Hubbard U value. Then, for the mio parameters, we can set `ShellResolvedScc = Yes` so that the different Hubbard U values are assigned to shells. Or, for 3rd order SCC, we can consider the derivative of Hubbard parameters so that the transfer of electrons can be considered. In these cases, the reduced charges can be used for a convergence criterion?

At the moment, I will modify the convergence check routine for REKS case.

**Comment by inseonglee** [comment]
@bhourahine Now changed to orbital populations for convergence check in REKS. Please see the commit 13049c2.
