### ISSUE TITLE
Output no longer contains Ewald alpha parameter 

### ISSUE THREAD

**Issue by MaximeVdB** [dftbplus/dftbplus#641]
**Describe the bug**
The DFTB+ manuals (v17.1 through v20.1) say that the Ewald alpha parameter is written to the (standard) output (for SCC = Yes and Periodic = Yes). However, this seems only true for the 17.1 release, not the more recent ones.

**To Reproduce**
1. Run DFTB+ >= v18 on any periodic structure, with SCC
2. Search in vain for the Ewald parameter in the standard output (or any of the other output files)

Am I missing something? Looks like this section of the manual simply wasn't updated.
If possible, I would prefer DFTB+ to again print out the Ewald parameter :)

**Comment by awvwgk** [comment]
Doing some quick history check on git blame reveals that it was commented out in 9f5923f646b8ec932ce01602694c20e9c4b9caec. After searching the codebase it seems like is indeed no way to retrieve the Ewald parameter right now.
