### ISSUE TITLE
Output info significanly depends on the machine

### ISSUE THREAD

**Issue by Dnasiul** [dftbplus/dftbplus#645]
[files.zip](https://github.com/dftbplus/dftbplus/files/5300513/files.zip)

Hello DFTB+ developers,

**Describe the bug**
Same input script generates different output in the "DFTB+ running times" section when used in different machines. Specifically:

- Machine 1 (12 cores; ubuntu):
```
--------------------------------------------------------------------------------
DFTB+ running times                          cpu [s]             wall clock [s]
--------------------------------------------------------------------------------
Pre-SCC initialisation                 +     0.01  ( 66.9%)      0.00  ( 33.3%)
--------------------------------------------------------------------------------
Missing                                +     0.01  ( 33.1%)      0.00  ( 66.7%)
Total                                  =     0.02  (100.0%)      0.00  (100.0%)
--------------------------------------------------------------------------------
```
- Machine 2 (16 cores; centos)
```
--------------------------------------------------------------------------------
DFTB+ running times                          cpu [s]             wall clock [s]
--------------------------------------------------------------------------------
Global initialisation                  +     0.00  (  0.3%)      0.05  ( 46.0%)
Pre-SCC initialisation                 +     0.04  ( 16.3%)      0.00  (  3.0%)
SCC                                    +     0.13  ( 55.6%)      0.03  ( 25.0%)
Post-SCC processing                    +     0.00  (  0.1%)      0.01  ( 13.0%)
Post-geometry optimisation             +     0.07  ( 27.7%)      0.01  ( 13.0%)
--------------------------------------------------------------------------------
Missing                                +     0.00  (  0.0%)      0.00  (  0.0%)
Total                                  =     0.24  (100.0%)      0.10  (100.0%)
--------------------------------------------------------------------------------
```

In addition, (probably related), computing times for longer runs are shorter (3 times) in the ubuntu machine (having less cores) than in the centos one (having more cores).

**To Reproduce**

Attached input files and full output files.

**Expected behaviour**

I would expect the same kind of output (not exactly the same numeric values) on both machines, and shorter computing times in the larger machine.

**Additional context**

Thanks in advance for taking a look at this.

**Comment by aradi** [comment]
Thanks for reporting. I think, the reason lies in the speed. In order not to clutter the output with unnecessary `0.00` entries, we do not print those timings where both, cpu and wall clock times are below 1e-2. If you make longer runs, you should see more entries.

**Comment by aradi** [comment]
Just as a further note, if it is essential for your worklfow, one could easily make the suppression of the 0.00 entries optional. Let us know, if it were relevant for your research by opening an issue requesting that feature.

In the mean time, I'll close this issue.

**Comment by Dnasiul** [comment]
Thanks!
