### ISSUE TITLE
LBFGS issues

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#664]
The LBFGS in DFTB+ currently has two calls to error:

https://github.com/dftbplus/dftbplus/blob/94698a5cbe833765c89eed2d4c800ac056e7aad8/prog/dftb%2B/lib_geoopt/lbfgs.F90#L363-L366

https://github.com/dftbplus/dftbplus/blob/94698a5cbe833765c89eed2d4c800ac056e7aad8/prog/dftb%2B/lib_geoopt/lbfgs.F90#L368-L371

At least the former is frequently encountered when using the LBFGS minimizer in DFTB+, the reason to perform this check is probably to not run into numerical difficulties with the two divisions performed in the LBFGS algorithms.

The first one happens here and is already secured against dividing by zero, which makes the first check unnecessary:
https://github.com/dftbplus/dftbplus/blob/94698a5cbe833765c89eed2d4c800ac056e7aad8/prog/dftb%2B/lib_geoopt/lbfgs.F90#L380-L384

The second division happens for the diagonal elements at

https://github.com/dftbplus/dftbplus/blob/94698a5cbe833765c89eed2d4c800ac056e7aad8/prog/dftb%2B/lib_geoopt/lbfgs.F90#L395-L396

And could easily catch divide by zero errors the same way as before without raising an error.

The simplest “fix” would be to remove the two calls to error and maybe secure the evaluation of the diagonal elements against division by zero. The main issue with this kind of fix would be a potential instability introduced into the LBFGS which leads to failing the optimization by distorting the structure.

@bhourahine Any opinion on this?

**Comment by bhourahine** [comment]
I tried something  like that in the past, but the solver then stops making progress even when not calling the errors. Something like this [dftb_in.hsd](https://gist.github.com/bhourahine/fff9bc408db20a942870368613ebdeff) demonstrates it.

**Comment by awvwgk** [comment]
After a bit of searching, the problem is not in the LBFGS but in the line search algorithm. There can occur a path where

https://github.com/dftbplus/dftbplus/blob/94698a5cbe833765c89eed2d4c800ac056e7aad8/prog/dftb%2B/lib_geoopt/lbfgs.F90#L834-L837

is invoked but `alphaLo` is still at its initial value of `0` without ever having been written, too.
`alphaNew` is used in

https://github.com/dftbplus/dftbplus/blob/94698a5cbe833765c89eed2d4c800ac056e7aad8/prog/dftb%2B/lib_geoopt/lbfgs.F90#L839-L840

to calculate the new positions, which will be exactly the old positions than. The line search zoom routine terminated (successfully) and returns to the LBFGS which fails to obtain the new search direction from the `xNew` input.

I would presume there is an algorithmic error present, since this situation should never occur.

**Comment by bhourahine** [comment]
Yes,  the line search is broken from original implementation. As #670 partly mitigates this, shall we close this or leave it open until the line search is fixed?
