### ISSUE TITLE
DFTB+ 20.1 memory leakage

### ISSUE THREAD

**Issue by naohjohn** [dftbplus/dftbplus#675]
**Describe the bug**
From the mail-list. The memory usage increases when running MD steps and finally use up all the memory.

**To Reproduce**

1. minimal example of how to trigger the bug (include self-contained input file)
I use the example of H2 cluster.
[dftb_in.hsd.txt](https://github.com/dftbplus/dftbplus/files/5535235/dftb_in.hsd.txt)
[geo_end.gen.txt](https://github.com/dftbplus/dftbplus/files/5535236/geo_end.gen.txt)
[H-H.skf.txt](https://github.com/dftbplus/dftbplus/files/5535247/H-H.skf.txt)

2. which version of DFTB+ is used (downloaded, conda-forge or build from source),
   if built from source include the git commit, the compiler and used libraries
DFTB+ 20.1 compiled with intel MPI 2019.6.166 and intel MKL 2020.0.166

3. output showing the error
I track the memory usage of dftb+ during MD steps every minute and find RES and VIRT are increasing steadily. The memory usage for the example is very small, so it won't use up soon, but the trend is abnormal. 
[memory.txt](https://github.com/dftbplus/dftbplus/files/5535340/memory.txt)

Thank you!

**Comment by aradi** [comment]
Thanks for reporting the issue. I can indeed reproduce the case on our development server. My current guess is, that this is a compiler problem. Using Intel 19 + MKL (serial mode) I obtained increasing memory usage. Using GNU 10 + MKL the memory usage is absolutely constant. Could you eventually test it with a non-intel compiler?

**Comment by aradi** [comment]
Having stared at the problem somewhat longer: I have found a workaround for this *compiler bug*. If I remove the compiler option  `-heap-arrays 10` in `sys/intel.cmake` from the variable `Fortran_FLAGS_RELEASE`, I obtain an executable with a constant memory footprint. @naohjohn Could you do me a favour and test this workaround on your system as well? If this solves the issues, we woudl remove that compiler switch in the upcomming fix release of DFTB+.

**Comment by naohjohn** [comment]
Thank you for your reply. I test the workaround on my system and the memory is constant now. That's very helpful.

**Comment by aradi** [comment]
Perfect, thanks for checking. I have removed that option from the default options in 3e1ffca. It will be part of the patch release we are going to release today.
