### ISSUE TITLE
lattice derivs and pressure =0 in detailed.out

### ISSUE THREAD

**Issue by hahuber** [dftbplus/dftbplus#679]
**Describe the bug**
 Output of lattice derivs and pressure in detailed.out is 0 in version 20.2 but not in 20.1. 

**To Reproduce**
Run dftb_in.hsd in attached folder with DFTB+ V20.1 look into detailed.out
Run dftb_in.hsd in attached folder with DFTB+ V20.2 look into detailed.out

1. minimal example of how to trigger the bug: see above
2. "Bug" occured with DFTB+ V20.2 from conda and from executable download
3. output shows lattice derivs and pressure 0

All input and output files required to confirm your report. --> attached folder

**Expected behaviour**
If it is a bug and not a user error to look into it/fixing it

**Additional context**
If there are further questions you can ask me via email
[temp_dftbplus_20.2.zip](https://github.com/dftbplus/dftbplus/files/5590468/temp_dftbplus_20.2.zip)

**Comment by aradi** [comment]
@hahuber Thanks a lot for reporting this. It has been fixed in #684 . We'll soon issue a patch release for 20.2 containing this fix.
