### ISSUE TITLE
New release 20.2: TSsurf dispersion energy is zero

### ISSUE THREAD

**Issue by werkova** [dftbplus/dftbplus#681]
**Describe the bug**
I downloaded the new release 20.2 as executable and tried to use a TSsurf dispersion correction for TCNE on Cu(111). For this system the dispersion energy should be around -64.4611 eV (obtained by earlier development version), but now it is -0.0000 eV. I also didn't receive any error messages.

**To Reproduce**

1. Use DFTB+ 20.2 executable
2. Use TS dispersion correction (check uploaded data)
3. Check dispersion energy in detailed.out

Both calculation folders (20.2 and devel_version) and the SK-folder (parameters/new) you can find attached.
[bug_report.zip](https://github.com/dftbplus/dftbplus/files/5597559/bug_report.zip)

**Comment by aradi** [comment]
@werkova Thanks for the bug report, I am going to have a look at this.

**Comment by aradi** [comment]
@werkova The TS energy is not zero, but extremely low (~1e-14). It is hard to judge, whether it is a bug or not. The original version of the code you have used is very-very ancient, it was using a completely different implementation of MBD, not libMBD. However, we can ask libMBD's author, whether he thinks the new values make sense...

@jhrmnn Would it be possible that you have a look at this system? As far as I can see, we transmit reasonable CPAs (0.7-0.8) to libMBD, but receive an energy of about 1e-14 as result for TS and TSsurf. If I change to MBD, the calculated dispersoin energy is 1e-4 Ha, so it is still very small. Is it reasonable in your opinion for the users system?

**Comment by werkova** [comment]
@aradi Thanks a lot for looking into this. Yes, this is an ancient code. This reference calculation with the different implementation of MBD was done in 2017 by a former college. In the meantime, it seems plausible to me that this is not a bug of libMBD as I also checked corresponding DFT calculations with a vdW contribution similar to the one obtained by libMBD.

**Comment by aradi** [comment]
OK, I'll then close this issue.
