### ISSUE TITLE
Intel toolchain forced to use of -standard-semantics or -assume realloc_lhs

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#701]
**Describe the bug**

Currently the toolchain file forces to use `-standard-semantics` or `-assume realloc-lhs` with Intel compilers. Since `-standard-semnatics` makes the latest version of the Intel oneAPI classic compilers more shaky it would be preferable to at least be able to disable this feature for local builds.

A custom configuration check requires either `-standard-semantics` or `-assume realloc_lhs` to be set. The `ifort` man page says `-assume realloc_lhs` is enabled by default, so there shouldn't be an enforcement to have a redundant `-assume realloc_lhs` specified just to avoid using the `-standard-semantics` argument.

**Comment by aradi** [comment]
That has been solved, as we check for those flags only for Intel versions < 18.0.
