### ISSUE TITLE
dftbplus 20.2.1 - Excited States and Dispersion D3

### ISSUE THREAD

**Issue by t-s-hofer** [dftbplus/dftbplus#703]
Dear Developers,

I really enjoy employing dftb+ in my research and have obtained a number of brilliant results in the past. However, when testing the new version dftb-20.2.1 i have encountered the following obstacles:

1) When using dftb+ 20.2.1 to calculate excited states via casida using the 3ob-set (i.e. third order SCC DFTB), i receive the error message:

"-> Third order currently incompatible with excited state"

However, this feature worked so well in the previous version (19.1). Was there any specific reason to turn this off in the new release?

2) Similarly, in dftb+ 20.2.1 D3 dispersion correction was turned off again, and jobs including this setting yield the error:

"-> Program had been compiled without DFTD3 support"

I learned that this might be an issue related to licensing and distribution, however as the inclusion of D3 dispersion correction follows this pattern I am not sure this is the actual problem:

dftb+ version 17.1 with D3 support
dftb+ version 18.1 with D3 support
dftb+ version 18.2 without D3 support
dftb+ version 19.1  with D3 support
dftb+ version 20.2.1 without D3 support

While D4-corrections are active in the newest version 20.2.1, which can be used as alternative, it is not possible to remain consistent and back-compatible to previous works based on D3.

If possible, kindly provide executable with these features turned on again. (Compiling the code with those features myself would be an option of course, but I have to admit that this task proved to be far to challenging for me).

Many thanks and best wishes,
Thomas Hofer

**Comment by awvwgk** [comment]
From my understanding this is a license issue, DFTB+ is distributed under LGPL-3.0 (or later) while the DFTD3 library used is licensed as GPL-1.0 (or later). Therefore, the policy was to exclude DFT-D3 from the release as far as I understood, from the version history this seems to be enforced rather inconsistently.

DFTD4 doesn't have this issue because it was contributed under the LGPL-3.0 (or later) to DFTB+. There are compatibly licensed variants of the DFTD3 library available, which could be used in DFTB+ to allow distribution without license concerns (see https://github.com/ehermes/ased3 or https://github.com/awvwgk/simple-dftd3).

I contributed parts of my DFTD3 reimplementation already to DFTB+ to allow usage of DFTD3 in the release version, see

https://github.com/dftbplus/dftbplus/blob/06409101c9f1a8e30817c729fb2823455641a6fc/test/prog/dftb%2B/dispersion/2H2O_sdftd3/dftb_in.hsd#L36-L45

**Comment by t-s-hofer** [comment]
Thank you awvwgk for the prompt response. Your answer makes this point very clear and will try using the SimpleDFTD3 setting in the future.

I hope there exists an equally simple solution to enable the calculation of excited states via casia in combination with Third Order DFTB.

**Comment by t-s-hofer** [comment]
Hello,

I am re-opening this for a related question -- similar as for the TD-DFTB case via casida, also the new freature Electron Dynamics does not seem to support 3rd Order (ThirdOrderFull = Yes) as of v20.2.1.

On the other, when having a look at the ElectronDynamics example from the recipies-page (i'm refering to the downloaded example files), the input employs the 3ob set without 3rd order (i.e. no Hubbard derivs). As far as I understood the DFTB philosophy, parameters are "full packages" which do not permit to run a calculation without all ingredients. Please correct me, if I'm wrong, but when running 3ob considering only 2nd order gives some questionable results when carrying out energy minimisations of random molecules and solid-state systems (when using the 3rd order result as reference). I assume excitations are even more sensitive than the minimum geometries.

1) So is the example provide in the recipies just some basic outline how to get this module running using the bare minimum of setting? This example might be misleading to newcomers to DFTB.

2) In order to use 3rd Order in casida and Electron Dynamics of v20.2.1 I have to compile the code myself using the correct flags? The possibility to run casida / Electron Dynamcis in implicit solvent has enormeous(!) potential - the UV/VIS spectra we have obtained for some systems using dftbplus/3ob are nothing short but SPECTACULAR when compared to old-school DFT.

Thanks for any feedback!

**Comment by aradi** [comment]
Dear @t-s-hofer , thanks a lot for your encouraging words. I am happy to hear, that DFTB+ is helpful for your research.

As for the D3, as @awvwgk already mentioned,  just use the SimpleD3, which is an implementation within DFTB+, so it will be always included. (The reason for the original D3 appearing and disappearing in the official binaries lies in discussions about the license incompatibililty between DFTB+ and the d3-library... Sorry for not having been very consistent on this.)

As for excited states: The Casida formalism is currently based on the 2nd order DFTB formalism. In earlier versions, we did not implement checks for preventing setting Casida and 3rd order together. As a result, ground state Hamiltonian contained the 3rd order term, but the excitations only the 2nd order one. We now have the appropriate check in place and stop the code to avoid inconsistency.

On the other hand, the 3rd order corrections in the excitacions are expected to be very minor, so it would be still a reasonable approximation to make such "inconsistent" calculations. Therefore, we plan to introduce a new keyword, which would allow for such a combination. But the user would be then aware, that it is only an approximation.

In the mean time, if you wish, I could create a binary based on 20.2.1 for you, which simply disables the check again as in the good old times. :wink:

**Comment by t-s-hofer** [comment]
Dear Balint,

Thank you for your detailed reply on the issues highlighted earlier and
apologies for this late reply. I did not recognize this email of yours as
it was "hidden" under the response of Sebastian Ehlert. I simply did not
realize that there was a second email from you.

Also many thanks for your offer to compile a special version for our
purposes, but in the mean time a gifted student of mine was able to compile
the code without trouble (apparently, the change to cmake a few versions
back makes the compilation much easier compared to those days when I
attempted this). My student even found this switch and disabled it in the
source code. I am aware that this is quite dangerous but the results match
our previous data (and thanks to your explanation, we also have detailed
insider information).

Sorry also for highlighting the issue regarding the D3 corrections on the
forum ... maybe this was not the best location to ask this question because
of the licensing issue. It now is clear to me, so if you would prefer to
remove my question from the forum I will perfectly understand.

During our experimentation with the new version including D4 corrections,
we encountered a system in which dftb+ terminates giving segmentation fault
before the first iteration when running with dftbplus v20.2.1 (our in-house
vesion). This job runs fine if dispersion is deactivated entirely or D3
disperision is used in v19.1. I have attached the gen- and input files. I
hope this information is useful for you and your team.

Best wishes,
Thomas




Am Mi., 10. Feb. 2021 um 21:49 Uhr schrieb Bálint Aradi <
***@***.***>:

**Comment by awvwgk** [comment]
> During our experimentation with the new version including D4 corrections, we encountered a system in which dftb+ terminates giving segmentation fault before the first iteration when running with dftbplus v20.2.1 (our in-house vesion). This job runs fine if dispersion is deactivated entirely or D3 disperision is used in v19.1. I have attached the gen- and input files. I hope this information is useful for you and your team.

Unfortunately, attachments get lost on email replies to issue. If this was an OpenMP parallel run, I have an idea why D4 crashes, but I'd like to confirm it before I put together a patch.

**Comment by t-s-hofer** [comment]
Dear Sebastian,

I am re-sending the files again. I hope it works this time.

Best wishes,
Thomas

Am Mo., 22. März 2021 um 10:22 Uhr schrieb Sebastian Ehlert <
***@***.***>:

**Comment by omidshy** [comment]
> If this was an OpenMP parallel run, I have an idea why D4 crashes, but I'd like to confirm it before I put together a patch.

I've also encountered the mentioned problem, while the MPI parallel run of the DFTB+ (20.2.1) using D4 corrections works fine, the OpenMP parallel run is resulting in termination with a segmentation fault.

**Comment by awvwgk** [comment]
You can actually fix this issue by increasing the system stack size (`ulimit -s unlimited`) and setting the OpenMP stack (`export OMP_STACKSIZE=1G`) without modifying DFTB+.
