### ISSUE TITLE
Build fails for OMP dis- and MPI enabled

### ISSUE THREAD

**Issue by vanderhe** [dftbplus/dftbplus#711]
**Describe the bug**
Build fails for OMP dis- and MPI enabled

**To Reproduce (on dpdevel)**
module load env_dftb+/gcc9-openmpi
git clone git@github.com:dftbplus/dftbplus.git dftbplus
cd dftbplus
FC=gfortran CC=gcc cmake -C /home/buildbot/testers/dftbplus/settings/gnu-9/arch.cmake -DWITH_OMP=0 -DWITH_MPI=1 -B _build
cmake --build _build -- -j

**Error**
/home/user/dftbplus/prog/dftb+/lib_common/mpienv.F90:15:
error: exception occured when evaluating 'WITH_TRANSPORT' [FyppFatalError]
error: name 'WITH_TRANSPORT' is not defined [NameError]

**Comment by aradi** [comment]
Actually, it is only `WITH_MPI` in combination with `WITH_TRANSPORT`. Had been fixed in #712, where also the resulting circular reference was fixed.
