### ISSUE TITLE
Compile time regression

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#738]
**Describe the bug**

Compile time with `ifort` has significantly increased due to https://github.com/dftbplus/dftbplus/pull/722. Since the dftd3param was added in this way to remove the overhead from `ifort` compiling the old copyc6 routines I consider this a regression.

**To Reproduce**

Compile DFTB+ at c082c6770d1c1dfce8fc62fa1431a9cc489a3624 (dftd3param takes ~30 sec) and 3f52e21edb3aa9adb2f1ee612306ef4a96804a45 (dftd3param takes >10 min) with `ifort`.

**Expected behaviour**

Don't take >10 min to compile a file that could be compiled in 30 sec.

**Comment by aradi** [comment]
Actually, I think we can even decrease the compilation time with respect of the original version considerably as proposed in #744. (Don't ask me, why ifort tries to optimize trivial `reshape`s for hours...)
