### ISSUE TITLE
Resource temporarily unavailable in D4 calculations

### ISSUE THREAD

**Issue by dveclani** [dftbplus/dftbplus#826]
Dear users,

I am Daniele Veclani and I'm DFTB+ user. I want to use DFTB+ to perfom some calculation with DFT-D4. I am able to use a D4 dispertion correction but during calculation I obtained this error:

"libgomp: Thread creation failed: Resource temporarily unavailable."

I noticed that if I increase the number of k points the error appears more often. In 
[File.zip](https://github.com/dftbplus/dftbplus/files/6898695/File.zip)
attached input file, geometry, error file and calculation launch sript 

If anyone could offer some information about this error, or an example of an input file which can be used to calculate with DFTB-D4, I’ll be very appreciated.

Best regerds,
Daniele Veclani

**Comment by awvwgk** [comment]
Should be fixed by https://github.com/dftbplus/dftbplus/pull/901
