### ISSUE TITLE
Python API segfault

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#834]
**Describe the bug**

API breaking changes and Python API segfaults due to [50158a5](https://github.com/dftbplus/dftbplus/pull/686/commits/50158a54f5c075b9bd109d7575ead7ca71ffd93c)

**To Reproduce**
Appears for current Python regression tests as a segfault

**Expected behaviour**

Tests run as expected.

**Additional context**

Previously discussed, but should be addressed. Also, shows CI regression should be running this.

**Comment by awvwgk** [comment]
Is there something we want to do about this before we release a new version?

**Comment by aradi** [comment]
Yes, I'd like to revert the interface to its original form without the `TDftbPlusAtomList` argument. I've just contacted @tomaskubar to discuss, how we could provide a similar functionality (if needed) without having to specify an optional argument in the `dftbp_process_input()` call.
