### ISSUE TITLE
Lattice optimization is not working with xTB Hamiltonian

### ISSUE THREAD

**Issue by steinmig** [dftbplus/dftbplus#836]
**Describe the bug**
If the lattice is optimized with the xTB Hamiltonian, the system shrinks in every optimization step, while the lattice force norm keeps increasing (possibly a sign mistake?). The structure is eventually shrunken together so much that additionally something else breaks and segfaults.

**To Reproduce**
Input and output files for a Au crystal with DFTB (everything works as expected) and with GFN1 are attached.
I observed the same behavior for other systems. The input structure is taken from the Materialsproject database (2x2x2 supercell of the unit cell).

DFTB+ version:
I pulled the current master branch (060977a32a5f1d9b399d34977ffbc6594d06e001) and compiled with included tblite and gfortran/gcc version 8.3

**Expected behaviour**
A normal optimization according to the lattice force

**Additional context**
tagging @awvwgk as author of tblite

[dftb_in.txt](https://github.com/dftbplus/dftbplus/files/6961860/dftb_in.txt)
[dftb_out.txt](https://github.com/dftbplus/dftbplus/files/6961861/dftb_out.txt)
[xtb_in.txt](https://github.com/dftbplus/dftbplus/files/6961863/xtb_in.txt)
[xtb_out.txt](https://github.com/dftbplus/dftbplus/files/6961864/xtb_out.txt)

**Comment by awvwgk** [comment]
I'll have a look, let's hope it is just another sign convention I missed when implementing stuff in DFTB+.

**Comment by awvwgk** [comment]
`tblite` calculates the gradient (∂E/∂R) and the strain derivatives (∂E/∂ε = V·σ), and transfers this quantities to DFTB+, which requests gradient and stress tensor (σ = 1/V·∂E/∂ε ?). The sign convention I'm using for the stress tensor can be found [here](https://www.sciencedirect.com/science/article/abs/pii/S0010465515000090) ([pdf](https://th.fhi-berlin.mpg.de/site/uploads/Publications/paper_stress_tensor_20150113.pdf)). At least for the gradient the sign convention is changed in the output to forces (F = –∂E/∂R) for DFTB+, similarly I expected the lattice forces to be generated from the stress tensor including the sign change there. Of course I checked a few molecular crystals with xTB but didn't notice any anomalies there.

Unless the stress tensor in DFTB+ is instead defined differently (σ' = –1/V·∂E/∂ε), maybe @aradi @bhourahine can clarify this for me.

**Comment by bhourahine** [comment]
Yes, simple sign error. Using the dftbplus3/utils/numcheck/calcderivs script on the gfn1_succinic regression example:
Lattice derivatives by finite differences:
       2.174757349235E-02       2.090576959148E-07       3.783590853191E-04
       4.233794345325E-07       2.473842245067E-02      -1.020246676430E-05
      -1.090952170006E-04      -1.746552968362E-05       1.892358472363E-02
Reference lattice derivatives:
      -2.174821862518E-02      -2.036614574058E-07      -3.780942233967E-04
      -4.194745016909E-07      -2.473871804924E-02       1.020502793915E-05
       1.093918873139E-04       1.746930929062E-05      -1.892408950177E-02

**Comment by awvwgk** [comment]
Thanks for checking, I'll fix it for xTB and add a sentence to the manual.
