### ISSUE TITLE
Output interaction energy between external charge and system

### ISSUE THREAD

**Issue by wuchiz** [dftbplus/dftbplus#842]
How can I output the interaction energy between external charge and system? And how can I decompose the corresponding force?

**Comment by aradi** [comment]
@wuchiz We add the energies and the forces to the SCC-contribution (as the external charges interact with the scc charges). See [scc.F90:605](https://github.com/dftbplus/dftbplus/blob/9269709cf6d223e610d41287d28df6e430fa0c11/src/dftbp/dftb/scc.F90#L605). You could hack things in there, if you wanted to visualize it. Similar for the force in [scc.F90:726](https://github.com/dftbplus/dftbplus/blob/9269709cf6d223e610d41287d28df6e430fa0c11/src/dftbp/dftb/scc.F90#L726).

**Comment by wuchiz** [comment]
@aradi thanks! I have another question. If I only know the external electric field applied on each QM atom, how can I use dftbplus to calculation the energy and force?
