### ISSUE TITLE
  How to deal with this problem When running this command  as shown below？

### ISSUE THREAD

**Issue by e-724** [dftbplus/dftbplus#845]
CalculationFailed: Calculator "dftb" failed with command "dftb+ > dftb.out" failed in /root/ZrO with error code 127

```python
import numpy as np
import matplotlib.pylab as plt

from quippy.potential import Potential

from ase import Atoms, units,Atom
from ase.io import write,read

from ase.calculators.dftb import Dftb


atoms=read("ZrO2_monoclinic.vasp")
calculator_NVT = Dftb(atoms=atoms,
                      Hamiltonian_MaxAngularMomentum_='',
                      Hamiltonian_MaxAngularMomentum_Zr='d',
                      Hamiltonian_MaxAngularMomentum_O='p',
                      Driver_='VelocityVerlet',
                      Driver_MDRestartFrequency=5,
                      Driver_Steps=500,
                      Driver_KeepStationary='Yes',
                      Driver_TimeStep=8.26,
                      Driver_Thermostat_='Berendsen',
                      Driver_Thermostat_Temperature=0.00339845142,  # 800 degC
                      Driver_Thermostat_CouplingStrength=0.01)
atoms.set_calculator(calculator_NVT)

isolated_Zr = Atoms('Zr', cell=[20,20,20])
isolated_Zr.calc=calculator_NVT

isolated_O = Atoms('O', cell=[20,20,20])
isolated_O.calc=calculator_NVT

print('e0_Zr:',isolated_Zr.get_potential_energy())
print('e0_O:',isolated_O.get_potential_energy())
```

**Comment by awvwgk** [comment]
Can you post the input produced by ASE for DFTB+ (`dftb_in.hsd`) and the output produced by the DFTB+ command (`dftb.out`)?

**Comment by e-724** [comment]
dftb_in.hsd：Geometry = GenFormat { 
&nbsp;&nbsp;&nbsp; <<< "geo_end.gen" 
} 
&nbsp;
Driver = VelocityVerlet{ 
&nbsp;&nbsp; KeepStationary = Yes 
&nbsp;&nbsp; MDRestartFrequency = 5 
&nbsp;&nbsp; Steps = 500 
&nbsp;&nbsp; Thermostat = Berendsen{ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; CouplingStrength = 0.01 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Temperature = 0.00339845142 
&nbsp;&nbsp; } 
&nbsp;&nbsp; TimeStep = 8.26 
&nbsp;&nbsp; } 
Hamiltonian = DFTB{ 
&nbsp;&nbsp; MaxAngularMomentum = { 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; O = p 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Zr = d 
&nbsp;&nbsp; } 
&nbsp;&nbsp; SlaterKosterFiles = Type2FileNames{ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Prefix = ./ 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Separator = "-" 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Suffix = ".skf" 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; } 
&nbsp;&nbsp; } 
Options { 
&nbsp;&nbsp; WriteResultsTag = Yes 
} 
ParserOptions { 
&nbsp;&nbsp; IgnoreUnprocessedNodes = Yes &nbsp;
} 

I'm sorry that dftb.out is empty.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dftbplus/dftbplus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dftbplus/dftbplus]   How to deal with this problem When running this command  as shown below？ (#845)





 
Can you post the input produced by ASE for DFTB+ (dftb_in.hsd) and the output produced by the DFTB+ command (dftb.out)?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by e-724** [comment]
Can you give me some simple examples of DFTB molecular dynamics calculations written in Python？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dftbplus/dftbplus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dftbplus/dftbplus]   How to deal with this problem When running this command  as shown below？ (#845)





 
Can you post the input produced by ASE for DFTB+ (dftb_in.hsd) and the output produced by the DFTB+ command (dftb.out)?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aradi** [comment]
Are you sure, that DFTB+ is found and can be started? Usually, DFTB+ prints a header immediately after start (before reading any input). If even that is not present, it may be that it was not even started.

When you just change to the directory with the generated input and start ``dftb+`` from the shell command line, what happens there?
