### ISSUE TITLE
Debug code: Hellmann-Feynman dipole moment

### ISSUE THREAD

**Issue by awvwgk** [dftbplus/dftbplus#863]
**Describe the bug**

When compiling in debug mode an additional evaluation of the dipole moment is done based on the potential rather than on the charges:

https://github.com/dftbplus/dftbplus/blob/9e4ff1ef97239a41d4152832995d2837df47497c/src/dftbp/dftbplus/main.F90#L4649-L4659

The actual dipole moment for xTB will disagree with the Hellmann-Feynman dipole moment

**To Reproduce**

Print the dipole moment in parts for an xTB calculation, using only the charges, and the full dipole moment from charges and atomic dipole moments. The former will match with the Hellmann-Feynman dipole moment, while the latter should be the physically correct one:

https://github.com/dftbplus/dftbplus/blob/9e4ff1ef97239a41d4152832995d2837df47497c/src/dftbp/dftbplus/main.F90#L4576-L4589

**Expected behaviour**

The Hellmann-Feynman dipole moment must account for the dipole potential as well.

**Comment by bhourahine** [comment]
Original issue is now addressed by #1238
