### ISSUE TITLE
NaN / Infinity gradients and general question concerning gradients

### ISSUE THREAD

**Issue by steinmig** [dftbplus/dftbplus#871]
**Bug**
With the attached input file and the current master built with gcc-9.2, I get a converged SCF solution, but if I request forces, I get NaN / infinity values (possibly coming from tblite? @awvwgk )

**Additional question**
Both the manual and the dftb_pin.hsd file suggest, that gradients in DFTB+ are calculated with finite differences, but requesting gradients via `Analysis = {CalculateForces = Yes}` has a close to identical runtime compared to without forces, suggesting that the gradients are analytical. Does tblite automatically support analytic gradients and the option in DFTB+ is a misnomen?

[dftb_in.hsd.txt](https://github.com/dftbplus/dftbplus/files/7345401/dftb_in.hsd.txt)

**Comment by steinmig** [comment]
Still present with the latest version

**Comment by awvwgk** [comment]
There is a numerical issue in the evaluation of the DFT-D3 dispersion correction. I'm adding a patch for this with https://github.com/awvwgk/simple-dftd3/commit/ddc9044f4fc4ad96cd38267ccca8342068c637ab upstream.

**Comment by steinmig** [comment]
I just tested https://github.com/dftbplus/dftbplus/pull/891 and the issue still persists in case that helps

**Comment by awvwgk** [comment]
Fixed with new release of `s-dftd3` library (https://github.com/awvwgk/simple-dftd3/releases/tag/v0.5.0), DFTB+ might have to update its submodule to include the fix.
