### ISSUE TITLE
xlmf90 name collision with keyword

### ISSUE THREAD

**Issue by bhourahine** [dftbplus/dftbplus#905]
**Describe the bug**
xmlf90 defines an interface for char() which is already a language keyword.

**Comment by awvwgk** [comment]
Not really a bug, unless xmlf90's char interface accepts an integer.

**Comment by bhourahine** [comment]
The two argument form does, but yes probably more of an enhancement.

**Comment by awvwgk** [comment]
There is

https://github.com/dftbplus/dftbplus/blob/05b91b3dd779d96ee2495364b638f405c94237e1/external/xmlf90/strings.f90#L124-L130

and 

https://github.com/dftbplus/dftbplus/blob/05b91b3dd779d96ee2495364b638f405c94237e1/external/xmlf90/strings.f90#L137-L149

in the char interface

https://github.com/dftbplus/dftbplus/blob/05b91b3dd779d96ee2495364b638f405c94237e1/external/xmlf90/strings.f90#L32-L35

Both are uncritical for the intrinsic char as the interfaces do not collide: https://gcc.gnu.org/onlinedocs/gfortran/CHAR.html

From most string implementations and previous attempts to standardize string types, *i.e.* `iso_varying_string`, the name `char` for the procedure to convert to an intrinsic character variable seems like the default choice. The Fortran standard library is using the same convention as well.

**Comment by aradi** [comment]
The `char` interface *extends* the intrinsic definition, so the intrinsic one is still available. As long as we only use it with our derived type, there should be no shadowing problem.
```
module test
  implicit none

  type :: str
    character :: c = "!"
  end type str

  interface char
    module procedure char_str
  end interface

contains

  function char_str(this) result(c)
    type(str), intent(in) :: this
    character :: c
    c = this%c
  end function char_str

end module test


program testprog
  use test, only : str, char

  type(str) :: mystr

  print *, char(mystr)
  print *, char(42)  !<-- still works as supposed

end program testprog
```

**Comment by bhourahine** [comment]
Yes, its all legal Fortran. But as a pattern its more of a learning curve and cognitive overhead for new developers/less Fortran experienced developers (who need to know to recognise the extension of a keyword and potentially look up its interface to understand code where it is used).
