### ISSUE TITLE
dftb+ development version Compilation error

### ISSUE THREAD

**Issue by periasamy25** [dftbplus/dftbplus#92]
Compiling dftb+ development version, **make** completed successfully. But the following error occur, while execute the following command.
$ make test

make[2]: Entering directory `/opt/apps/dftbplus-master/_build/external/mpifx'
make[2]: /opt/apps/dftbplus-master/external/mpifx/origin/src/Makefile.lib: No such file or directory
make[2]: *** No rule to make target `/opt/apps/dftbplus-master/external/mpifx/origin/src/Makefile.lib'.  Stop.
make[2]: Leaving directory `/opt/apps/dftbplus-master/_build/external/mpifx'
make[1]: *** [libmpifx] Error 2
make[1]: Leaving directory `/opt/apps/dftbplus-master/_build/external/mpifx'
make: *** [external_mpifx] Error 2

Please help me on this..

**Comment by aradi** [comment]
Are you sure that the building was successful? Since on the first glance it seems to me as if you were missing the external library `mpifx`. That is not part of the repository, but is a git-submodule, so make sure you check it out as well (see the ``INSTALL.rst`` file for details).

**Comment by periasamy25** [comment]
i was wrong that time.. 
i copy the mpifx and scalapackfx from git-submodule..
Now the **make** was stopped with following error...

/opt/apps/dftbplus-master/_build/external/scalapackfx/blacsfx.f90:151: undefined reference to `igebs2d_'
collect2: error: ld returned 1 exit status
make[1]: *** [dftb+] Error 1
rm extlagrangian.f90 parallelks.f90 parser.f90 hsdutils.f90 slakoeqgrid.f90 thermostat.f90 andersentherm.f90 geoopt.f90 linkedlistr0.f90 spin.f90 bisect.f90 dispuff.f90 gdiis.f90 xlbomd.f90 potentials.f90 mainio.f90 andersonmixer.f90 factorial.f90 intrinsicpr.f90 formatout.f90 dummytherm.f90 qm.f90 angmomentum.f90 broydenmixer.f90 hsdparser.f90 repspline.f90 inputdata.f90 simplemixer.f90 fifo.f90 lapack.f90 dispdftd3.f90 blacsenv.f90 tokenreader.f90 mdintegrator.f90 repcont.f90 mpienv.f90 typegeometry.f90 densitymatrix.f90 dftbplusu.f90 sk.f90 typegeometryhsd.f90 repulsive.f90 densedescr.f90 chargeconstr.f90 sccinit.f90 stress.f90 diismixer.f90 conjgrad.f90 elecconstraints.f90 environment.f90 mixer.f90 assert.f90 interpolation.f90 xmlf90.f90 dftd3.f90 steepdesc.f90 linkedlisti0.f90 sorting.f90 unitconversion.f90 berendsentherm.f90 linkedlistlc0.f90 linkedlistmc0.f90 dispersions.f90 nhctherm.f90 xmlutils.f90 fileid.f90 forces.f90 nonscc.f90 eigensolver.f90 populations.f90 accuracy.f90 scalapackfx.f90 timerarray.f90 linkedlistr2.f90 hermite.f90 numderivs2.f90 memman.f90 pmlocalisation.f90 lapackroutines.f90 spinorbit.f90 charmanip.f90 dispuffdata.f90 energies.f90 linkedlist.f90 commontypes.f90 periodic.f90 randomgenpool.f90 eigenvects.f90 dftbplus.f90 initprogram.f90 main.f90 linemin.f90 io.f90 scalafxext.f90 linkedlisti1.f90 constants.f90 externalcharges.f90 taggedoutput.f90 reppoly.f90 scc.f90 velocityverlet.f90 slakocont.f90 shortgamma.f90 dispcommon.f90 orbitalequiv.f90 message.f90 oldskdata.f90 mdcommon.f90 mpifx.f90 dispslaterkirkw.f90 ranlux.f90 oldcompat.f90 charges.f90 linresp.f90 coulomb.f90 simplealgebra.f90 hsdutils2.f90 shift.f90 orbitals.f90 tempprofile.f90 thirdorder.f90 linkedlistr1.f90 blasroutines.f90 sparse2dense.f90 etemp.f90 globalenv.f90 blas.f90 schedule.f90 linkedlists0.f90 errorfunction.f90 dispiface.f90 timer.f90
make[1]: Leaving directory `/opt/apps/dftbplus-master/_build/prog/dftb+'
make: *** [dftb+] Error 2

pls help me

**Comment by aradi** [comment]
It seems, you don't link any scalapack  or lapack libraries. Don't you get any error before the current one about missing ``-lscalapack`˙or so? You must make sure, those libraries are present on your system.

**Comment by periasamy25** [comment]
Successfully Compiled and installed dftb+ mpi version...
Thank you for your quick response...
