### ISSUE TITLE
DFTB+21.2 with xTB

### ISSUE THREAD

**Issue by ruauar** [dftbplus/dftbplus#920]
I ran the geometry optimization of  adsorption of an organic molecule on the iron surface using DFTB + 21.2, but encountered a problem.

```
-> Unexpected end of data
Path: dftbplusinput/Hamiltonian/xTB/SpinConstants/H
Line: 67-69 (File: dftb_in.hsd)
ShellResolvedScc = Yes
SpinConstants = {
    Fe = {
      -0.015  -0.012  -0.003  -0.012  -0.019  -0.001  -0.003  -0.001  -0.017
    }
C = {
   -0.031 -0.025 -0.025 -0.023
   }
   O = {
   -0.035 -0.030 -0.030 -0.028
   }
  H = {
   -0.072
   }
  N = {
   -0.033 -0.027 -0.027 -0.026
   }
```

**Comment by awvwgk** [comment]
GFN1-xTB uses an extended basis set for hydrogen (1s2s), therefore a 2x2 block of spin constants is required.

**Comment by ruauar** [comment]
I found these spin constants in the manual of DFTB+ 21.2. Could you give me a 2X2 block of spin constants for hydrogen？

**Comment by bhourahine** [comment]
The spin constants you are using have not been fitted for the GFN models, so treat the results with some caution. The documented values are for free atoms in a numerical basis suitable for the DFTB model.

For the hydrogen atom, you could make the approximation that they are all the same values, and give a 2x2 matrix of the -0.072 value.
