### ISSUE TITLE
Fails to install the Python binding into the stage directory

### ISSUE THREAD

**Issue by yurivict** [dftbplus/dftbplus#931]
It prints this error
```
error: could not create '//usr/local/lib/python3.8/site-packages/__init__.py': Permission denied
```
and then succeeds anyway.

The ```install``` target should respect the ```DESTDIR``` variable which contains stage directory.

Version: 21.2
OS: FreeBSD 13

**Comment by awvwgk** [comment]
The installation is setup here

https://github.com/dftbplus/dftbplus/blob/a1a48642e24ea1964057285ab39d3501cf1246ec/tools/dptools/CMakeLists.txt#L1-L5

While `DESTDIR` is referenced, I guess it is read at configure time rather than install here and therefore failing.

**Comment by awvwgk** [comment]
I proposed a patch in #933. Generally, I would recommend to install the Python components as separate packages rather than bundling them with DFTB+ as it provides more control over the installation (we take this approach for packaging on conda-forge as well).

**Comment by yurivict** [comment]
> Generally, I would recommend to install the Python components as separate packages [...]

Are there instructions how to do this for dftbplus?

**Comment by yurivict** [comment]
In order to install python separately cleanly project needs to supply a top-level CMakeLists.txt for python.

Like the ```faiss``` project does [here](https://github.com/facebookresearch/faiss/blob/main/faiss/python/CMakeLists.txt).

**Comment by awvwgk** [comment]
No CMake required, you can install straight via `setup.py` or `pip install` (which is what our CMake is doing anyway).
