### ISSUE TITLE
Please version the file https://www.dftb.org/fileadmin/DFTB/public/slako-unpacked.tar.xz

### ISSUE THREAD

**Issue by yurivict** [dftbplus/dftbplus#934]
It is downloaded by package builders. Lacking version means that when you would update it all packages would become broken because file fingerprint would change.

**Comment by awvwgk** [comment]
The individual SK sets are actually versioned (e.g. https://dftb.org/fileadmin/DFTB/public/slako/3ob/3ob-3-1.tar.xz), the complete collection of all SK sets however is not, and it is probably unwise to rely on this convenience feature for a package distribution.

We were planning to move the SK repositories to a public repository (soon). This should improve the accessibility of the tarballs and possibility to identify stable versions, however it won't necessarily solve the issue with complete SK collection.

cc @aradi

**Comment by aradi** [comment]
@yurivict I've never thought about that aspect. A simple timestamp in the filename would be enough, wouldn't it? (e.g. `slako-packed-20220101.tar.xz`)

**Comment by yurivict** [comment]
> A simple timestamp in the filename would be enough, wouldn't it? (e.g. slako-packed-20220101.tar.xz)

Yes.

**Comment by yurivict** [comment]
ping
