### ISSUE TITLE
Dependencies issues: for some dependencies configure doesn't report what dependencies are used, and their binaries aren't linked to

### ISSUE THREAD

**Issue by yurivict** [dftbplus/dftbplus#937]
I am trying to change dftd4, mctc-lib, mstore, multicharge from submodules to package dependencies.

For 2 of them configure reported that packages are used:
```
-- mctc-lib: Trying to find installed package
-- mctc-lib: Installed package found
-- mstore: Trying to find installed package
-- mstore: Installed package found
```
but for the other 2 it did not print anything.

Furthermore, only ```libmctc-lib.so``` is linked to by ```dftbplus``` binaries, and the other 3 shared libraries aren't linked to.
Either they are used as headers-only libraries, or they aren't used at all.

**Comment by awvwgk** [comment]
Your Portfile does only use `mctc-lib` and `mstore` via `WITH_SDFTD3`, while `dftd4` and `multicharge` are dependencies only required when the option `WITH_TBLITE` is enabled.

**Comment by yurivict** [comment]
That was it, thank you for your help!
