### ISSUE TITLE
Inconsistent option "EigenvectorsAsText = No" in dftb_pin.hsd

### ISSUE THREAD

**Issue by lvgee** [dftbplus/dftbplus#945]
**Describe the bug**
The contents of the file "dftb_pin.hsd" seem to change, even though the original file "dftb_in.hsd" stays the same.
Specifically, the option "EigenvectorsAsText = No" seems to sometimes appear in "dftb_pin.hsd", and sometimes not.

**To Reproduce**
1) Download the stable source from https://dftbplus.org/download/dftb-stable
2) Compile using the instructions given at https://github.com/dftbplus/dftbplus
3) Use the dftb_in.hsd-file given at https://dftbplus-recipes.readthedocs.io/en/latest/basics/firstcalc.html
4) Run the program in _build/app/dftb+ like `./dftb+ && grep "Eigenvectors" dftb_pin.hsd`

**Additional Info**
1. Input-file see above, the only thing I changed is the location of the SK-files
2. DFTB+ Version 21.2, compiled from source (see above), gfortran 9.3.0, cmake 3.16.3 on Ubuntu 20.4.3 LTS
3. For me, sometimes the option "EigenvectorsAsText = No" appears in the dftb_pin.hsd-file, and sometimes it does not. It may take a few runs to see it happening.

I just recently started working with dftb+, so I just might be missing something, apologies if that is the case. The behaviour just seems strange to me. I did not make any changes to the code.

**Comment by aradi** [comment]
@lvgee , welcome in the DFTB+ community.

I've tried to reproduce your problem with a binary built from the current development branch as well as with the official stable version on conda-forge (`21.2 nompi_h8767184_102`). How many times I run, I always have the `EigenvectorsAsText = No` line in my dftb_in.hsd file. Could you eventually try it on your system with the conda-forge binary?

**Comment by lvgee** [comment]
Thank you for your reply. I also tested it with the version you mentioned above on conda-forge, and now I never seem to get the line `EigenvectorsAsText = No` in my dftb_pin.hsd file, but at least the behaviour is consistent. Since you were not able to reproduce the issue, I am assuming it is just something on my end. I will keep looking into this over the next couple of days.

**Comment by lvgee** [comment]
I ran some more tests on a different machine and got the same results with the compiled-from-source-version. I then moved the uninitialized variable out of the `#:if WITH_ARPACK`-block, just for testing, and it indeed seems to fix the issue for me. Thanks for your help with this.
