### ISSUE TITLE
Geometry optimization crashes after x steps

### ISSUE THREAD

**Issue by chem-william** [dftbplus/dftbplus#958]
**Describe the bug**

During a geometry optimization, DFTB+ will crash at the end of one SCF convergence cycle after x amount of geometry steps. It tends to be around 10-20 steps or a few hours.
It crashes with the following error:
```bash
[node629:24295] *** An error occurred in MPI_Allreduce
[node629:24295] *** reported by process [1140981761,0]
[node629:24295] *** on communicator MPI_COMMUNICATOR 3
[node629:24295] *** MPI_ERR_TRUNCATE: message truncated
[node629:24295] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node629:24295] ***    and potentially your MPI job)
```
and the output is the following:
```bash

***  Geometry step: 17

 iSCC Total electronic   Diff electronic      SCC error
    1   -0.66508698E+03    0.00000000E+00    0.39399838E-03
    2   -0.66508758E+03   -0.59935893E-03    0.10037506E-02
    3   -0.66508737E+03    0.20487908E-03    0.74247630E-03
    4   -0.66508732E+03    0.49273099E-04    0.89566171E-03
    5   -0.66508734E+03   -0.21913833E-04    0.27148628E-03
    6   -0.66508757E+03   -0.22876711E-03    0.13624196E-03
    7   -0.66508757E+03   -0.10325336E-05    0.12481772E-03
    8   -0.66508757E+03   -0.16341131E-05    0.22593282E-04
    9   -0.66508758E+03   -0.15157565E-05    0.20741034E-04
   10   -0.66508758E+03    0.10859515E-06    0.12673298E-04
   11   -0.66508758E+03   -0.48634320E-07    0.61873642E-05
   12   -0.66508758E+03   -0.28412160E-07    0.35142784E-05
   13   -0.66508758E+03   -0.24336032E-07    0.16884401E-05
   14   -0.66508758E+03    0.30752290E-09    0.98045134E-06
   15   -0.66508758E+03   -0.60992988E-08    0.58612828E-06
   16   -0.66508758E+03    0.28114755E-09    0.29523479E-06
   17   -0.66508758E+03   -0.44292392E-09    0.17386637E-06
```
**To Reproduce**

It's a rather big structure so I'm not sure whether it will reproduce with a smaller structure. The input, structure, output and error files can be downloaded [here](https://sid.erda.dk/cgi-sid/ls.py?share_id=GSI4uXVYgh)
**Expected behaviour**

**Additional context**

I've tried compiling source code myself and installing it from conda.
```bash
# Name          Version                   Build                                       Channel
dftbplus          21.2                        mpi_openmpi_haf9840c_2    conda-forge
openmpi         4.1.2                       hbfc84c5_0                            conda-forge
```

**Comment by aradi** [comment]
Thanks, I've started a similar calculation and will try to reproduce the behavior.

**Comment by aradi** [comment]
Just a quick feedback: I've got a similar crash on our development server using the conda openmpi library, so at least the problem is reproducible. The error message, however, comes from the very depths of the OpenMPI-library, so I am somewhat inclined to think, that this is an OpenMPI bug. I'll test with other MPI frameworks...

**Comment by chem-william** [comment]
While it sucks that there seems to be a bug, I'm glad that it's at least reproducible on other systems than mine. And thank you for the very quick response!

If you need anymore information from me, just let me know

**Comment by aradi** [comment]
@chem-william Could you as a quick check test, whether you get different behavior if you use an old-style driver? If I use `Driver = ConjugateGradient { MovedAtoms = 17:-192}` I don't get a crash after 17 steps, but the code runs (currently at step 35 and still happily running).

**Comment by chem-william** [comment]
Seeing the same thing. I'm at step 49 and still going strong!

**Comment by chem-william** [comment]
I said that too early.. On step 50 it crashed with the same error :(

**Comment by aradi** [comment]
Just a quick feedback: I still have no idea, where the error comes from. On the other hand, I managed to run your system with an intel/mkl/impi binary and it went through till step 279, where the geometry then properly converged. This could be also a possible workaround on your system for the moment.

**Comment by awvwgk** [comment]
Is this problem unique to GCC OpenMPI version from conda-forge or does it also happen with the GCC MPICH version, *i.e.* is it a general GCC problem or just an OpenMPI problem?

Note that you can use the GCC MPICH variant from conda-forge with Intel MPI or system MPICH (see https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries).

**Comment by aradi** [comment]
Unfortunately, this is not limited to the MPI/Compiler combinations available on Conda. I can reproduce it on dpdevel also with gcc 11.2 & openmpi 4.1. Also there, it predictably stops in the `mpi_all_reduce()` call at a given iteration...

**Comment by awvwgk** [comment]
Running the GCC MPICH variant is stable as far as I can tell (at step 176 now).

**Comment by chem-william** [comment]
I've yet to try with the intel/mkl/impi approach, but installing the MPICH version
```bash
# Name                    Version                   Build  Channel
dftbplus                  21.2            mpi_mpich_h3469437_2    conda-forge
```
with conda still crashes with the following error:
```bash
Fatal error in PMPI_Allreduce: Message truncated, error stack:
PMPI_Allreduce(402)...............................: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x556c21435490, count=260, datatype=MPI_DOUBLE_PRECISION, op=MPI_SUM, comm=comm=0x84000002) failed
PMPI_Allreduce(388)...............................:
MPIR_Allreduce_impl(236)..........................:
MPIR_Allreduce_intra_reduce_scatter_allgather(262):
do_cts(515).......................................: Message truncated; 8881064 bytes received but buffer size is 1040
Fatal error in PMPI_Allreduce: Message truncated, error stack:
PMPI_Allreduce(402)...............................: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x564dbd418560, count=260, datatype=MPI_DOUBLE_PRECISION, op=MPI_SUM, comm=comm=0x84000004) failed
PMPI_Allreduce(388)...............................:
MPIR_Allreduce_impl(236)..........................:
MPIR_Allreduce_intra_reduce_scatter_allgather(262):
do_cts(515).......................................: Message truncated; 8881056 bytes received but buffer size is 1040
```

**Comment by awvwgk** [comment]
Here is my successful run ([dftbplus-958.tar.gz](https://github.com/dftbplus/dftbplus/files/8156473/dftbplus-958.tar.gz)) and the respective environment I used:

```yaml
name: dftbplus
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - chimes-calculator=1.0.0=h0c14de7_1
  - dftbplus=21.2=mpi_mpich_h3469437_2
  - dftd4=3.3.0=hf06ca72_3
  - elpa=2021.11.001=mpi_mpich_h3469437_3
  - elsi=2.8.2=mpi_mpich_h6ba1590_2
  - fftw=3.3.10=nompi_h77c792f_102
  - gawk=5.1.0=h7f98852_0
  - gsl=2.7=he838d99_0
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libgcc-ng=11.2.0=h1d223b6_12
  - libgfortran-ng=11.2.0=h69a702a_12
  - libgfortran5=11.2.0=h5c6108e_12
  - libgomp=11.2.0=h1d223b6_12
  - liblapack=3.9.0=13_linux64_openblas
  - libmbd=0.12.5=mpi_mpich_hb74dc4d_0
  - libnegf=1.0.3=mpi_mpich_h6ba1590_2
  - libnsl=2.0.0=h7f98852_0
  - libomm=1.0.0=mpi_mpich_h6ba1590_2
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libstdcxx-ng=11.2.0=he4da1e4_12
  - libzlib=1.2.11=h36c2ea0_1013
  - matrixswitch=1.0.0=mpi_mpich_h6ba1590_2
  - mctc-lib=0.2.4=h92ddd45_2
  - mpi=1.0=mpich
  - mpich=3.4.3=h846660c_100
  - mpifx=1.2=mpi_mpich_h4345814_0
  - ntpoly=2.7.1=mpi_mpich_h3469437_0
  - plumed=2.7.3=mpi_mpich_hc4d6106_0
  - scalapack=2.1.0=h6ba1590_0
  - scalapackfx=1.0.2=mpi_mpich_hb74dc4d_0
  - simple-dftd3=0.4.2=hb01ceae_1
  - tblite=0.1.0=hf06ca72_2
  - toml-f=0.2.2=h92ddd45_2
  - xdrfile=1.1.4=h7f98852_1
```

**Comment by chem-william** [comment]
Thanks for all the help!

I might've have jumped the gun with my previous comment.
With the conda installed MPICH version, it seems I'm able to converge structures consistently.

I'll leave the issue open, but feel free to close it if this is deemed an issue with the MPI libraries
