### ISSUE TITLE
Convergence option GradAMax is ignored in geometry optimizations

### ISSUE THREAD

**Issue by acroy** [dftbplus/dftbplus#969]
**Describe the bug**
`Convergence.GradAMax` is ignored in geometry optimizations.

**To Reproduce**
1. One can use any input with the new geometry optimization driver. I attach one for H2O. [dftb_in.hsd.txt](https://github.com/dftbplus/dftbplus/files/8177816/dftb_in.hsd.txt)
2. I am using DFTB+ 21.2 from conda-forge on macOS.
3. Independent of the value set for `GradAMax` in the `Convergence` block the last optimization step always gives:
```
total energy  -4.0848354E+00 H       energy change -1.0154065E-08 H
gradient norm  5.3063903E-05 H/a0    max. gradient  2.9367011E-05 H/a0
step length    1.2640396E-04 a0      max. step      1.0316283E-04 a0
```

**Expected behaviour**
According to the manual (page 16) `GradAMax` sets the maximum absolute gradient element in one geometry step to consider optimization converged. Default threshold is 1e-4 Hartree/Bohr.

**Additional context**
Looking into the function `readOptTolerance` in `input/geoopt.F90` apparently the the option is expected to be called `GradElem` instead. Similarly, `DispAMax` is read as `DispElem`.

**Comment by awvwgk** [comment]
Looks like we renamed the keywords in https://github.com/dftbplus/dftbplus/pull/862/commits/6e6c6f0841501738964201a25117be99e19b1437 but didn't correctly update the manual (`GradAMax` –> `GradElem`).

cc @aradi

**Comment by Andrew-S-Rosen** [comment]
FYI, this wasn't updated in the recipes: https://dftbplus-recipes.readthedocs.io/en/latest/basics/firstcalc.html
