### ISSUE TITLE
NaN energy values based on undefined behavior with xTB Hamiltonian

### ISSUE THREAD

**Issue by steinmig** [dftbplus/dftbplus#971]
**Describe the bug**
I observed both normal terminations of a calculation and NaN energy values in the SCF based on an identical input file depending on the mode of execution (binary vs. API). I suspected undefined behavior due to also different behavior based on the compiler and whether I was using python to start the calculations or not.

I wanted to make sure that the error is not on my side with valgrind and could find a case where I could reproduce the NaN result with solely the dftb+ binary.

**To Reproduce**
I compiled the current master with gcc8.3 and intel-oneapi-2021.4 (with underlying gcc10.1)

If I run the attached input file with the dftb+ binary, I get a normal result in both cases. If I run the calculation with valgrind, I still get a normal result with gcc, but the NaN values with the intel compiled binary. Output files are also attached.

(I also got the NaN with non valgrind runs, but those where via the API and are more difficult to reproduce)

[dftb_in.hsd.txt](https://github.com/dftbplus/dftbplus/files/8184021/dftb_in.hsd.txt)
[gcc-normal-out.txt](https://github.com/dftbplus/dftbplus/files/8184023/gcc-normal-out.txt)
[gcc-valgrind-out.txt](https://github.com/dftbplus/dftbplus/files/8184024/gcc-valgrind-out.txt)
[intel-normal-out.txt](https://github.com/dftbplus/dftbplus/files/8184025/intel-normal-out.txt)
[intel-valgrind-out.txt](https://github.com/dftbplus/dftbplus/files/8184026/intel-valgrind-out.txt)

**Comment by awvwgk** [comment]
This issue is rather difficult to track down, if `valgrind` is required to reproduce. Can't promise that I can allocate time for investigating such a special corner case.

**Comment by steinmig** [comment]
For completeness, for me this occurs in ~0.1 % of calculations over different systems (all API calls)

**Comment by awvwgk** [comment]
If you could limit the search space for me by at least narrowing down whether this is issue occurs on the DFTB+ or tblite side (tblite itself, or dftd4, s-dftd3, ...) it would already be of much help.
