### ISSUE TITLE
 GFN2-xTB open-shell calculations

### ISSUE THREAD

**Issue by AndresOrtegaGuerrero** [dftbplus/dftbplus#972]
Dear DFTB+ community,

I was wondering if you could help me with something? How can I enable open-shell systems calculations while using GFN2-xTB ?? I used this option,

```
SpinPolarisation = Colinear {
UnpairedElectrons = 3.0
InitialSpins = {
AtomSpin = {
        Atoms = 1:3
        SpinPerAtom = 1.0}
}
}
```
I keep getting this error -> Missing child: SpinConstants

How can I get these constants for different transition metals or lanthanides in xTB?
Or how can I get the simulations to run? 
Do you have a recipe for running open-shell using xTB in DFTB+?
Should Spinconstants be requested for xTB?
thank you

best,

Andres

**Comment by haneug** [comment]
Dear Andres,

In principle, one can calculate the spin constants via numerical differentiation of atoms using DFT (see for example [Fe](https://pubs.acs.org/doi/abs/10.1021/jp068802p?casa_token=s47O5Uk59sAAAAAA:sO-UnPq-iVtgeqcXL-VhTVHdpf8hR0AYlzkDoxKsAza8qLzPADyuoNzrvmorEaQl82UXwRHffh1_aoOZ)). 

Also, we are currently working on generating and thoroughly testing these spin constants for GFN2-xTB with all elements up to Radon for molecular applications and will finish this work later this year.

best,

Hagen

**Comment by AndresOrtegaGuerrero** [comment]
Dear Hagen, 

Thank you for your reply, 
I was trying to test xTB for different materials that are open-shell Co , Fe, and so on, but I guess I will try for an element, 
Thank you 
best, 

Andres

**Comment by chem-william** [comment]
How's the work coming along with generating the spin constants for GFN2-xTB? I'm very interested in using GFN2-xTB through DFTB+ with a spin-polarized calculation for a molecule containing ruthenium

**Comment by haneug** [comment]
We generated spin constants with PBE and tested them for spin splittings of 3d, 4d, and 5d transition metal complexes with GFN1 and GFN2-xTB. You can find them in the supporting information of our open access paper:
https://doi.org/10.1002/jcc.27185

**Comment by chem-william** [comment]
Wonderful! I'll try them out straightaway. Thank you!

**Comment by KunhuanLiu** [comment]
> We generated spin constants with PBE and tested them for spin splittings of 3d, 4d, and 5d transition metal complexes with GFN1 and GFN2-xTB. You can find them in the supporting information of our open access paper: https://doi.org/10.1002/jcc.27185

Thank you very much for the nice work. Excited to try it out!
