### ISSUE TITLE
Restart MD simulation  - issue

### ISSUE THREAD

**Issue by dveclani** [dftbplus/dftbplus#978]
Dear all,

I've performed molecular dynamics simulations, after a few ps the dynamics stopped for timewall, how can I restart the dynamics simulation? Do you have any restart inputs or procedure?

Waiting for your kind reply.

Best regards,
Daniele Veclani.

**Comment by korintje** [comment]
I really appreciate the great efforts of the developers and researchers of DFTB+ and glad to hear that the MD restart will be easier to use in the future (https://github.com/dftbplus/dftbplus/issues/906#issue-1070294132).

Until it is officially implemented, a tiny script I wrote might be useful for people who want to instantly make MD restart files and collect their results.
https://github.com/korintje/dftbplus_restarter

The script works on a Python with [hsd-python](https://github.com/dftbplus/hsd-python) package. The usage can be seen from the above link.
