### ISSUE TITLE
About the GFN-FF Hamiltonian 

### ISSUE THREAD

**Issue by xiki-tempula** [dftbplus/dftbplus#979]
**Is your feature request related to a problem? Please describe.**
Many thanks @awvwgk for implementing the GFN2-xTB and GFN1-xTB Hamiltonian. I wonder if there is any plan for the GFN-FF? Or it is is a `won't do` due to the different implementation of the GFN-FF?

Say if I would like to do simulated annealing with GFN-FF, I wonder what is the best way forward? Thank you.

**Comment by awvwgk** [comment]
Currently the GFN-FF seems a bit out-of-scope for DFTB+, since it is not a tight-binding method it would be difficult to fit it into the structure of this program. While I wouldn't completely rule this out as a future feature for DFTB+, I'm personally not interested in implementing it here.
