### ISSUE TITLE
The simulated-annealin page is lacking the code

### ISSUE THREAD

**Issue by xiki-tempula** [dftbplus/dftbplus#984]
**Describe the bug**
The page https://dftbplus-recipes.readthedocs.io/en/latest/moleculardynamics/annealing.html#simulated-annealing lacks code for recipe.

**Comment by aradi** [comment]
The example was to probably too big (especially the geometry) to be included into the text. However, as noted in the [Before you start section](https://dftbplus-recipes.readthedocs.io/en/latest/introduction.html#before-you-start), you can download the input for all examples, which also contain the full, self contained example for the simulated annealing.

**Comment by xiki-tempula** [comment]
@aradi I see. Thanks.
